using GisAPI.Application.Features.Admin.Companies.Commands.ResetCompanyData;

namespace GisAPI.Tests.Application.Admin;

/// <summary>
/// Catalogue RÉEL de la base de production TN relevé le 10/09/2026 (information_schema + pg_constraint) :
/// 81 tables, 132 clés étrangères. Seules les colonnes utiles au plan sont listées.
/// </summary>
public static class TnCatalogFixture
{
    public static CompanyDataCatalog Load()
    {
        var tables = new List<CatalogTable>
        {
            T("AccidentClaimDocuments", Array.Empty<string>(), new string[] { "ClaimId" }),
            T("AccidentClaimThirdParties", Array.Empty<string>(), new string[] { "ClaimId" }),
            T("AccidentClaims", new string[] { "CompanyId" }, new string[] { "CompanyId", "CreatedByUserId", "DriverId", "Id", "VehicleId" }),
            T("accident_event_documents", Array.Empty<string>(), new string[] { "accident_event_id", "file_url" }),
            T("accident_event_third_parties", Array.Empty<string>(), new string[] { "accident_event_id" }),
            T("accident_events", new string[] { "company_id" }, new string[] { "company_id", "id", "pdf_report_url" }),
            T("acquisition_payments", new string[] { "company_id" }, new string[] { "company_id", "receipt_url", "vehicle_id" }),
            T("ai_chat_messages", new string[] { "company_id" }, new string[] { "company_id", "user_id", "vehicle_id" }),
            T("alert_emails", new string[] { "company_id" }, new string[] { "company_id" }),
            T("audit_logs", new string[] { "CompanyId", "SocieteId" }, new string[] { "CompanyId", "SocieteId", "UserId" }),
            T("brands", Array.Empty<string>(), new string[] { "Id" }),
            T("chat_messages", new string[] { "company_id" }, new string[] { "company_id", "receiver_id", "sender_id" }),
            T("contracts", new string[] { "CompanyId" }, new string[] { "CompanyId", "VehicleId" }),
            T("daily_statistics", new string[] { "CompanyId" }, new string[] { "CompanyId", "VehicleId" }),
            T("departments", new string[] { "CompanyId" }, new string[] { "CompanyId", "Id" }),
            T("device_commands", new string[] { "company_id" }, new string[] { "company_id", "device_id" }),
            T("device_events", new string[] { "company_id" }, new string[] { "company_id", "device_id" }),
            T("driver_assignments", new string[] { "CompanyId" }, new string[] { "AssignedByUserId", "CompanyId", "DriverId", "VehicleId" }),
            T("driver_scores", new string[] { "CompanyId" }, new string[] { "CompanyId", "DriverId" }),
            T("drivers", new string[] { "company_id" }, new string[] { "assigned_vehicle_id", "company_id", "id" }),
            T("driving_events", new string[] { "CompanyId" }, new string[] { "CompanyId", "DriverId", "TripId", "VehicleId" }),
            T("estimate_items", Array.Empty<string>(), new string[] { "EstimateId" }),
            T("estimates", new string[] { "CompanyId" }, new string[] { "CompanyId", "Id" }),
            T("fuel_entries", new string[] { "company_id" }, new string[] { "company_id", "driver_id", "fuel_type_id", "vehicle_id" }),
            T("fuel_pricing", new string[] { "CompanyId" }, new string[] { "CompanyId", "FuelTypeId" }),
            T("fuel_records", new string[] { "company_id" }, new string[] { "company_id", "device_id", "driver_id", "vehicle_id" }),
            T("fuel_types", Array.Empty<string>(), new string[] { "Id" }),
            T("geofence_events", new string[] { "company_id" }, new string[] { "company_id", "geofence_id", "vehicle_id" }),
            T("geofence_groups", new string[] { "company_id" }, new string[] { "company_id", "id" }),
            T("geofence_vehicles", Array.Empty<string>(), new string[] { "geofence_id", "vehicle_id" }),
            T("geofences", new string[] { "company_id" }, new string[] { "company_id", "group_id", "id" }),
            T("gps_alerts", new string[] { "company_id" }, new string[] { "company_id", "device_id", "resolved_by_user_id", "vehicle_id" }),
            T("gps_devices", new string[] { "company_id" }, new string[] { "company_id", "id" }),
            T("gps_devices_orphans_bak_20260715", new string[] { "company_id" }, new string[] { "company_id" }),
            T("gps_positions", Array.Empty<string>(), new string[] { "device_id" }),
            T("invoice_scan_logs", new string[] { "company_id" }, new string[] { "company_id" }),
            T("maintenance_alert_settings", new string[] { "company_id" }, new string[] { "company_id" }),
            T("maintenance_logs", new string[] { "company_id" }, new string[] { "company_id", "cost_id", "photos", "schedule_id", "supplier_id", "template_id", "vehicle_id" }),
            T("maintenance_notifications", new string[] { "company_id" }, new string[] { "company_id", "schedule_id", "template_id", "vehicle_id" }),
            T("maintenance_parts", Array.Empty<string>(), new string[] { "maintenance_record_id" }),
            T("maintenance_records", new string[] { "company_id" }, new string[] { "company_id", "id", "invoice_url", "vehicle_id" }),
            T("maintenance_template_parts", Array.Empty<string>(), new string[] { "preferred_supplier_id", "template_id" }),
            T("maintenance_templates", new string[] { "company_id" }, new string[] { "company_id", "id" }),
            T("notifications", new string[] { "CompanyId" }, new string[] { "ActionUrl", "CompanyId", "UserId" }),
            T("part_categories", Array.Empty<string>(), new string[] { "Id" }),
            T("part_inventory", new string[] { "company_id" }, new string[] { "company_id", "id", "supplier_id" }),
            T("part_pricing", new string[] { "CompanyId" }, new string[] { "CompanyId", "PartId" }),
            T("part_transactions", new string[] { "company_id" }, new string[] { "company_id", "created_by_user_id", "maintenance_record_id", "part_id", "supplier_id", "vehicle_id" }),
            T("poi_visits", new string[] { "company_id" }, new string[] { "company_id", "poi_id", "vehicle_id" }),
            T("points_of_interest", new string[] { "SocieteId", "company_id" }, new string[] { "SocieteId", "company_id", "id" }),
            T("refresh_tokens", Array.Empty<string>(), new string[] { "UserId" }),
            T("repair_parts", Array.Empty<string>(), new string[] { "repair_id" }),
            T("repairs", new string[] { "societe_id" }, new string[] { "id", "societe_id", "vehicle_id" }),
            T("report_schedules", new string[] { "CompanyId", "SocieteId" }, new string[] { "CompanyId", "CreatedByUserId", "SocieteId" }),
            T("reports", new string[] { "CompanyId", "SocieteId" }, new string[] { "CompanyId", "CreatedByUserId", "SocieteId" }),
            T("reservations", new string[] { "CompanyId" }, new string[] { "ApprovedByUserId", "AssignedDriverId", "CompanyId", "RequestedByUserId", "VehicleId" }),
            T("roles", new string[] { "societe_id" }, new string[] { "id", "societe_id" }),
            T("societes", Array.Empty<string>(), new string[] { "id", "logo_url", "subscription_type_id" }),
            T("speed_limit_alerts", new string[] { "CompanyId", "SocieteId" }, new string[] { "AcknowledgedById", "CompanyId", "SocieteId", "VehicleId" }),
            T("subscription_orders", new string[] { "company_id" }, new string[] { "company_id", "subscription_type_id" }),
            T("subscription_types", Array.Empty<string>(), new string[] { "id" }),
            T("supplier_services", Array.Empty<string>(), new string[] { "supplier_id" }),
            T("suppliers", new string[] { "CompanyId", "SocieteId" }, new string[] { "CompanyId", "Id", "SocieteId" }),
            T("tour_pauses", Array.Empty<string>(), new string[] { "TourId" }),
            T("tour_waypoints", Array.Empty<string>(), new string[] { "TourId", "geofence_id" }),
            T("tours", new string[] { "CompanyId" }, new string[] { "CompanyId", "Id" }),
            T("tow_events", new string[] { "company_id" }, new string[] { "company_id", "device_id", "vehicle_id" }),
            T("trip_waypoints", Array.Empty<string>(), new string[] { "TripId" }),
            T("trips", new string[] { "CompanyId" }, new string[] { "CompanyId", "DriverId", "Id", "VehicleId" }),
            T("user_device_tokens", Array.Empty<string>(), new string[] { "user_id" }),
            T("user_vehicles", Array.Empty<string>(), new string[] { "assigned_by", "user_id", "vehicle_id" }),
            T("users", new string[] { "company_id" }, new string[] { "company_id", "id", "role_id" }),
            T("vehicle_costs", new string[] { "company_id" }, new string[] { "accident_event_id", "company_id", "created_by_user_id", "id", "receipt_url", "vehicle_id" }),
            T("vehicle_documents", Array.Empty<string>(), new string[] { "file_url", "vehicle_id" }),
            T("vehicle_load_periods", new string[] { "company_id" }, new string[] { "company_id", "vehicle_id" }),
            T("vehicle_maintenance_schedules", new string[] { "company_id" }, new string[] { "company_id", "id", "template_id", "vehicle_id" }),
            T("vehicle_models", Array.Empty<string>(), new string[] { "BrandId" }),
            T("vehicle_parts", Array.Empty<string>(), new string[] { "CategoryId", "Id" }),
            T("vehicle_stops", new string[] { "company_id" }, new string[] { "company_id", "device_id", "driver_id", "geofence_id", "vehicle_id" }),
            T("vehicle_user_assignments", Array.Empty<string>(), new string[] { "user_id", "vehicle_id" }),
            T("vehicles", new string[] { "company_id" }, new string[] { "DepartmentId", "assigned_driver_id", "assigned_supervisor_id", "company_id", "gps_device_id", "id" }),
        };
        var fks = new List<CatalogForeignKey>
        {
            new("AccidentClaimDocuments", "ClaimId", "AccidentClaims", "Id", 'c'),
            new("AccidentClaimThirdParties", "ClaimId", "AccidentClaims", "Id", 'c'),
            new("AccidentClaims", "CreatedByUserId", "users", "id", 'a'),
            new("AccidentClaims", "DriverId", "drivers", "id", 'n'),
            new("AccidentClaims", "VehicleId", "vehicles", "id", 'c'),
            new("accident_event_documents", "accident_event_id", "accident_events", "id", 'c'),
            new("accident_event_third_parties", "accident_event_id", "accident_events", "id", 'c'),
            new("acquisition_payments", "vehicle_id", "vehicles", "id", 'c'),
            new("ai_chat_messages", "company_id", "societes", "id", 'a'),
            new("ai_chat_messages", "user_id", "users", "id", 'r'),
            new("ai_chat_messages", "vehicle_id", "vehicles", "id", 'r'),
            new("audit_logs", "SocieteId", "societes", "id", 'a'),
            new("audit_logs", "UserId", "users", "id", 'a'),
            new("chat_messages", "company_id", "societes", "id", 'a'),
            new("chat_messages", "receiver_id", "users", "id", 'r'),
            new("chat_messages", "sender_id", "users", "id", 'r'),
            new("contracts", "VehicleId", "vehicles", "id", 'c'),
            new("daily_statistics", "VehicleId", "vehicles", "id", 'c'),
            new("departments", "CompanyId", "societes", "id", 'c'),
            new("device_commands", "device_id", "gps_devices", "id", 'a'),
            new("device_events", "device_id", "gps_devices", "id", 'a'),
            new("driver_assignments", "AssignedByUserId", "users", "id", 'a'),
            new("driver_assignments", "DriverId", "drivers", "id", 'c'),
            new("driver_assignments", "VehicleId", "vehicles", "id", 'c'),
            new("driver_scores", "DriverId", "drivers", "id", 'c'),
            new("drivers", "assigned_vehicle_id", "vehicles", "id", 'n'),
            new("drivers", "company_id", "societes", "id", 'c'),
            new("driving_events", "DriverId", "drivers", "id", 'n'),
            new("driving_events", "TripId", "trips", "Id", 'a'),
            new("driving_events", "VehicleId", "vehicles", "id", 'c'),
            new("estimate_items", "EstimateId", "estimates", "Id", 'c'),
            new("estimates", "CompanyId", "societes", "id", 'n'),
            new("fuel_entries", "driver_id", "drivers", "id", 'n'),
            new("fuel_entries", "fuel_type_id", "fuel_types", "Id", 'r'),
            new("fuel_entries", "vehicle_id", "vehicles", "id", 'n'),
            new("fuel_pricing", "CompanyId", "societes", "id", 'c'),
            new("fuel_pricing", "FuelTypeId", "fuel_types", "Id", 'c'),
            new("fuel_records", "device_id", "gps_devices", "id", 'a'),
            new("fuel_records", "driver_id", "drivers", "id", 'n'),
            new("fuel_records", "vehicle_id", "vehicles", "id", 'c'),
            new("geofence_events", "geofence_id", "geofences", "id", 'c'),
            new("geofence_events", "vehicle_id", "vehicles", "id", 'c'),
            new("geofence_groups", "company_id", "societes", "id", 'c'),
            new("geofence_vehicles", "geofence_id", "geofences", "id", 'c'),
            new("geofence_vehicles", "vehicle_id", "vehicles", "id", 'c'),
            new("geofences", "company_id", "societes", "id", 'c'),
            new("geofences", "group_id", "geofence_groups", "id", 'n'),
            new("gps_alerts", "device_id", "gps_devices", "id", 'a'),
            new("gps_alerts", "resolved_by_user_id", "users", "id", 'a'),
            new("gps_alerts", "vehicle_id", "vehicles", "id", 'a'),
            new("gps_devices", "company_id", "societes", "id", 'c'),
            new("gps_positions", "device_id", "gps_devices", "id", 'c'),
            new("maintenance_logs", "cost_id", "vehicle_costs", "id", 'n'),
            new("maintenance_logs", "schedule_id", "vehicle_maintenance_schedules", "id", 'n'),
            new("maintenance_logs", "supplier_id", "suppliers", "Id", 'n'),
            new("maintenance_logs", "template_id", "maintenance_templates", "id", 'c'),
            new("maintenance_logs", "vehicle_id", "vehicles", "id", 'c'),
            new("maintenance_notifications", "schedule_id", "vehicle_maintenance_schedules", "id", 'c'),
            new("maintenance_notifications", "template_id", "maintenance_templates", "id", 'c'),
            new("maintenance_notifications", "vehicle_id", "vehicles", "id", 'c'),
            new("maintenance_parts", "maintenance_record_id", "maintenance_records", "id", 'c'),
            new("maintenance_records", "vehicle_id", "vehicles", "id", 'c'),
            new("maintenance_template_parts", "preferred_supplier_id", "suppliers", "Id", 'n'),
            new("maintenance_template_parts", "template_id", "maintenance_templates", "id", 'c'),
            new("notifications", "UserId", "users", "id", 'c'),
            new("part_inventory", "supplier_id", "suppliers", "Id", 'n'),
            new("part_pricing", "CompanyId", "societes", "id", 'c'),
            new("part_pricing", "PartId", "vehicle_parts", "Id", 'c'),
            new("part_transactions", "created_by_user_id", "users", "id", 'n'),
            new("part_transactions", "maintenance_record_id", "maintenance_records", "id", 'n'),
            new("part_transactions", "part_id", "part_inventory", "id", 'c'),
            new("part_transactions", "supplier_id", "suppliers", "Id", 'n'),
            new("part_transactions", "vehicle_id", "vehicles", "id", 'n'),
            new("poi_visits", "poi_id", "points_of_interest", "id", 'c'),
            new("poi_visits", "vehicle_id", "vehicles", "id", 'c'),
            new("points_of_interest", "SocieteId", "societes", "id", 'a'),
            new("points_of_interest", "company_id", "societes", "id", 'c'),
            new("refresh_tokens", "UserId", "users", "id", 'c'),
            new("repair_parts", "repair_id", "repairs", "id", 'c'),
            new("repairs", "societe_id", "societes", "id", 'c'),
            new("repairs", "vehicle_id", "vehicles", "id", 'c'),
            new("report_schedules", "CreatedByUserId", "users", "id", 'c'),
            new("report_schedules", "SocieteId", "societes", "id", 'a'),
            new("reports", "CreatedByUserId", "users", "id", 'a'),
            new("reports", "SocieteId", "societes", "id", 'a'),
            new("reservations", "ApprovedByUserId", "users", "id", 'a'),
            new("reservations", "AssignedDriverId", "drivers", "id", 'n'),
            new("reservations", "RequestedByUserId", "users", "id", 'a'),
            new("reservations", "VehicleId", "vehicles", "id", 'c'),
            new("roles", "societe_id", "societes", "id", 'c'),
            new("societes", "subscription_type_id", "subscription_types", "id", 'a'),
            new("speed_limit_alerts", "AcknowledgedById", "users", "id", 'a'),
            new("speed_limit_alerts", "SocieteId", "societes", "id", 'a'),
            new("speed_limit_alerts", "VehicleId", "vehicles", "id", 'c'),
            new("subscription_orders", "company_id", "societes", "id", 'a'),
            new("subscription_orders", "subscription_type_id", "subscription_types", "id", 'a'),
            new("supplier_services", "supplier_id", "suppliers", "Id", 'c'),
            new("suppliers", "SocieteId", "societes", "id", 'a'),
            new("tour_pauses", "TourId", "tours", "Id", 'c'),
            new("tour_waypoints", "TourId", "tours", "Id", 'c'),
            new("tour_waypoints", "geofence_id", "geofences", "id", 'n'),
            new("tow_events", "device_id", "gps_devices", "id", 'a'),
            new("tow_events", "vehicle_id", "vehicles", "id", 'a'),
            new("trip_waypoints", "TripId", "trips", "Id", 'c'),
            new("trips", "DriverId", "drivers", "id", 'n'),
            new("trips", "VehicleId", "vehicles", "id", 'c'),
            new("user_device_tokens", "user_id", "users", "id", 'c'),
            new("user_vehicles", "assigned_by", "users", "id", 'n'),
            new("user_vehicles", "user_id", "users", "id", 'c'),
            new("user_vehicles", "vehicle_id", "vehicles", "id", 'c'),
            new("users", "company_id", "societes", "id", 'c'),
            new("users", "role_id", "roles", "id", 'r'),
            new("vehicle_costs", "accident_event_id", "accident_events", "id", 'n'),
            new("vehicle_costs", "created_by_user_id", "users", "id", 'a'),
            new("vehicle_costs", "vehicle_id", "vehicles", "id", 'c'),
            new("vehicle_documents", "vehicle_id", "vehicles", "id", 'c'),
            new("vehicle_load_periods", "vehicle_id", "vehicles", "id", 'c'),
            new("vehicle_maintenance_schedules", "template_id", "maintenance_templates", "id", 'c'),
            new("vehicle_maintenance_schedules", "vehicle_id", "vehicles", "id", 'c'),
            new("vehicle_models", "BrandId", "brands", "Id", 'c'),
            new("vehicle_parts", "CategoryId", "part_categories", "Id", 'c'),
            new("vehicle_stops", "device_id", "gps_devices", "id", 'a'),
            new("vehicle_stops", "driver_id", "drivers", "id", 'n'),
            new("vehicle_stops", "geofence_id", "geofences", "id", 'a'),
            new("vehicle_stops", "vehicle_id", "vehicles", "id", 'c'),
            new("vehicle_user_assignments", "user_id", "users", "id", 'c'),
            new("vehicle_user_assignments", "vehicle_id", "vehicles", "id", 'c'),
            new("vehicles", "DepartmentId", "departments", "Id", 'a'),
            new("vehicles", "assigned_driver_id", "drivers", "id", 'n'),
            new("vehicles", "assigned_supervisor_id", "users", "id", 'n'),
            new("vehicles", "company_id", "societes", "id", 'c'),
            new("vehicles", "gps_device_id", "gps_devices", "id", 'n'),
        };
        return new CompanyDataCatalog(tables, fks);
    }

    private static CatalogTable T(string name, string[] companyCols, string[] allCols) => new(name, companyCols, allCols);
}
