namespace GisAPI.DTOs;

// UserListDto is now in GisAPI.Application.Features.Users namespace

public record CreateUserRequest(
    string FirstName,
    string LastName,
    string Email,
    string? Phone,
    string Password,
    int RoleId,
    int[]? AssignedVehicleIds = null,
    string? EmployeeRole = null,
    string? PermitNumber = null,
    string? PermitType = null,
    DateTime? PermitExpiry = null,
    string? CIN = null,
    DateTime? DateOfBirth = null,
    DateTime? HireDate = null,
    string? AccessLevel = "user",
    bool CanMonitoring = true,
    bool CanVehicles = true,
    bool CanDrivers = false,
    bool CanReports = false,
    bool CanGeofences = false,
    bool CanMaintenance = false,
    bool CanCosts = false,
    bool CanDocuments = false,
    bool CanAccidents = false,
    bool CanUsers = false,
    bool CanSettings = false,
    bool CanSuppliers = false,
    bool CanFleetManagement = false,
    bool CanFuel = false,
    bool CanTours = false,
    bool CanPlayback = false,
    // Per-report permissions
    bool CanReportTrips = true,
    bool CanReportFuel = true,
    bool CanReportSpeed = true,
    bool CanReportStops = true,
    bool CanReportMileage = true,
    bool CanReportCosts = true,
    bool CanReportMaintenance = true,
    bool CanReportDaily = true,
    bool CanReportMonthly = true,
    bool CanReportMileagePeriod = true,
    bool CanReportSpeedInfraction = true,
    bool CanReportDrivingBehavior = true,
    bool CanReportMonthlyCosts = true
);

public record UpdateUserRequest(
    string FirstName,
    string LastName,
    string Email,
    string? Phone,
    int? RoleId,
    string? Status,
    int[]? AssignedVehicleIds = null,
    string? AccessLevel = null,
    bool? CanMonitoring = null,
    bool? CanVehicles = null,
    bool? CanDrivers = null,
    bool? CanReports = null,
    bool? CanGeofences = null,
    bool? CanMaintenance = null,
    bool? CanCosts = null,
    bool? CanDocuments = null,
    bool? CanAccidents = null,
    bool? CanUsers = null,
    bool? CanSettings = null,
    bool? CanSuppliers = null,
    bool? CanFleetManagement = null,
    bool? CanFuel = null,
    bool? CanTours = null,
    bool? CanPlayback = null,
    // Per-report permissions
    bool? CanReportTrips = null,
    bool? CanReportFuel = null,
    bool? CanReportSpeed = null,
    bool? CanReportStops = null,
    bool? CanReportMileage = null,
    bool? CanReportCosts = null,
    bool? CanReportMaintenance = null,
    bool? CanReportDaily = null,
    bool? CanReportMonthly = null,
    bool? CanReportMileagePeriod = null,
    bool? CanReportSpeedInfraction = null,
    bool? CanReportDrivingBehavior = null,
    bool? CanReportMonthlyCosts = null
);

public record UserSettingsDto(
    string Language,
    string Timezone,
    string Currency,
    string DateFormat,
    string DistanceUnit,
    string SpeedUnit,
    string VolumeUnit,
    string TemperatureUnit
);
