using GisAPI.Application.Common.Interfaces;

namespace GisAPI.Application.Features.Users.Commands.CreateUser;

public record CreateUserCommand(
    string FirstName,
    string LastName,
    string Email,
    string? Phone,
    string Password,
    int RoleId,
    int[]? AssignedVehicleIds = null,
    string? EmployeeRole = null,
    string? PermitNumber = null,
    string? PermitType = null,
    DateTime? PermitExpiry = null,
    string? CIN = null,
    DateTime? DateOfBirth = null,
    DateTime? HireDate = null,
    string? AccessLevel = "user",
    bool CanMonitoring = true,
    bool CanVehicles = true,
    bool CanDrivers = false,
    bool CanReports = false,
    bool CanGeofences = false,
    bool CanMaintenance = false,
    bool CanCosts = false,
    bool CanFuel = false,
    bool CanDocuments = false,
    bool CanAccidents = false,
    bool CanUsers = false,
    bool CanSettings = false,
    bool CanSuppliers = false,
    bool CanFleetManagement = false,
    bool CanTours = false,
    bool CanPlayback = false,
    // Per-report permissions
    bool CanReportTrips = true,
    bool CanReportFuel = true,
    bool CanReportSpeed = true,
    bool CanReportStops = true,
    bool CanReportMileage = true,
    bool CanReportCosts = true,
    bool CanReportMaintenance = true,
    bool CanReportDaily = true,
    bool CanReportMonthly = true,
    bool CanReportMileagePeriod = true,
    bool CanReportSpeedInfraction = true,
    bool CanReportDrivingBehavior = true,
    bool CanReportMonthlyCosts = true,
    // Alert email preferences
    bool AlertAssurance = false,
    bool AlertTaxeCirculation = false,
    bool AlertVisiteTechnique = false,
    bool AlertEntretien = false
) : ICommand<UserListDto>;
