-- 029: Périodes de chargement (tonnage) pour l'analyse de consommation par segments
-- Le tonnage déclaré est hérité par les segments de X km dont le point médian
-- tombe dans [start_time, end_time] (end_time NULL = période en cours).
-- Idempotent : rejouable sans effet.

CREATE TABLE IF NOT EXISTS vehicle_load_periods (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id  INTEGER NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
    start_time  TIMESTAMPTZ NOT NULL,
    end_time    TIMESTAMPTZ NULL,
    tonnage_t   NUMERIC(6,2) NOT NULL,
    notes       VARCHAR(300) NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    company_id  INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_vehicle_load_periods_vehicle_id_start_time"
    ON vehicle_load_periods (vehicle_id, start_time);

CREATE INDEX IF NOT EXISTS "IX_vehicle_load_periods_company_id"
    ON vehicle_load_periods (company_id);
