-- 044 — Échéancier d'acquisition persisté (apport, mensualités de crédit/leasing,
-- achat comptant) — recette client du 07/09/2026.
--
-- CONSTAT — Les échéances d'acquisition n'existaient nulle part en base : elles
-- étaient RECALCULÉES à chaque affichage par deux générateurs identiques
-- (expenses.component.ts et AcquisitionSchedule.cs) et par l'échéancier de la
-- fiche véhicule, à partir des sept champs vehicles.acquisition_type /
-- purchase_price / purchase_date / leasing_monthly_payment /
-- leasing_duration_months / leasing_start_date / leasing_payment_day.
-- « Payé » n'était qu'une présomption calendaire (date atteinte = payé) : aucun
-- paiement réel n'était connu, impossible de marquer une mensualité payée à une
-- autre date ou pour un autre montant, d'y joindre une quittance ou d'en ignorer
-- une. Sur TN au 07/09/2026 : 4 contrats leasing + 7 apports/achats, soit 175
-- lignes virtuelles dont 66 « comptées ».
--
-- POURQUOI UNE TABLE — une ligne par échéance, générée et RECALÉE par l'API
-- (AcquisitionScheduleSync, à chaque enregistrement du véhicule et à la première
-- lecture de l'écran Dépenses) : les lignes « planned » suivent le contrat, les
-- lignes « paid » / « skipped » sont des faits saisis par l'exploitant et ne
-- disparaissent jamais, même si le contrat change. Le tableau de bord somme
-- désormais cette table (paid, ou planned dont la date est atteinte) et garde
-- le calcul à la volée en repli pour les véhicules jamais synchronisés.
-- AUCUN backfill SQL ici : la génération est paresseuse, faite par l'API, pour
-- qu'une seule implémentation (C#) porte les règles d'échéancier.
--
-- CHECK sur kind et status — délibéré, contrairement à 043 : les valeurs ne
-- viennent que du code serveur (jamais d'une saisie mobile), et une faute de
-- frappe dans un statut fausserait silencieusement le « Coût total ».
-- Aucune contrainte de ce type n'existait sur vehicles.acquisition_type ni
-- vehicle_costs.type (vérifié sur TN) : pas de précédent à respecter.
--
-- SUPPRESSION D'UN VÉHICULE — FK ON DELETE CASCADE ; VehicleDeletionHelper
-- découvre de toute façon la FK par le catalogue et purge la table lui-même.
--
-- ORDRE DE DÉPLOIEMENT — CE SQL SE JOUE AVANT LE NOUVEAU POD API, sur DZ puis
-- TN. La table est mappée par EF (entité AcquisitionPayment) : un pod démarré
-- avant la migration renverrait « 42P01 relation does not exist » sur l'écran
-- Dépenses et sur GET /api/acquisition-payments (le tableau de bord, lui, se
-- rabat sur l'ancien calcul).

CREATE TABLE IF NOT EXISTS acquisition_payments (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id   INTEGER NOT NULL,
    vehicle_id   INTEGER NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
    kind         VARCHAR(20) NOT NULL,                     -- apport | mensualite | achat
    seq          INTEGER NOT NULL,                         -- mensualite : 1..N ; apport/achat : 1
    due_date     DATE NOT NULL,
    amount       NUMERIC(12,2) NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'planned',   -- planned | paid | skipped
    paid_at      TIMESTAMPTZ NULL,
    paid_amount  NUMERIC(12,2) NULL,
    receipt_url  VARCHAR(500) NULL,
    note         VARCHAR(500) NULL,
    generated    BOOLEAN NOT NULL DEFAULT true,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ux_acquisition_payments_vehicle_kind_seq UNIQUE (vehicle_id, kind, seq),
    CONSTRAINT ck_acquisition_payments_kind   CHECK (kind IN ('apport', 'mensualite', 'achat')),
    CONSTRAINT ck_acquisition_payments_status CHECK (status IN ('planned', 'paid', 'skipped'))
);

CREATE INDEX IF NOT EXISTS idx_acquisition_payments_company_due
    ON acquisition_payments (company_id, due_date);

CREATE INDEX IF NOT EXISTS idx_acquisition_payments_vehicle
    ON acquisition_payments (vehicle_id);

COMMENT ON TABLE acquisition_payments IS
    'Échéancier d''acquisition persisté (apport, mensualités, achat comptant) — généré et recalé par l''API depuis vehicles.acquisition_* (AcquisitionScheduleSync), jamais par SQL. planned = suit le contrat ; paid / skipped = fait saisi, conservé même hors contrat.';

COMMENT ON COLUMN acquisition_payments.kind IS
    'apport (contrat leasing) | mensualite (1..N) | achat (comptant)';

COMMENT ON COLUMN acquisition_payments.status IS
    'planned = compté dès que due_date est atteinte | paid = compté (paid_amount ?? amount) | skipped = jamais compté';
