-- 052 — Crédit IA MENSUEL de la société, en JETONS (demandes de Slim du 22/09/2026 :
-- « une barre de progression de contexte qui se remet à zéro chaque mois », puis « et bien
-- sûr le quota inclut l'utilisation de l'IA »). Le crédit couvre TOUTE l'IA de la société :
-- scan de factures, assistant IA, comparaison et rapport véhicule, rapport IA flotte et ses
-- questions, explication d'une tranche de consommation, récit d'accident. Seul l'assistant
-- PUBLIC d'avant connexion (sans société) n'est pas compté.
--
-- CONSTAT — Le scan de factures IA était plafonné en NOMBRE de scans par mois
-- (societes.invoice_scan_monthly_limit : NULL = 20, 0 = désactivé), affiché « 12/20 ce
-- mois » à côté du bouton. Or un scan ne coûte pas toujours la même chose : mesuré sur TN
-- (13 scans), de 1 953 à 3 957 jetons Groq, 3 000 en moyenne (p90 3 631) — une photo floue
-- déclenche une passe corrective qui double la note. Le reste de l'IA (une réponse de
-- l'assistant : ~2 400 jetons, 3 400 au plus) n'était plafonné par rien.
--
-- POURQUOI UNE NOUVELLE COLONNE — le budget devient un crédit de jetons par mois civil
-- (UTC) : invoice_scan_monthly_tokens (nom historique : d'abord réservé au scan), NULL =
-- défaut plateforme 60 000, 0 = IA désactivée pour la société. invoice_scan_monthly_limit
-- n'est PAS réutilisée : ses valeurs sont des SCANS, les relire comme des jetons ferait
-- passer une société réglée à 50 scans à 50 jetons, donc à zéro. Elle est conservée et
-- CONVERTIE À LA LECTURE (limite × 3 000, bornée à 10 000 000, 0 reste 0) tant que la
-- nouvelle colonne est NULL. Chaque enregistrement depuis la fiche admin écrit les jetons ET
-- une OMBRE dans l'ancienne colonne, pour le retour arrière : vide (défaut) → NULL ;
-- 0 (désactivé) → 0 ; sinon l'équivalent en scans (jetons / 3 000, au moins 1). Le nouveau
-- code ne la relit plus dès que les jetons sont renseignés.
--
-- POURQUOI UNE NOUVELLE TABLE — la consommation du mois = jetons des scans (déjà journalisés
-- dans invoice_scan_logs à chaque scan réussi, index ix_invoice_scan_logs_company_id_created_at
-- existant) + jetons de TOUS LES AUTRES appels à l'IA, jusqu'ici non journalisés (seul
-- l'assistant gardait ses jetons sur ai_chat_messages, sans les autres fonctions).
-- ai_usage_logs : une ligne par appel réussi (société, utilisateur — NULL pour un récit
-- d'accident rédigé par le système —, fonction, jetons). Les scans n'y sont PAS recopiés :
-- aucun double comptage. Un tokens_used à 0 (fournisseur muet) est compté par l'API pour
-- une estimation par fonction, jamais pour zéro. Index (company_id, created_at) : la somme
-- du mois est lue avant chaque appel payant.
--
-- AUCUNE DONNÉE MODIFIÉE — ajout d'une colonne NULL et d'une table vide, sans UPDATE :
-- chaque société garde exactement son budget actuel (ancien quota converti, ou défaut).
-- La consommation hors scan démarre à zéro au déploiement (rien n'est repris de
-- ai_chat_messages).
--
-- ATTENTION AVANT DÉPLOIEMENT — une société à 0 (ancien quota ou nouveau crédit) perd
-- désormais TOUTE l'IA (assistant, rapports IA…), plus seulement le scan. À lister d'abord :
--   SELECT id, name, invoice_scan_monthly_limit, invoice_scan_monthly_tokens FROM societes
--   WHERE invoice_scan_monthly_limit = 0 OR invoice_scan_monthly_tokens = 0;
--
-- ORDRE DE DÉPLOIEMENT — ce SQL se joue AVANT le pod API qui mappe
-- Societe.InvoiceScanMonthlyTokens et AiUsageLog (sinon 42703 sur toute lecture d'une
-- société : login cassé pour tout le monde ; 42P01 sur tout appel à l'IA). DZ puis TN.
-- Retour arrière du pod API : la colonne et la table peuvent rester en place, l'ancien code
-- les ignore et relit invoice_scan_monthly_limit, que la fiche tient à jour (ombre
-- ci-dessus) — une société désactivée le reste, une société réglée garde l'équivalent de son
-- crédit en scans. Seul écart : un crédit qui n'est pas un multiple de 3 000 jetons est
-- arrondi au scan inférieur.

ALTER TABLE societes ADD COLUMN IF NOT EXISTS invoice_scan_monthly_tokens integer NULL;

COMMENT ON COLUMN societes.invoice_scan_monthly_tokens IS
    'Crédit IA mensuel de la société, en jetons Groq, pour TOUTE l''IA (scans, assistant, rapports IA, explications, récits d''accident) — NULL = défaut plateforme 60 000, 0 = IA désactivée. Remis à zéro le 1er de chaque mois (UTC). Prioritaire sur invoice_scan_monthly_limit (ancien quota en scans, converti à 3 000 jetons par scan).';

CREATE TABLE IF NOT EXISTS ai_usage_logs (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  integer     NOT NULL,
    user_id     integer     NULL,
    feature     varchar(32) NOT NULL,
    tokens_used integer     NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_ai_usage_logs_company_id_created_at
    ON ai_usage_logs (company_id, created_at);

COMMENT ON TABLE ai_usage_logs IS
    'Un appel à l''IA réussi, hors scan de facture (ceux-ci restent dans invoice_scan_logs) : consommation du crédit IA mensuel de la société. feature = assistant_chat, vehicle_compare, vehicle_report, fleet_report, fleet_report_ask, consumption_explain, accident_narrative. tokens_used = 0 : consommation non rendue par Groq, comptée pour une estimation par fonction.';
