-- 053 — Catalogue des marques et modèles de la fiche véhicule (Karim, 25/09/2026).
--
-- Constat : les listes « Marque » et « Modèle » de la fiche véhicule ne proposaient
-- que 27 marques, dont 8 sans aucun modèle (BMW, Honda, MAN, Mazda, Mitsubishi,
-- Nissan, Suzuki, Volvo), et 128 modèles. Le client ne trouvait pas son véhicule ;
-- le tutoriel devait laisser passer Marque et Modèle vides. Karim : « ajoute dans
-- la liste déroulante de marque et modèle toutes les marques avec leurs modèles »
-- — voitures, utilitaires, camions et bus vendus en Tunisie, en Algérie et en
-- France, modèles des vingt dernières années environ.
--
-- Karim, même jour : « mettre toutes les marques en majuscule » — elles étaient
-- mélangées (« AUDI », « KIA » à côté de « Renault », « Peugeot »).
--
-- Modèle : rejouable. 1) Les noms de marques existants passent en majuscules (seule
-- modification ; vehicles.brand, le texte déjà enregistré sur chaque véhicule, n'est
-- pas touché — la fiche retrouve sa marque sans tenir compte de la casse). 2) Ajout des
-- marques et modèles absents : une marque est reconnue par son nom normalisé
-- (minuscules, sans accents, sans espaces ni ponctuation : « AUDI » = « Audi »,
-- « T.CROSS » = « T-Cross ») ; un modèle, par ce nom normalisé DANS SA marque. Rien
-- n'est supprimé : les doublons et les erreurs déjà présents en base (TN :
-- 45 couples en double, « LEON » rangé chez KIA, types « van »/« hatchback » que la
-- fiche ne connaît pas) restent à traiter à part, sur décision de Karim.
-- vehicle_models."VehicleType" reprend les valeurs de la liste « Type » de la fiche
-- (citadine, suv, utilitaire, camion, other) : choisir le modèle y positionne le type.
-- 111 marques, 1147 modèles dans le catalogue ci-dessous.
--
-- Tables : brands ("Id" identité, "Name", "LogoUrl", "IsActive", "CreatedAt") et
-- vehicle_models ("Id" identité, "BrandId" → brands ON DELETE CASCADE, "Name",
-- "VehicleType", "IsActive", "CreatedAt"). Aucune colonne mappée par EF n'est
-- ajoutée : l'ordre SQL / pod API est indifférent.

BEGIN;

CREATE OR REPLACE FUNCTION pg_temp.norm(t text) RETURNS text LANGUAGE sql IMMUTABLE AS $$
  SELECT regexp_replace(
           translate(lower(coalesce(t, '')),
                     'àáâãäåçèéêëìíîïñòóôõöšùúûüýÿžÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÑÒÓÔÕÖŠÙÚÛÜÝŸŽ',
                     'aaaaaaceeeeiiiinooooosuuuuyyzaaaaaaceeeeiiiinooooosuuuuyyz'),
           '[^a-z0-9]', '', 'g')
$$;

CREATE TEMP TABLE catalogue (marque text NOT NULL, modele text NOT NULL, type text NOT NULL) ON COMMIT DROP;

INSERT INTO catalogue (marque, modele, type) VALUES
  ('ABARTH', '124 Spider', 'citadine'),
  ('ABARTH', '500', 'citadine'),
  ('ABARTH', '500e', 'citadine'),
  ('ABARTH', '595', 'citadine'),
  ('ABARTH', '600e', 'suv'),
  ('ABARTH', '695', 'citadine'),
  ('AIXAM', 'City', 'citadine'),
  ('AIXAM', 'Coupé', 'citadine'),
  ('AIXAM', 'Crossline', 'citadine'),
  ('AIXAM', 'Minauto', 'citadine'),
  ('ALFA ROMEO', '4C', 'citadine'),
  ('ALFA ROMEO', '147', 'citadine'),
  ('ALFA ROMEO', '156', 'citadine'),
  ('ALFA ROMEO', '159', 'citadine'),
  ('ALFA ROMEO', '166', 'citadine'),
  ('ALFA ROMEO', 'Brera', 'citadine'),
  ('ALFA ROMEO', 'Giulia', 'citadine'),
  ('ALFA ROMEO', 'Giulietta', 'citadine'),
  ('ALFA ROMEO', 'GT', 'citadine'),
  ('ALFA ROMEO', 'Junior', 'suv'),
  ('ALFA ROMEO', 'MiTo', 'citadine'),
  ('ALFA ROMEO', 'Spider', 'citadine'),
  ('ALFA ROMEO', 'Stelvio', 'suv'),
  ('ALFA ROMEO', 'Tonale', 'suv'),
  ('ALPINE', 'A110', 'citadine'),
  ('ALPINE', 'A290', 'citadine'),
  ('ALPINE', 'A390', 'suv'),
  ('ASTON MARTIN', 'DB9', 'citadine'),
  ('ASTON MARTIN', 'DB11', 'citadine'),
  ('ASTON MARTIN', 'DB12', 'citadine'),
  ('ASTON MARTIN', 'DBS', 'citadine'),
  ('ASTON MARTIN', 'DBX', 'suv'),
  ('ASTON MARTIN', 'Rapide', 'citadine'),
  ('ASTON MARTIN', 'Vanquish', 'citadine'),
  ('ASTON MARTIN', 'Vantage', 'citadine'),
  ('AUDI', 'A1', 'citadine'),
  ('AUDI', 'A2', 'citadine'),
  ('AUDI', 'A3', 'citadine'),
  ('AUDI', 'A4', 'citadine'),
  ('AUDI', 'A5', 'citadine'),
  ('AUDI', 'A6', 'citadine'),
  ('AUDI', 'A7', 'citadine'),
  ('AUDI', 'A8', 'citadine'),
  ('AUDI', 'e-tron', 'suv'),
  ('AUDI', 'e-tron GT', 'citadine'),
  ('AUDI', 'Q2', 'suv'),
  ('AUDI', 'Q3', 'suv'),
  ('AUDI', 'Q4 e-tron', 'suv'),
  ('AUDI', 'Q5', 'suv'),
  ('AUDI', 'Q6 e-tron', 'suv'),
  ('AUDI', 'Q7', 'suv'),
  ('AUDI', 'Q8', 'suv'),
  ('AUDI', 'R8', 'citadine'),
  ('AUDI', 'TT', 'citadine'),
  ('BAIC', 'BJ40', 'suv'),
  ('BAIC', 'D20', 'citadine'),
  ('BAIC', 'U5 Plus', 'citadine'),
  ('BAIC', 'X7', 'suv'),
  ('BAIC', 'X25', 'suv'),
  ('BAIC', 'X35', 'suv'),
  ('BAIC', 'X55', 'suv'),
  ('BENTLEY', 'Arnage', 'citadine'),
  ('BENTLEY', 'Azure', 'citadine'),
  ('BENTLEY', 'Bentayga', 'suv'),
  ('BENTLEY', 'Brooklands', 'citadine'),
  ('BENTLEY', 'Continental GT', 'citadine'),
  ('BENTLEY', 'Flying Spur', 'citadine'),
  ('BENTLEY', 'Mulsanne', 'citadine'),
  ('BMW', 'i3', 'citadine'),
  ('BMW', 'i4', 'citadine'),
  ('BMW', 'i5', 'citadine'),
  ('BMW', 'i7', 'citadine'),
  ('BMW', 'i8', 'citadine'),
  ('BMW', 'iX', 'suv'),
  ('BMW', 'iX1', 'suv'),
  ('BMW', 'iX2', 'suv'),
  ('BMW', 'iX3', 'suv'),
  ('BMW', 'Série 1', 'citadine'),
  ('BMW', 'Série 2', 'citadine'),
  ('BMW', 'Série 3', 'citadine'),
  ('BMW', 'Série 4', 'citadine'),
  ('BMW', 'Série 5', 'citadine'),
  ('BMW', 'Série 6', 'citadine'),
  ('BMW', 'Série 7', 'citadine'),
  ('BMW', 'Série 8', 'citadine'),
  ('BMW', 'X1', 'suv'),
  ('BMW', 'X2', 'suv'),
  ('BMW', 'X3', 'suv'),
  ('BMW', 'X4', 'suv'),
  ('BMW', 'X5', 'suv'),
  ('BMW', 'X6', 'suv'),
  ('BMW', 'X7', 'suv'),
  ('BMW', 'XM', 'suv'),
  ('BMW', 'Z4', 'citadine'),
  ('BOVA', 'Futura', 'other'),
  ('BOVA', 'Magiq', 'other'),
  ('BYD', 'Atto 2', 'suv'),
  ('BYD', 'Atto 3', 'suv'),
  ('BYD', 'Dolphin', 'citadine'),
  ('BYD', 'Dolphin Surf', 'citadine'),
  ('BYD', 'Han', 'citadine'),
  ('BYD', 'Seal', 'citadine'),
  ('BYD', 'Seal 6', 'citadine'),
  ('BYD', 'Seal U', 'suv'),
  ('BYD', 'Sealion 5', 'suv'),
  ('BYD', 'Sealion 7', 'suv'),
  ('BYD', 'Song Plus', 'suv'),
  ('BYD', 'Tang', 'suv'),
  ('CADILLAC', 'BLS', 'citadine'),
  ('CADILLAC', 'CTS', 'citadine'),
  ('CADILLAC', 'Escalade', 'suv'),
  ('CADILLAC', 'Lyriq', 'suv'),
  ('CADILLAC', 'SRX', 'suv'),
  ('CADILLAC', 'STS', 'citadine'),
  ('CADILLAC', 'XT4', 'suv'),
  ('CHANGAN', 'Hunter', 'utilitaire'),
  ('CHANGAN', 'Star Truck', 'utilitaire'),
  ('CHANGAN', 'Star Van', 'utilitaire'),
  ('CHERY', 'Arrizo 5', 'citadine'),
  ('CHERY', 'Arrizo 8', 'citadine'),
  ('CHERY', 'Cowin', 'citadine'),
  ('CHERY', 'Fulwin', 'citadine'),
  ('CHERY', 'Himla', 'utilitaire'),
  ('CHERY', 'QQ', 'citadine'),
  ('CHERY', 'S18', 'citadine'),
  ('CHERY', 'Tiggo 1X', 'suv'),
  ('CHERY', 'Tiggo 2', 'suv'),
  ('CHERY', 'Tiggo 3X', 'suv'),
  ('CHERY', 'Tiggo 4', 'suv'),
  ('CHERY', 'Tiggo 7', 'suv'),
  ('CHERY', 'Tiggo 8', 'suv'),
  ('CHERY', 'Tiggo 9', 'suv'),
  ('CHEVROLET', 'Aveo', 'citadine'),
  ('CHEVROLET', 'Camaro', 'citadine'),
  ('CHEVROLET', 'Captiva', 'suv'),
  ('CHEVROLET', 'Corvette', 'citadine'),
  ('CHEVROLET', 'Cruze', 'citadine'),
  ('CHEVROLET', 'Epica', 'citadine'),
  ('CHEVROLET', 'Evanda', 'citadine'),
  ('CHEVROLET', 'Kalos', 'citadine'),
  ('CHEVROLET', 'Lacetti', 'citadine'),
  ('CHEVROLET', 'Malibu', 'citadine'),
  ('CHEVROLET', 'Matiz', 'citadine'),
  ('CHEVROLET', 'Nubira', 'citadine'),
  ('CHEVROLET', 'Optra', 'citadine'),
  ('CHEVROLET', 'Orlando', 'citadine'),
  ('CHEVROLET', 'Rezzo', 'citadine'),
  ('CHEVROLET', 'Sail', 'citadine'),
  ('CHEVROLET', 'Spark', 'citadine'),
  ('CHEVROLET', 'Trax', 'suv'),
  ('CHEVROLET', 'Volt', 'citadine'),
  ('CHRYSLER', '300C', 'citadine'),
  ('CHRYSLER', 'Crossfire', 'citadine'),
  ('CHRYSLER', 'PT Cruiser', 'citadine'),
  ('CHRYSLER', 'Sebring', 'citadine'),
  ('CHRYSLER', 'Voyager', 'citadine'),
  ('CITROËN', 'Ami', 'citadine'),
  ('CITROËN', 'Berlingo', 'utilitaire'),
  ('CITROËN', 'C-Crosser', 'suv'),
  ('CITROËN', 'C-Elysée', 'citadine'),
  ('CITROËN', 'C-Zero', 'citadine'),
  ('CITROËN', 'C1', 'citadine'),
  ('CITROËN', 'C2', 'citadine'),
  ('CITROËN', 'C3', 'citadine'),
  ('CITROËN', 'C3 Aircross', 'suv'),
  ('CITROËN', 'C3 Picasso', 'citadine'),
  ('CITROËN', 'C3 Pluriel', 'citadine'),
  ('CITROËN', 'C4', 'citadine'),
  ('CITROËN', 'C4 Aircross', 'suv'),
  ('CITROËN', 'C4 Cactus', 'citadine'),
  ('CITROËN', 'C4 Picasso', 'citadine'),
  ('CITROËN', 'C4 SpaceTourer', 'citadine'),
  ('CITROËN', 'C4 X', 'citadine'),
  ('CITROËN', 'C5', 'citadine'),
  ('CITROËN', 'C5 Aircross', 'suv'),
  ('CITROËN', 'C5 X', 'citadine'),
  ('CITROËN', 'C6', 'citadine'),
  ('CITROËN', 'C8', 'citadine'),
  ('CITROËN', 'C15', 'utilitaire'),
  ('CITROËN', 'Jumper', 'utilitaire'),
  ('CITROËN', 'Jumpy', 'utilitaire'),
  ('CITROËN', 'Nemo', 'utilitaire'),
  ('CITROËN', 'SpaceTourer', 'utilitaire'),
  ('CITROËN', 'Xsara', 'citadine'),
  ('CITROËN', 'Xsara Picasso', 'citadine'),
  ('CUPRA', 'Ateca', 'suv'),
  ('CUPRA', 'Born', 'citadine'),
  ('CUPRA', 'Formentor', 'suv'),
  ('CUPRA', 'Leon', 'citadine'),
  ('CUPRA', 'Tavascan', 'suv'),
  ('CUPRA', 'Terramar', 'suv'),
  ('DACIA', 'Bigster', 'suv'),
  ('DACIA', 'Dokker', 'utilitaire'),
  ('DACIA', 'Duster', 'suv'),
  ('DACIA', 'Jogger', 'citadine'),
  ('DACIA', 'Lodgy', 'citadine'),
  ('DACIA', 'Logan', 'citadine'),
  ('DACIA', 'Sandero', 'citadine'),
  ('DACIA', 'Spring', 'citadine'),
  ('DAF', 'CF', 'camion'),
  ('DAF', 'LF', 'camion'),
  ('DAF', 'XB', 'camion'),
  ('DAF', 'XD', 'camion'),
  ('DAF', 'XF', 'camion'),
  ('DAF', 'XG', 'camion'),
  ('DAIHATSU', 'Charade', 'citadine'),
  ('DAIHATSU', 'Copen', 'citadine'),
  ('DAIHATSU', 'Cuore', 'citadine'),
  ('DAIHATSU', 'Materia', 'citadine'),
  ('DAIHATSU', 'Sirion', 'citadine'),
  ('DAIHATSU', 'Terios', 'suv'),
  ('DAIHATSU', 'Trevis', 'citadine'),
  ('DFSK', 'C31', 'utilitaire'),
  ('DFSK', 'C32', 'utilitaire'),
  ('DFSK', 'C35', 'utilitaire'),
  ('DFSK', 'E5', 'suv'),
  ('DFSK', 'EC75', 'utilitaire'),
  ('DFSK', 'Glory 500', 'suv'),
  ('DFSK', 'Glory 580', 'suv'),
  ('DFSK', 'Glory iX5', 'suv'),
  ('DFSK', 'K01', 'utilitaire'),
  ('DFSK', 'K02', 'utilitaire'),
  ('DFSK', 'K05', 'utilitaire'),
  ('DFSK', 'Seres 3', 'suv'),
  ('DODGE', 'Avenger', 'citadine'),
  ('DODGE', 'Caliber', 'citadine'),
  ('DODGE', 'Journey', 'suv'),
  ('DODGE', 'Nitro', 'suv'),
  ('DONGFENG', 'AX7', 'suv'),
  ('DONGFENG', 'Box', 'citadine'),
  ('DONGFENG', 'Captain', 'camion'),
  ('DONGFENG', 'Duolika', 'camion'),
  ('DONGFENG', 'Huge', 'suv'),
  ('DONGFENG', 'Rich', 'utilitaire'),
  ('DONGFENG', 'Shine', 'citadine'),
  ('DONGFENG', 'Shine GS', 'suv'),
  ('DONGFENG', 'Shine Max', 'citadine'),
  ('DONGFENG', 'Tianlong', 'camion'),
  ('DS', 'DS 3', 'citadine'),
  ('DS', 'DS 4', 'citadine'),
  ('DS', 'DS 5', 'citadine'),
  ('DS', 'DS 7', 'suv'),
  ('DS', 'DS 9', 'citadine'),
  ('DS', 'N°8', 'suv'),
  ('FAW', 'J5', 'camion'),
  ('FAW', 'J6', 'camion'),
  ('FERRARI', '12Cilindri', 'citadine'),
  ('FERRARI', '296 GTB', 'citadine'),
  ('FERRARI', '458 Italia', 'citadine'),
  ('FERRARI', '488 GTB', 'citadine'),
  ('FERRARI', '599 GTB Fiorano', 'citadine'),
  ('FERRARI', '612 Scaglietti', 'citadine'),
  ('FERRARI', '812 Superfast', 'citadine'),
  ('FERRARI', 'California', 'citadine'),
  ('FERRARI', 'F8 Tributo', 'citadine'),
  ('FERRARI', 'F12berlinetta', 'citadine'),
  ('FERRARI', 'F430', 'citadine'),
  ('FERRARI', 'FF', 'citadine'),
  ('FERRARI', 'GTC4Lusso', 'citadine'),
  ('FERRARI', 'Portofino', 'citadine'),
  ('FERRARI', 'Purosangue', 'suv'),
  ('FERRARI', 'Roma', 'citadine'),
  ('FERRARI', 'SF90 Stradale', 'citadine'),
  ('FIAT', '124 Spider', 'citadine'),
  ('FIAT', '500', 'citadine'),
  ('FIAT', '500L', 'citadine'),
  ('FIAT', '500X', 'suv'),
  ('FIAT', '600', 'suv'),
  ('FIAT', 'Albea', 'citadine'),
  ('FIAT', 'Bravo', 'citadine'),
  ('FIAT', 'Croma', 'citadine'),
  ('FIAT', 'Doblò', 'utilitaire'),
  ('FIAT', 'Ducato', 'utilitaire'),
  ('FIAT', 'Fiorino', 'utilitaire'),
  ('FIAT', 'Freemont', 'suv'),
  ('FIAT', 'Fullback', 'utilitaire'),
  ('FIAT', 'Grande Panda', 'citadine'),
  ('FIAT', 'Idea', 'citadine'),
  ('FIAT', 'Linea', 'citadine'),
  ('FIAT', 'Multipla', 'citadine'),
  ('FIAT', 'Palio', 'citadine'),
  ('FIAT', 'Panda', 'citadine'),
  ('FIAT', 'Punto', 'citadine'),
  ('FIAT', 'Qubo', 'citadine'),
  ('FIAT', 'Scudo', 'utilitaire'),
  ('FIAT', 'Sedici', 'suv'),
  ('FIAT', 'Seicento', 'citadine'),
  ('FIAT', 'Siena', 'citadine'),
  ('FIAT', 'Stilo', 'citadine'),
  ('FIAT', 'Strada', 'utilitaire'),
  ('FIAT', 'Talento', 'utilitaire'),
  ('FIAT', 'Tipo', 'citadine'),
  ('FIAT', 'Topolino', 'citadine'),
  ('FIAT', 'Ulysse', 'citadine'),
  ('FORD', 'B-Max', 'citadine'),
  ('FORD', 'Bronco', 'suv'),
  ('FORD', 'C-Max', 'citadine'),
  ('FORD', 'Capri', 'suv'),
  ('FORD', 'EcoSport', 'suv'),
  ('FORD', 'Edge', 'suv'),
  ('FORD', 'Explorer', 'suv'),
  ('FORD', 'F-Max', 'camion'),
  ('FORD', 'Fiesta', 'citadine'),
  ('FORD', 'Focus', 'citadine'),
  ('FORD', 'Fusion', 'citadine'),
  ('FORD', 'Galaxy', 'citadine'),
  ('FORD', 'Ka', 'citadine'),
  ('FORD', 'Kuga', 'suv'),
  ('FORD', 'Mondeo', 'citadine'),
  ('FORD', 'Mustang', 'citadine'),
  ('FORD', 'Mustang Mach-E', 'suv'),
  ('FORD', 'Puma', 'suv'),
  ('FORD', 'Ranger', 'utilitaire'),
  ('FORD', 'S-Max', 'citadine'),
  ('FORD', 'Tourneo Connect', 'citadine'),
  ('FORD', 'Tourneo Courier', 'citadine'),
  ('FORD', 'Tourneo Custom', 'utilitaire'),
  ('FORD', 'Transit', 'utilitaire'),
  ('FORD', 'Transit Connect', 'utilitaire'),
  ('FORD', 'Transit Courier', 'utilitaire'),
  ('FORD', 'Transit Custom', 'utilitaire'),
  ('FOTON', 'Auman', 'camion'),
  ('FOTON', 'Aumark', 'camion'),
  ('FOTON', 'Gratour', 'utilitaire'),
  ('FOTON', 'Ollin', 'camion'),
  ('FOTON', 'Toano', 'utilitaire'),
  ('FOTON', 'Tunland', 'utilitaire'),
  ('FOTON', 'View', 'utilitaire'),
  ('FOTON', 'Wonder', 'utilitaire'),
  ('GEELY', 'Azkarra', 'suv'),
  ('GEELY', 'Cityray', 'suv'),
  ('GEELY', 'CK', 'citadine'),
  ('GEELY', 'Coolray', 'suv'),
  ('GEELY', 'Emgrand', 'citadine'),
  ('GEELY', 'EX2', 'citadine'),
  ('GEELY', 'EX5', 'suv'),
  ('GEELY', 'GX3', 'suv'),
  ('GEELY', 'MK', 'citadine'),
  ('GEELY', 'Monjaro', 'suv'),
  ('GEELY', 'Ray', 'citadine'),
  ('GEELY', 'Starray', 'suv'),
  ('GEELY', 'Tugella', 'suv'),
  ('GOLDEN DRAGON', 'XML6122', 'other'),
  ('GOLDEN DRAGON', 'XML6127', 'other'),
  ('GOUPIL', 'G3', 'utilitaire'),
  ('GOUPIL', 'G4', 'utilitaire'),
  ('GOUPIL', 'G5', 'utilitaire'),
  ('GOUPIL', 'G6', 'utilitaire'),
  ('GREAT WALL', 'Florid', 'citadine'),
  ('GREAT WALL', 'Hover', 'suv'),
  ('GREAT WALL', 'Poer', 'utilitaire'),
  ('GREAT WALL', 'Voleex C30', 'citadine'),
  ('GREAT WALL', 'Voleex C50', 'citadine'),
  ('GREAT WALL', 'Wingle', 'utilitaire'),
  ('HAVAL', 'Dargo', 'suv'),
  ('HAVAL', 'H2', 'suv'),
  ('HAVAL', 'H6', 'suv'),
  ('HAVAL', 'Jolion', 'suv'),
  ('HAVAL', 'M4', 'suv'),
  ('HEULIEZ BUS', 'GX 127', 'other'),
  ('HEULIEZ BUS', 'GX 137', 'other'),
  ('HEULIEZ BUS', 'GX 317', 'other'),
  ('HEULIEZ BUS', 'GX 327', 'other'),
  ('HEULIEZ BUS', 'GX 337', 'other'),
  ('HEULIEZ BUS', 'GX 417', 'other'),
  ('HEULIEZ BUS', 'GX 427', 'other'),
  ('HEULIEZ BUS', 'GX 437', 'other'),
  ('HIGER', 'KLQ6122', 'other'),
  ('HIGER', 'KLQ6129', 'other'),
  ('HINO', 'Série 300', 'camion'),
  ('HINO', 'Série 500', 'camion'),
  ('HINO', 'Série 700', 'camion'),
  ('HONDA', 'Accord', 'citadine'),
  ('HONDA', 'City', 'citadine'),
  ('HONDA', 'Civic', 'citadine'),
  ('HONDA', 'CR-V', 'suv'),
  ('HONDA', 'CR-Z', 'citadine'),
  ('HONDA', 'e', 'citadine'),
  ('HONDA', 'e:Ny1', 'suv'),
  ('HONDA', 'FR-V', 'citadine'),
  ('HONDA', 'HR-V', 'suv'),
  ('HONDA', 'Insight', 'citadine'),
  ('HONDA', 'Jazz', 'citadine'),
  ('HONDA', 'Legend', 'citadine'),
  ('HONDA', 'NSX', 'citadine'),
  ('HONDA', 'S2000', 'citadine'),
  ('HONDA', 'Stream', 'citadine'),
  ('HONDA', 'ZR-V', 'suv'),
  ('HUMMER', 'H2', 'suv'),
  ('HUMMER', 'H3', 'suv'),
  ('HYUNDAI', 'Accent', 'citadine'),
  ('HYUNDAI', 'Atos', 'citadine'),
  ('HYUNDAI', 'Bayon', 'suv'),
  ('HYUNDAI', 'County', 'other'),
  ('HYUNDAI', 'Coupé', 'citadine'),
  ('HYUNDAI', 'Creta', 'suv'),
  ('HYUNDAI', 'Elantra', 'citadine'),
  ('HYUNDAI', 'Getz', 'citadine'),
  ('HYUNDAI', 'Grand i10', 'citadine'),
  ('HYUNDAI', 'Grandeur', 'citadine'),
  ('HYUNDAI', 'H-1', 'utilitaire'),
  ('HYUNDAI', 'H100', 'utilitaire'),
  ('HYUNDAI', 'H350', 'utilitaire'),
  ('HYUNDAI', 'HD35', 'utilitaire'),
  ('HYUNDAI', 'HD65', 'camion'),
  ('HYUNDAI', 'HD72', 'camion'),
  ('HYUNDAI', 'HD78', 'camion'),
  ('HYUNDAI', 'i10', 'citadine'),
  ('HYUNDAI', 'i20', 'citadine'),
  ('HYUNDAI', 'i30', 'citadine'),
  ('HYUNDAI', 'i40', 'citadine'),
  ('HYUNDAI', 'Inster', 'citadine'),
  ('HYUNDAI', 'Ioniq', 'citadine'),
  ('HYUNDAI', 'Ioniq 5', 'suv'),
  ('HYUNDAI', 'Ioniq 6', 'citadine'),
  ('HYUNDAI', 'Ioniq 9', 'suv'),
  ('HYUNDAI', 'ix20', 'citadine'),
  ('HYUNDAI', 'ix35', 'suv'),
  ('HYUNDAI', 'ix55', 'suv'),
  ('HYUNDAI', 'Kona', 'suv'),
  ('HYUNDAI', 'Matrix', 'citadine'),
  ('HYUNDAI', 'Mighty', 'camion'),
  ('HYUNDAI', 'Nexo', 'suv'),
  ('HYUNDAI', 'Palisade', 'suv'),
  ('HYUNDAI', 'Porter', 'utilitaire'),
  ('HYUNDAI', 'Santa Fe', 'suv'),
  ('HYUNDAI', 'Sonata', 'citadine'),
  ('HYUNDAI', 'Staria', 'utilitaire'),
  ('HYUNDAI', 'Terracan', 'suv'),
  ('HYUNDAI', 'Trajet', 'citadine'),
  ('HYUNDAI', 'Tucson', 'suv'),
  ('HYUNDAI', 'Universe', 'other'),
  ('HYUNDAI', 'Veloster', 'citadine'),
  ('HYUNDAI', 'Venue', 'suv'),
  ('HYUNDAI', 'Xcient', 'camion'),
  ('INFINITI', 'EX', 'suv'),
  ('INFINITI', 'FX', 'suv'),
  ('INFINITI', 'G', 'citadine'),
  ('INFINITI', 'M', 'citadine'),
  ('INFINITI', 'Q30', 'citadine'),
  ('INFINITI', 'Q50', 'citadine'),
  ('INFINITI', 'Q60', 'citadine'),
  ('INFINITI', 'Q70', 'citadine'),
  ('INFINITI', 'QX30', 'suv'),
  ('INFINITI', 'QX50', 'suv'),
  ('INFINITI', 'QX70', 'suv'),
  ('IRISBUS', 'Agora', 'other'),
  ('IRISBUS', 'Ares', 'other'),
  ('IRISBUS', 'Arway', 'other'),
  ('IRISBUS', 'Axer', 'other'),
  ('IRISBUS', 'Citelis', 'other'),
  ('IRISBUS', 'Crealis', 'other'),
  ('IRISBUS', 'Cristalis', 'other'),
  ('IRISBUS', 'Crossway', 'other'),
  ('IRISBUS', 'Evadys', 'other'),
  ('IRISBUS', 'Iliade', 'other'),
  ('IRISBUS', 'Magelys', 'other'),
  ('IRISBUS', 'Recreo', 'other'),
  ('IRIZAR', 'Century', 'other'),
  ('IRIZAR', 'i4', 'other'),
  ('IRIZAR', 'i6', 'other'),
  ('IRIZAR', 'i8', 'other'),
  ('IRIZAR', 'ie tram', 'other'),
  ('IRIZAR', 'PB', 'other'),
  ('ISUZU', 'Citibus', 'other'),
  ('ISUZU', 'D-Max', 'utilitaire'),
  ('ISUZU', 'FSR', 'camion'),
  ('ISUZU', 'FTR', 'camion'),
  ('ISUZU', 'FVR', 'camion'),
  ('ISUZU', 'MU-X', 'suv'),
  ('ISUZU', 'NKR', 'camion'),
  ('ISUZU', 'NLR', 'camion'),
  ('ISUZU', 'NMR', 'camion'),
  ('ISUZU', 'Novo', 'other'),
  ('ISUZU', 'NPR', 'camion'),
  ('ISUZU', 'NQR', 'camion'),
  ('ISUZU', 'Turquoise', 'other'),
  ('ISUZU', 'Visigo', 'other'),
  ('IVECO', 'Crealis', 'other'),
  ('IVECO', 'Crossway', 'other'),
  ('IVECO', 'Daily', 'utilitaire'),
  ('IVECO', 'E-Way', 'other'),
  ('IVECO', 'Eurocargo', 'camion'),
  ('IVECO', 'Evadys', 'other'),
  ('IVECO', 'Magelys', 'other'),
  ('IVECO', 'S-Way', 'camion'),
  ('IVECO', 'Stralis', 'camion'),
  ('IVECO', 'T-Way', 'camion'),
  ('IVECO', 'Trakker', 'camion'),
  ('IVECO', 'Urbanway', 'other'),
  ('IVECO', 'X-Way', 'camion'),
  ('JAC', 'Gallop', 'camion'),
  ('JAC', 'J2', 'citadine'),
  ('JAC', 'J3', 'citadine'),
  ('JAC', 'J5', 'citadine'),
  ('JAC', 'J6', 'citadine'),
  ('JAC', 'J7', 'citadine'),
  ('JAC', 'JS2', 'suv'),
  ('JAC', 'JS3', 'suv'),
  ('JAC', 'JS4', 'suv'),
  ('JAC', 'JS8', 'suv'),
  ('JAC', 'Série N', 'camion'),
  ('JAC', 'T8', 'utilitaire'),
  ('JAECOO', 'J5', 'suv'),
  ('JAECOO', 'J7', 'suv'),
  ('JAECOO', 'J8', 'suv'),
  ('JAGUAR', 'E-Pace', 'suv'),
  ('JAGUAR', 'F-Pace', 'suv'),
  ('JAGUAR', 'F-Type', 'citadine'),
  ('JAGUAR', 'I-Pace', 'suv'),
  ('JAGUAR', 'S-Type', 'citadine'),
  ('JAGUAR', 'X-Type', 'citadine'),
  ('JAGUAR', 'XE', 'citadine'),
  ('JAGUAR', 'XF', 'citadine'),
  ('JAGUAR', 'XJ', 'citadine'),
  ('JAGUAR', 'XK', 'citadine'),
  ('JEEP', 'Avenger', 'suv'),
  ('JEEP', 'Cherokee', 'suv'),
  ('JEEP', 'Commander', 'suv'),
  ('JEEP', 'Compass', 'suv'),
  ('JEEP', 'Gladiator', 'utilitaire'),
  ('JEEP', 'Grand Cherokee', 'suv'),
  ('JEEP', 'Patriot', 'suv'),
  ('JEEP', 'Renegade', 'suv'),
  ('JEEP', 'Wrangler', 'suv'),
  ('JETOUR', 'Dashing', 'suv'),
  ('JETOUR', 'T2', 'suv'),
  ('JETOUR', 'X70', 'suv'),
  ('JETOUR', 'X70 Plus', 'suv'),
  ('JETOUR', 'X90 Plus', 'suv'),
  ('KARSAN', 'Atak', 'other'),
  ('KARSAN', 'Jest', 'other'),
  ('KIA', 'Carens', 'citadine'),
  ('KIA', 'Carnival', 'citadine'),
  ('KIA', 'Ceed', 'citadine'),
  ('KIA', 'Cerato', 'citadine'),
  ('KIA', 'EV3', 'suv'),
  ('KIA', 'EV4', 'citadine'),
  ('KIA', 'EV6', 'suv'),
  ('KIA', 'EV9', 'suv'),
  ('KIA', 'K2500', 'utilitaire'),
  ('KIA', 'K2700', 'utilitaire'),
  ('KIA', 'Magentis', 'citadine'),
  ('KIA', 'Niro', 'suv'),
  ('KIA', 'Opirus', 'citadine'),
  ('KIA', 'Optima', 'citadine'),
  ('KIA', 'Pegas', 'citadine'),
  ('KIA', 'Picanto', 'citadine'),
  ('KIA', 'PV5', 'utilitaire'),
  ('KIA', 'Rio', 'citadine'),
  ('KIA', 'Seltos', 'suv'),
  ('KIA', 'Sonet', 'suv'),
  ('KIA', 'Sorento', 'suv'),
  ('KIA', 'Soul', 'suv'),
  ('KIA', 'Sportage', 'suv'),
  ('KIA', 'Stinger', 'citadine'),
  ('KIA', 'Stonic', 'suv'),
  ('KIA', 'Venga', 'citadine'),
  ('KIA', 'XCeed', 'suv'),
  ('KING LONG', 'XMQ6127', 'other'),
  ('KING LONG', 'XMQ6900', 'other'),
  ('LADA', 'Granta', 'citadine'),
  ('LADA', 'Kalina', 'citadine'),
  ('LADA', 'Niva', 'suv'),
  ('LADA', 'Priora', 'citadine'),
  ('LAMBORGHINI', 'Aventador', 'citadine'),
  ('LAMBORGHINI', 'Gallardo', 'citadine'),
  ('LAMBORGHINI', 'Huracán', 'citadine'),
  ('LAMBORGHINI', 'Murciélago', 'citadine'),
  ('LAMBORGHINI', 'Revuelto', 'citadine'),
  ('LAMBORGHINI', 'Temerario', 'citadine'),
  ('LAMBORGHINI', 'Urus', 'suv'),
  ('LANCIA', 'Delta', 'citadine'),
  ('LANCIA', 'Musa', 'citadine'),
  ('LANCIA', 'Phedra', 'citadine'),
  ('LANCIA', 'Thema', 'citadine'),
  ('LANCIA', 'Thesis', 'citadine'),
  ('LANCIA', 'Voyager', 'citadine'),
  ('LANCIA', 'Ypsilon', 'citadine'),
  ('LAND ROVER', 'Defender', 'suv'),
  ('LAND ROVER', 'Discovery', 'suv'),
  ('LAND ROVER', 'Discovery Sport', 'suv'),
  ('LAND ROVER', 'Freelander', 'suv'),
  ('LAND ROVER', 'Range Rover', 'suv'),
  ('LAND ROVER', 'Range Rover Evoque', 'suv'),
  ('LAND ROVER', 'Range Rover Sport', 'suv'),
  ('LAND ROVER', 'Range Rover Velar', 'suv'),
  ('LEAPMOTOR', 'B05', 'citadine'),
  ('LEAPMOTOR', 'B10', 'suv'),
  ('LEAPMOTOR', 'C10', 'suv'),
  ('LEAPMOTOR', 'T03', 'citadine'),
  ('LEXUS', 'CT', 'citadine'),
  ('LEXUS', 'ES', 'citadine'),
  ('LEXUS', 'GS', 'citadine'),
  ('LEXUS', 'IS', 'citadine'),
  ('LEXUS', 'LBX', 'suv'),
  ('LEXUS', 'LC', 'citadine'),
  ('LEXUS', 'LM', 'citadine'),
  ('LEXUS', 'LS', 'citadine'),
  ('LEXUS', 'NX', 'suv'),
  ('LEXUS', 'RC', 'citadine'),
  ('LEXUS', 'RX', 'suv'),
  ('LEXUS', 'RZ', 'suv'),
  ('LEXUS', 'UX', 'suv'),
  ('LIGIER', 'JS50', 'citadine'),
  ('LIGIER', 'Myli', 'citadine'),
  ('LOTUS', 'Eletre', 'suv'),
  ('LOTUS', 'Elise', 'citadine'),
  ('LOTUS', 'Emeya', 'citadine'),
  ('LOTUS', 'Emira', 'citadine'),
  ('LOTUS', 'Evora', 'citadine'),
  ('LOTUS', 'Exige', 'citadine'),
  ('LYNK & CO', '01', 'suv'),
  ('LYNK & CO', '08', 'suv'),
  ('MAHINDRA', 'KUV100', 'suv'),
  ('MAHINDRA', 'Pik-Up', 'utilitaire'),
  ('MAHINDRA', 'Scorpio', 'suv'),
  ('MAHINDRA', 'XUV 3XO', 'suv'),
  ('MAHINDRA', 'XUV300', 'suv'),
  ('MAHINDRA', 'XUV500', 'suv'),
  ('MAN', 'Lion''s City', 'other'),
  ('MAN', 'Lion''s Coach', 'other'),
  ('MAN', 'Lion''s Intercity', 'other'),
  ('MAN', 'TGA', 'camion'),
  ('MAN', 'TGE', 'utilitaire'),
  ('MAN', 'TGL', 'camion'),
  ('MAN', 'TGM', 'camion'),
  ('MAN', 'TGS', 'camion'),
  ('MAN', 'TGX', 'camion'),
  ('MASERATI', 'Ghibli', 'citadine'),
  ('MASERATI', 'GranTurismo', 'citadine'),
  ('MASERATI', 'Grecale', 'suv'),
  ('MASERATI', 'Levante', 'suv'),
  ('MASERATI', 'MC20', 'citadine'),
  ('MASERATI', 'Quattroporte', 'citadine'),
  ('MAZDA', 'BT-50', 'utilitaire'),
  ('MAZDA', 'CX-3', 'suv'),
  ('MAZDA', 'CX-5', 'suv'),
  ('MAZDA', 'CX-7', 'suv'),
  ('MAZDA', 'CX-30', 'suv'),
  ('MAZDA', 'CX-60', 'suv'),
  ('MAZDA', 'CX-80', 'suv'),
  ('MAZDA', 'Mazda2', 'citadine'),
  ('MAZDA', 'Mazda3', 'citadine'),
  ('MAZDA', 'Mazda5', 'citadine'),
  ('MAZDA', 'Mazda6', 'citadine'),
  ('MAZDA', 'Mazda6e', 'citadine'),
  ('MAZDA', 'MX-5', 'citadine'),
  ('MAZDA', 'MX-30', 'suv'),
  ('MAZDA', 'RX-8', 'citadine'),
  ('MAZDA', 'Tribute', 'suv'),
  ('MCLAREN', '12C', 'citadine'),
  ('MCLAREN', '570S', 'citadine'),
  ('MCLAREN', '650S', 'citadine'),
  ('MCLAREN', '720S', 'citadine'),
  ('MCLAREN', '750S', 'citadine'),
  ('MCLAREN', 'Artura', 'citadine'),
  ('MCLAREN', 'GT', 'citadine'),
  ('MERCEDES-BENZ', 'Actros', 'camion'),
  ('MERCEDES-BENZ', 'AMG GT', 'citadine'),
  ('MERCEDES-BENZ', 'Antos', 'camion'),
  ('MERCEDES-BENZ', 'Arocs', 'camion'),
  ('MERCEDES-BENZ', 'Atego', 'camion'),
  ('MERCEDES-BENZ', 'Axor', 'camion'),
  ('MERCEDES-BENZ', 'Citan', 'utilitaire'),
  ('MERCEDES-BENZ', 'Citaro', 'other'),
  ('MERCEDES-BENZ', 'CL', 'citadine'),
  ('MERCEDES-BENZ', 'CLA', 'citadine'),
  ('MERCEDES-BENZ', 'Classe A', 'citadine'),
  ('MERCEDES-BENZ', 'Classe B', 'citadine'),
  ('MERCEDES-BENZ', 'Classe C', 'citadine'),
  ('MERCEDES-BENZ', 'Classe E', 'citadine'),
  ('MERCEDES-BENZ', 'Classe G', 'suv'),
  ('MERCEDES-BENZ', 'Classe M', 'suv'),
  ('MERCEDES-BENZ', 'Classe R', 'citadine'),
  ('MERCEDES-BENZ', 'Classe S', 'citadine'),
  ('MERCEDES-BENZ', 'Classe T', 'citadine'),
  ('MERCEDES-BENZ', 'Classe V', 'utilitaire'),
  ('MERCEDES-BENZ', 'Classe X', 'utilitaire'),
  ('MERCEDES-BENZ', 'CLC', 'citadine'),
  ('MERCEDES-BENZ', 'CLE', 'citadine'),
  ('MERCEDES-BENZ', 'CLK', 'citadine'),
  ('MERCEDES-BENZ', 'CLS', 'citadine'),
  ('MERCEDES-BENZ', 'Econic', 'camion'),
  ('MERCEDES-BENZ', 'EQA', 'suv'),
  ('MERCEDES-BENZ', 'EQB', 'suv'),
  ('MERCEDES-BENZ', 'EQC', 'suv'),
  ('MERCEDES-BENZ', 'EQE', 'citadine'),
  ('MERCEDES-BENZ', 'EQS', 'citadine'),
  ('MERCEDES-BENZ', 'EQT', 'citadine'),
  ('MERCEDES-BENZ', 'EQV', 'utilitaire'),
  ('MERCEDES-BENZ', 'GL', 'suv'),
  ('MERCEDES-BENZ', 'GLA', 'suv'),
  ('MERCEDES-BENZ', 'GLB', 'suv'),
  ('MERCEDES-BENZ', 'GLC', 'suv'),
  ('MERCEDES-BENZ', 'GLE', 'suv'),
  ('MERCEDES-BENZ', 'GLK', 'suv'),
  ('MERCEDES-BENZ', 'GLS', 'suv'),
  ('MERCEDES-BENZ', 'Intouro', 'other'),
  ('MERCEDES-BENZ', 'SL', 'citadine'),
  ('MERCEDES-BENZ', 'SLC', 'citadine'),
  ('MERCEDES-BENZ', 'SLK', 'citadine'),
  ('MERCEDES-BENZ', 'Sprinter', 'utilitaire'),
  ('MERCEDES-BENZ', 'Tourino', 'other'),
  ('MERCEDES-BENZ', 'Tourismo', 'other'),
  ('MERCEDES-BENZ', 'Travego', 'other'),
  ('MERCEDES-BENZ', 'Unimog', 'camion'),
  ('MERCEDES-BENZ', 'Vario', 'camion'),
  ('MERCEDES-BENZ', 'Viano', 'utilitaire'),
  ('MERCEDES-BENZ', 'Vito', 'utilitaire'),
  ('MERCEDES-BENZ', 'Zetros', 'camion'),
  ('MG', 'Cyberster', 'citadine'),
  ('MG', 'GS', 'suv'),
  ('MG', 'GT', 'citadine'),
  ('MG', 'HS', 'suv'),
  ('MG', 'Marvel R', 'suv'),
  ('MG', 'MG3', 'citadine'),
  ('MG', 'MG4', 'citadine'),
  ('MG', 'MG5', 'citadine'),
  ('MG', 'MG7', 'citadine'),
  ('MG', 'MG350', 'citadine'),
  ('MG', 'One', 'suv'),
  ('MG', 'RX5', 'suv'),
  ('MG', 'RX9', 'suv'),
  ('MG', 'S5', 'suv'),
  ('MG', 'S6', 'suv'),
  ('MG', 'ZS', 'suv'),
  ('MINI', 'Aceman', 'suv'),
  ('MINI', 'Clubman', 'citadine'),
  ('MINI', 'Cooper', 'citadine'),
  ('MINI', 'Countryman', 'suv'),
  ('MINI', 'Paceman', 'suv'),
  ('MITSUBISHI', 'ASX', 'suv'),
  ('MITSUBISHI', 'Attrage', 'citadine'),
  ('MITSUBISHI', 'Colt', 'citadine'),
  ('MITSUBISHI', 'Eclipse Cross', 'suv'),
  ('MITSUBISHI', 'Grandis', 'citadine'),
  ('MITSUBISHI', 'i-MiEV', 'citadine'),
  ('MITSUBISHI', 'L200', 'utilitaire'),
  ('MITSUBISHI', 'L300', 'utilitaire'),
  ('MITSUBISHI', 'Lancer', 'citadine'),
  ('MITSUBISHI', 'Outlander', 'suv'),
  ('MITSUBISHI', 'Pajero', 'suv'),
  ('MITSUBISHI', 'Pajero Sport', 'suv'),
  ('MITSUBISHI', 'Space Star', 'citadine'),
  ('MITSUBISHI FUSO', 'Canter', 'camion'),
  ('MITSUBISHI FUSO', 'Fighter', 'camion'),
  ('MITSUBISHI FUSO', 'Rosa', 'other'),
  ('NEOPLAN', 'Cityliner', 'other'),
  ('NEOPLAN', 'Euroliner', 'other'),
  ('NEOPLAN', 'Jetliner', 'other'),
  ('NEOPLAN', 'Skyliner', 'other'),
  ('NEOPLAN', 'Starliner', 'other'),
  ('NEOPLAN', 'Tourliner', 'other'),
  ('NEOPLAN', 'Trendliner', 'other'),
  ('NISSAN', '350Z', 'citadine'),
  ('NISSAN', '370Z', 'citadine'),
  ('NISSAN', 'Almera', 'citadine'),
  ('NISSAN', 'Ariya', 'suv'),
  ('NISSAN', 'Atleon', 'camion'),
  ('NISSAN', 'Cabstar', 'camion'),
  ('NISSAN', 'Cube', 'citadine'),
  ('NISSAN', 'GT-R', 'citadine'),
  ('NISSAN', 'Interstar', 'utilitaire'),
  ('NISSAN', 'Juke', 'suv'),
  ('NISSAN', 'Kubistar', 'utilitaire'),
  ('NISSAN', 'Leaf', 'citadine'),
  ('NISSAN', 'Magnite', 'suv'),
  ('NISSAN', 'Micra', 'citadine'),
  ('NISSAN', 'Murano', 'suv'),
  ('NISSAN', 'Navara', 'utilitaire'),
  ('NISSAN', 'Note', 'citadine'),
  ('NISSAN', 'NP300', 'utilitaire'),
  ('NISSAN', 'NT400', 'camion'),
  ('NISSAN', 'NT500', 'camion'),
  ('NISSAN', 'NV200', 'utilitaire'),
  ('NISSAN', 'NV250', 'utilitaire'),
  ('NISSAN', 'NV300', 'utilitaire'),
  ('NISSAN', 'NV400', 'utilitaire'),
  ('NISSAN', 'Pathfinder', 'suv'),
  ('NISSAN', 'Patrol', 'suv'),
  ('NISSAN', 'Pixo', 'citadine'),
  ('NISSAN', 'Primastar', 'utilitaire'),
  ('NISSAN', 'Primera', 'citadine'),
  ('NISSAN', 'Pulsar', 'citadine'),
  ('NISSAN', 'Qashqai', 'suv'),
  ('NISSAN', 'Sunny', 'citadine'),
  ('NISSAN', 'Terrano', 'suv'),
  ('NISSAN', 'Tiida', 'citadine'),
  ('NISSAN', 'Townstar', 'utilitaire'),
  ('NISSAN', 'Urvan', 'utilitaire'),
  ('NISSAN', 'X-Trail', 'suv'),
  ('OMODA', 'C5', 'suv'),
  ('OMODA', 'C7', 'suv'),
  ('OMODA', 'C9', 'suv'),
  ('OMODA', 'E5', 'suv'),
  ('OPEL', 'Adam', 'citadine'),
  ('OPEL', 'Agila', 'citadine'),
  ('OPEL', 'Ampera', 'citadine'),
  ('OPEL', 'Antara', 'suv'),
  ('OPEL', 'Astra', 'citadine'),
  ('OPEL', 'Cascada', 'citadine'),
  ('OPEL', 'Combo', 'utilitaire'),
  ('OPEL', 'Corsa', 'citadine'),
  ('OPEL', 'Crossland', 'suv'),
  ('OPEL', 'Frontera', 'suv'),
  ('OPEL', 'Grandland', 'suv'),
  ('OPEL', 'GT', 'citadine'),
  ('OPEL', 'Insignia', 'citadine'),
  ('OPEL', 'Karl', 'citadine'),
  ('OPEL', 'Meriva', 'citadine'),
  ('OPEL', 'Mokka', 'suv'),
  ('OPEL', 'Movano', 'utilitaire'),
  ('OPEL', 'Rocks-e', 'citadine'),
  ('OPEL', 'Signum', 'citadine'),
  ('OPEL', 'Tigra', 'citadine'),
  ('OPEL', 'Vectra', 'citadine'),
  ('OPEL', 'Vivaro', 'utilitaire'),
  ('OPEL', 'Zafira', 'citadine'),
  ('OPEL', 'Zafira Life', 'utilitaire'),
  ('OTOKAR', 'Kent', 'other'),
  ('OTOKAR', 'Navigo', 'other'),
  ('OTOKAR', 'Territo', 'other'),
  ('OTOKAR', 'Vectio', 'other'),
  ('PEUGEOT', '107', 'citadine'),
  ('PEUGEOT', '108', 'citadine'),
  ('PEUGEOT', '206', 'citadine'),
  ('PEUGEOT', '207', 'citadine'),
  ('PEUGEOT', '208', 'citadine'),
  ('PEUGEOT', '301', 'citadine'),
  ('PEUGEOT', '307', 'citadine'),
  ('PEUGEOT', '308', 'citadine'),
  ('PEUGEOT', '406', 'citadine'),
  ('PEUGEOT', '407', 'citadine'),
  ('PEUGEOT', '408', 'citadine'),
  ('PEUGEOT', '508', 'citadine'),
  ('PEUGEOT', '607', 'citadine'),
  ('PEUGEOT', '807', 'citadine'),
  ('PEUGEOT', '1007', 'citadine'),
  ('PEUGEOT', '2008', 'suv'),
  ('PEUGEOT', '3008', 'suv'),
  ('PEUGEOT', '4007', 'suv'),
  ('PEUGEOT', '4008', 'suv'),
  ('PEUGEOT', '5008', 'suv'),
  ('PEUGEOT', 'Bipper', 'utilitaire'),
  ('PEUGEOT', 'Boxer', 'utilitaire'),
  ('PEUGEOT', 'Expert', 'utilitaire'),
  ('PEUGEOT', 'iOn', 'citadine'),
  ('PEUGEOT', 'Landtrek', 'utilitaire'),
  ('PEUGEOT', 'Partner', 'utilitaire'),
  ('PEUGEOT', 'Pick Up', 'utilitaire'),
  ('PEUGEOT', 'RCZ', 'citadine'),
  ('PEUGEOT', 'Rifter', 'citadine'),
  ('PEUGEOT', 'Traveller', 'utilitaire'),
  ('PIAGGIO', 'Porter', 'utilitaire'),
  ('POLESTAR', '2', 'citadine'),
  ('POLESTAR', '3', 'suv'),
  ('POLESTAR', '4', 'suv'),
  ('PORSCHE', '911', 'citadine'),
  ('PORSCHE', 'Boxster', 'citadine'),
  ('PORSCHE', 'Cayenne', 'suv'),
  ('PORSCHE', 'Cayman', 'citadine'),
  ('PORSCHE', 'Macan', 'suv'),
  ('PORSCHE', 'Panamera', 'citadine'),
  ('PORSCHE', 'Taycan', 'citadine'),
  ('PROTON', 'Persona', 'citadine'),
  ('RENAULT', '4 E-Tech', 'suv'),
  ('RENAULT', '5 E-Tech', 'citadine'),
  ('RENAULT', 'Alaskan', 'utilitaire'),
  ('RENAULT', 'Arkana', 'suv'),
  ('RENAULT', 'Austral', 'suv'),
  ('RENAULT', 'Captur', 'suv'),
  ('RENAULT', 'Clio', 'citadine'),
  ('RENAULT', 'Espace', 'citadine'),
  ('RENAULT', 'Express', 'utilitaire'),
  ('RENAULT', 'Fluence', 'citadine'),
  ('RENAULT', 'Kadjar', 'suv'),
  ('RENAULT', 'Kangoo', 'utilitaire'),
  ('RENAULT', 'Koleos', 'suv'),
  ('RENAULT', 'Laguna', 'citadine'),
  ('RENAULT', 'Latitude', 'citadine'),
  ('RENAULT', 'Master', 'utilitaire'),
  ('RENAULT', 'Mégane', 'citadine'),
  ('RENAULT', 'Modus', 'citadine'),
  ('RENAULT', 'Rafale', 'suv'),
  ('RENAULT', 'Scénic', 'citadine'),
  ('RENAULT', 'Symbioz', 'suv'),
  ('RENAULT', 'Symbol', 'citadine'),
  ('RENAULT', 'Talisman', 'citadine'),
  ('RENAULT', 'Trafic', 'utilitaire'),
  ('RENAULT', 'Twingo', 'citadine'),
  ('RENAULT', 'Twizy', 'citadine'),
  ('RENAULT', 'Vel Satis', 'citadine'),
  ('RENAULT', 'Wind', 'citadine'),
  ('RENAULT', 'Zoe', 'citadine'),
  ('RENAULT TRUCKS', 'C', 'camion'),
  ('RENAULT TRUCKS', 'D', 'camion'),
  ('RENAULT TRUCKS', 'K', 'camion'),
  ('RENAULT TRUCKS', 'Kerax', 'camion'),
  ('RENAULT TRUCKS', 'Magnum', 'camion'),
  ('RENAULT TRUCKS', 'Mascott', 'utilitaire'),
  ('RENAULT TRUCKS', 'Master', 'utilitaire'),
  ('RENAULT TRUCKS', 'Maxity', 'utilitaire'),
  ('RENAULT TRUCKS', 'Midlum', 'camion'),
  ('RENAULT TRUCKS', 'Premium', 'camion'),
  ('RENAULT TRUCKS', 'T', 'camion'),
  ('ROLLS-ROYCE', 'Cullinan', 'suv'),
  ('ROLLS-ROYCE', 'Dawn', 'citadine'),
  ('ROLLS-ROYCE', 'Ghost', 'citadine'),
  ('ROLLS-ROYCE', 'Phantom', 'citadine'),
  ('ROLLS-ROYCE', 'Spectre', 'citadine'),
  ('ROLLS-ROYCE', 'Wraith', 'citadine'),
  ('SAAB', '9-3', 'citadine'),
  ('SAAB', '9-5', 'citadine'),
  ('SCANIA', 'Citywide', 'other'),
  ('SCANIA', 'Interlink', 'other'),
  ('SCANIA', 'Série G', 'camion'),
  ('SCANIA', 'Série L', 'camion'),
  ('SCANIA', 'Série P', 'camion'),
  ('SCANIA', 'Série R', 'camion'),
  ('SCANIA', 'Série S', 'camion'),
  ('SCANIA', 'Touring', 'other'),
  ('SEAT', 'Alhambra', 'citadine'),
  ('SEAT', 'Altea', 'citadine'),
  ('SEAT', 'Arona', 'suv'),
  ('SEAT', 'Ateca', 'suv'),
  ('SEAT', 'Córdoba', 'citadine'),
  ('SEAT', 'Exeo', 'citadine'),
  ('SEAT', 'Ibiza', 'citadine'),
  ('SEAT', 'León', 'citadine'),
  ('SEAT', 'Mii', 'citadine'),
  ('SEAT', 'Tarraco', 'suv'),
  ('SEAT', 'Toledo', 'citadine'),
  ('SETRA', 'ComfortClass', 'other'),
  ('SETRA', 'MultiClass', 'other'),
  ('SETRA', 'TopClass', 'other'),
  ('SHACMAN', 'F2000', 'camion'),
  ('SHACMAN', 'F3000', 'camion'),
  ('SHACMAN', 'H3000', 'camion'),
  ('SHACMAN', 'L3000', 'camion'),
  ('SHACMAN', 'X3000', 'camion'),
  ('SINOTRUK', 'Howo', 'camion'),
  ('SKODA', 'Citigo', 'citadine'),
  ('SKODA', 'Elroq', 'suv'),
  ('SKODA', 'Enyaq', 'suv'),
  ('SKODA', 'Fabia', 'citadine'),
  ('SKODA', 'Kamiq', 'suv'),
  ('SKODA', 'Karoq', 'suv'),
  ('SKODA', 'Kodiaq', 'suv'),
  ('SKODA', 'Octavia', 'citadine'),
  ('SKODA', 'Rapid', 'citadine'),
  ('SKODA', 'Roomster', 'citadine'),
  ('SKODA', 'Scala', 'citadine'),
  ('SKODA', 'Superb', 'citadine'),
  ('SKODA', 'Yeti', 'suv'),
  ('SMART', '#1', 'suv'),
  ('SMART', '#3', 'suv'),
  ('SMART', '#5', 'suv'),
  ('SMART', 'Forfour', 'citadine'),
  ('SMART', 'Fortwo', 'citadine'),
  ('SNVI', '100 L6', 'other'),
  ('SNVI', '100 V8', 'other'),
  ('SNVI', 'B260', 'camion'),
  ('SNVI', 'C260', 'camion'),
  ('SNVI', 'K66', 'camion'),
  ('SNVI', 'K120', 'camion'),
  ('SOLARIS', 'Urbino', 'other'),
  ('SOUEAST', 'DX3', 'suv'),
  ('SOUEAST', 'DX7', 'suv'),
  ('SSANGYONG', 'Actyon', 'suv'),
  ('SSANGYONG', 'Actyon Sports', 'utilitaire'),
  ('SSANGYONG', 'Korando', 'suv'),
  ('SSANGYONG', 'Kyron', 'suv'),
  ('SSANGYONG', 'Musso', 'utilitaire'),
  ('SSANGYONG', 'Rexton', 'suv'),
  ('SSANGYONG', 'Rodius', 'citadine'),
  ('SSANGYONG', 'Tivoli', 'suv'),
  ('SSANGYONG', 'Torres', 'suv'),
  ('SSANGYONG', 'XLV', 'suv'),
  ('SUBARU', 'BRZ', 'citadine'),
  ('SUBARU', 'Crosstrek', 'suv'),
  ('SUBARU', 'Forester', 'suv'),
  ('SUBARU', 'Impreza', 'citadine'),
  ('SUBARU', 'Justy', 'citadine'),
  ('SUBARU', 'Legacy', 'citadine'),
  ('SUBARU', 'Levorg', 'citadine'),
  ('SUBARU', 'Outback', 'suv'),
  ('SUBARU', 'Solterra', 'suv'),
  ('SUBARU', 'Trezia', 'citadine'),
  ('SUBARU', 'Tribeca', 'suv'),
  ('SUBARU', 'XV', 'suv'),
  ('SUZUKI', 'Across', 'suv'),
  ('SUZUKI', 'Alto', 'citadine'),
  ('SUZUKI', 'Baleno', 'citadine'),
  ('SUZUKI', 'Carry', 'utilitaire'),
  ('SUZUKI', 'Celerio', 'citadine'),
  ('SUZUKI', 'Ciaz', 'citadine'),
  ('SUZUKI', 'Dzire', 'citadine'),
  ('SUZUKI', 'e Vitara', 'suv'),
  ('SUZUKI', 'Ertiga', 'citadine'),
  ('SUZUKI', 'Fronx', 'suv'),
  ('SUZUKI', 'Grand Vitara', 'suv'),
  ('SUZUKI', 'Ignis', 'suv'),
  ('SUZUKI', 'Jimny', 'suv'),
  ('SUZUKI', 'Kizashi', 'citadine'),
  ('SUZUKI', 'Liana', 'citadine'),
  ('SUZUKI', 'S-Cross', 'suv'),
  ('SUZUKI', 'S-Presso', 'suv'),
  ('SUZUKI', 'Splash', 'citadine'),
  ('SUZUKI', 'Swace', 'citadine'),
  ('SUZUKI', 'Swift', 'citadine'),
  ('SUZUKI', 'SX4', 'suv'),
  ('SUZUKI', 'Vitara', 'suv'),
  ('SUZUKI', 'Wagon R+', 'citadine'),
  ('TATA', 'Aria', 'suv'),
  ('TATA', 'Indica', 'citadine'),
  ('TATA', 'Indigo', 'citadine'),
  ('TATA', 'LPT', 'camion'),
  ('TATA', 'Manza', 'citadine'),
  ('TATA', 'Prima', 'camion'),
  ('TATA', 'Super Ace', 'utilitaire'),
  ('TATA', 'Vista', 'citadine'),
  ('TATA', 'Xenon', 'utilitaire'),
  ('TEMSA', 'HD', 'other'),
  ('TEMSA', 'LD', 'other'),
  ('TEMSA', 'MD9', 'other'),
  ('TEMSA', 'Opalin', 'other'),
  ('TEMSA', 'Safari', 'other'),
  ('TESLA', 'Model 3', 'citadine'),
  ('TESLA', 'Model S', 'citadine'),
  ('TESLA', 'Model X', 'suv'),
  ('TESLA', 'Model Y', 'suv'),
  ('TESLA', 'Roadster', 'citadine'),
  ('TOYOTA', 'Auris', 'citadine'),
  ('TOYOTA', 'Avanza', 'citadine'),
  ('TOYOTA', 'Avensis', 'citadine'),
  ('TOYOTA', 'Aygo', 'citadine'),
  ('TOYOTA', 'Aygo X', 'suv'),
  ('TOYOTA', 'bZ4X', 'suv'),
  ('TOYOTA', 'C-HR', 'suv'),
  ('TOYOTA', 'Camry', 'citadine'),
  ('TOYOTA', 'Coaster', 'other'),
  ('TOYOTA', 'Corolla', 'citadine'),
  ('TOYOTA', 'Corolla Cross', 'suv'),
  ('TOYOTA', 'Dyna', 'camion'),
  ('TOYOTA', 'Fortuner', 'suv'),
  ('TOYOTA', 'GR86', 'citadine'),
  ('TOYOTA', 'GT86', 'citadine'),
  ('TOYOTA', 'Hiace', 'utilitaire'),
  ('TOYOTA', 'Highlander', 'suv'),
  ('TOYOTA', 'Hilux', 'utilitaire'),
  ('TOYOTA', 'iQ', 'citadine'),
  ('TOYOTA', 'Land Cruiser', 'suv'),
  ('TOYOTA', 'Land Cruiser Prado', 'suv'),
  ('TOYOTA', 'Mirai', 'citadine'),
  ('TOYOTA', 'Previa', 'citadine'),
  ('TOYOTA', 'Prius', 'citadine'),
  ('TOYOTA', 'Proace', 'utilitaire'),
  ('TOYOTA', 'Proace City', 'utilitaire'),
  ('TOYOTA', 'Proace Max', 'utilitaire'),
  ('TOYOTA', 'RAV4', 'suv'),
  ('TOYOTA', 'Supra', 'citadine'),
  ('TOYOTA', 'Urban Cruiser', 'suv'),
  ('TOYOTA', 'Verso', 'citadine'),
  ('TOYOTA', 'Verso-S', 'citadine'),
  ('TOYOTA', 'Yaris', 'citadine'),
  ('TOYOTA', 'Yaris Cross', 'suv'),
  ('VAN HOOL', 'Acron', 'other'),
  ('VAN HOOL', 'Alicron', 'other'),
  ('VAN HOOL', 'Alizée', 'other'),
  ('VAN HOOL', 'Altano', 'other'),
  ('VAN HOOL', 'Astromega', 'other'),
  ('VAN HOOL', 'Astron', 'other'),
  ('VAN HOOL', 'Exqui.City', 'other'),
  ('VAN HOOL', 'Série EX', 'other'),
  ('VDL', 'Citea', 'other'),
  ('VDL', 'Futura', 'other'),
  ('VOLKSWAGEN', 'Amarok', 'utilitaire'),
  ('VOLKSWAGEN', 'Arteon', 'citadine'),
  ('VOLKSWAGEN', 'Bora', 'citadine'),
  ('VOLKSWAGEN', 'Caddy', 'utilitaire'),
  ('VOLKSWAGEN', 'Caravelle', 'utilitaire'),
  ('VOLKSWAGEN', 'CC', 'citadine'),
  ('VOLKSWAGEN', 'Coccinelle', 'citadine'),
  ('VOLKSWAGEN', 'Crafter', 'utilitaire'),
  ('VOLKSWAGEN', 'Eos', 'citadine'),
  ('VOLKSWAGEN', 'Fox', 'citadine'),
  ('VOLKSWAGEN', 'Golf', 'citadine'),
  ('VOLKSWAGEN', 'ID. Buzz', 'utilitaire'),
  ('VOLKSWAGEN', 'ID.3', 'citadine'),
  ('VOLKSWAGEN', 'ID.4', 'suv'),
  ('VOLKSWAGEN', 'ID.5', 'suv'),
  ('VOLKSWAGEN', 'ID.7', 'citadine'),
  ('VOLKSWAGEN', 'Jetta', 'citadine'),
  ('VOLKSWAGEN', 'LT', 'utilitaire'),
  ('VOLKSWAGEN', 'Multivan', 'utilitaire'),
  ('VOLKSWAGEN', 'New Beetle', 'citadine'),
  ('VOLKSWAGEN', 'Passat', 'citadine'),
  ('VOLKSWAGEN', 'Phaeton', 'citadine'),
  ('VOLKSWAGEN', 'Polo', 'citadine'),
  ('VOLKSWAGEN', 'Scirocco', 'citadine'),
  ('VOLKSWAGEN', 'Sharan', 'citadine'),
  ('VOLKSWAGEN', 'T-Cross', 'suv'),
  ('VOLKSWAGEN', 'T-Roc', 'suv'),
  ('VOLKSWAGEN', 'Taigo', 'suv'),
  ('VOLKSWAGEN', 'Tayron', 'suv'),
  ('VOLKSWAGEN', 'Tiguan', 'suv'),
  ('VOLKSWAGEN', 'Touareg', 'suv'),
  ('VOLKSWAGEN', 'Touran', 'citadine'),
  ('VOLKSWAGEN', 'Transporter', 'utilitaire'),
  ('VOLKSWAGEN', 'up!', 'citadine'),
  ('VOLVO', '7900', 'other'),
  ('VOLVO', '8700', 'other'),
  ('VOLVO', '8900', 'other'),
  ('VOLVO', '9700', 'other'),
  ('VOLVO', '9900', 'other'),
  ('VOLVO', 'C30', 'citadine'),
  ('VOLVO', 'C40', 'suv'),
  ('VOLVO', 'C70', 'citadine'),
  ('VOLVO', 'ES90', 'citadine'),
  ('VOLVO', 'EX30', 'suv'),
  ('VOLVO', 'EX90', 'suv'),
  ('VOLVO', 'FE', 'camion'),
  ('VOLVO', 'FH', 'camion'),
  ('VOLVO', 'FH16', 'camion'),
  ('VOLVO', 'FL', 'camion'),
  ('VOLVO', 'FM', 'camion'),
  ('VOLVO', 'FMX', 'camion'),
  ('VOLVO', 'S40', 'citadine'),
  ('VOLVO', 'S60', 'citadine'),
  ('VOLVO', 'S80', 'citadine'),
  ('VOLVO', 'S90', 'citadine'),
  ('VOLVO', 'V40', 'citadine'),
  ('VOLVO', 'V50', 'citadine'),
  ('VOLVO', 'V60', 'citadine'),
  ('VOLVO', 'V70', 'citadine'),
  ('VOLVO', 'V90', 'citadine'),
  ('VOLVO', 'XC40', 'suv'),
  ('VOLVO', 'XC60', 'suv'),
  ('VOLVO', 'XC70', 'suv'),
  ('VOLVO', 'XC90', 'suv'),
  ('WALLYSCAR', 'Iris', 'citadine'),
  ('WALLYSCAR', 'Izis', 'suv'),
  ('XPENG', 'G6', 'suv'),
  ('XPENG', 'G9', 'suv'),
  ('YUTONG', 'E10', 'other'),
  ('YUTONG', 'E12', 'other');

-- 1) Toutes les marques en majuscules (« Citroën » → « CITROËN »).
UPDATE brands SET "Name" = upper("Name") WHERE "Name" <> upper("Name");

-- 2) Marques absentes (la première orthographe du catalogue fait foi).
INSERT INTO brands ("Name", "IsActive", "CreatedAt")
SELECT DISTINCT ON (pg_temp.norm(c.marque)) c.marque, true, now()
FROM catalogue c
WHERE NOT EXISTS (SELECT 1 FROM brands b WHERE pg_temp.norm(b."Name") = pg_temp.norm(c.marque))
ORDER BY pg_temp.norm(c.marque), c.marque;

-- Modèles absents de leur marque. Une marque déjà en double en base : la plus ancienne.
INSERT INTO vehicle_models ("BrandId", "Name", "VehicleType", "IsActive", "CreatedAt")
SELECT DISTINCT ON (b."Id", pg_temp.norm(c.modele)) b."Id", c.modele, c.type, true, now()
FROM catalogue c
CROSS JOIN LATERAL (
  SELECT b."Id" FROM brands b
  WHERE pg_temp.norm(b."Name") = pg_temp.norm(c.marque)
  ORDER BY b."Id" LIMIT 1
) b
WHERE NOT EXISTS (
  SELECT 1 FROM vehicle_models m
  WHERE m."BrandId" = b."Id" AND pg_temp.norm(m."Name") = pg_temp.norm(c.modele)
)
ORDER BY b."Id", pg_temp.norm(c.modele), c.modele;

COMMIT;
