-- 053 — Catalogue des marques et modèles de la fiche véhicule (Karim, 25/09/2026).
--
-- Constat : les listes « Marque » et « Modèle » de la fiche véhicule ne proposaient
-- que 27 marques, dont 8 sans aucun modèle (BMW, Honda, MAN, Mazda, Mitsubishi,
-- Nissan, Suzuki, Volvo), et 128 modèles. Le client ne trouvait pas son véhicule ;
-- le tutoriel devait laisser passer Marque et Modèle vides. Karim : « ajoute dans
-- la liste déroulante de marque et modèle toutes les marques avec leurs modèles »
-- — voitures, utilitaires, camions et bus vendus en Tunisie, en Algérie et en
-- France, modèles des vingt dernières années environ.
--
-- Modèle : AJOUT SEUL, rejouable. Une marque est reconnue par son nom normalisé
-- (minuscules, sans accents, sans espaces ni ponctuation : « AUDI » = « Audi »,
-- « T.CROSS » = « T-Cross ») ; un modèle, par ce nom normalisé DANS SA marque. Rien
-- n'est modifié ni supprimé : les doublons et les erreurs déjà présents en base (TN :
-- 45 couples en double, « LEON » rangé chez KIA, types « van »/« hatchback » que la
-- fiche ne connaît pas) restent à traiter à part, sur décision de Karim.
-- vehicle_models."VehicleType" reprend les valeurs de la liste « Type » de la fiche
-- (citadine, suv, utilitaire, camion, other) : choisir le modèle y positionne le type.
-- 111 marques, 1147 modèles dans le catalogue ci-dessous.
--
-- Tables : brands ("Id" identité, "Name", "LogoUrl", "IsActive", "CreatedAt") et
-- vehicle_models ("Id" identité, "BrandId" → brands ON DELETE CASCADE, "Name",
-- "VehicleType", "IsActive", "CreatedAt"). Aucune colonne mappée par EF n'est
-- ajoutée : l'ordre SQL / pod API est indifférent.

BEGIN;

CREATE OR REPLACE FUNCTION pg_temp.norm(t text) RETURNS text LANGUAGE sql IMMUTABLE AS $$
  SELECT regexp_replace(
           translate(lower(coalesce(t, '')),
                     'àáâãäåçèéêëìíîïñòóôõöšùúûüýÿž',
                     'aaaaaaceeeeiiiinooooosuuuuyyz'),
           '[^a-z0-9]', '', 'g')
$$;

CREATE TEMP TABLE catalogue (marque text NOT NULL, modele text NOT NULL, type text NOT NULL) ON COMMIT DROP;

INSERT INTO catalogue (marque, modele, type) VALUES
  ('Abarth', '124 Spider', 'citadine'),
  ('Abarth', '500', 'citadine'),
  ('Abarth', '500e', 'citadine'),
  ('Abarth', '595', 'citadine'),
  ('Abarth', '600e', 'suv'),
  ('Abarth', '695', 'citadine'),
  ('Aixam', 'City', 'citadine'),
  ('Aixam', 'Coupé', 'citadine'),
  ('Aixam', 'Crossline', 'citadine'),
  ('Aixam', 'Minauto', 'citadine'),
  ('Alfa Romeo', '4C', 'citadine'),
  ('Alfa Romeo', '147', 'citadine'),
  ('Alfa Romeo', '156', 'citadine'),
  ('Alfa Romeo', '159', 'citadine'),
  ('Alfa Romeo', '166', 'citadine'),
  ('Alfa Romeo', 'Brera', 'citadine'),
  ('Alfa Romeo', 'Giulia', 'citadine'),
  ('Alfa Romeo', 'Giulietta', 'citadine'),
  ('Alfa Romeo', 'GT', 'citadine'),
  ('Alfa Romeo', 'Junior', 'suv'),
  ('Alfa Romeo', 'MiTo', 'citadine'),
  ('Alfa Romeo', 'Spider', 'citadine'),
  ('Alfa Romeo', 'Stelvio', 'suv'),
  ('Alfa Romeo', 'Tonale', 'suv'),
  ('Alpine', 'A110', 'citadine'),
  ('Alpine', 'A290', 'citadine'),
  ('Alpine', 'A390', 'suv'),
  ('Aston Martin', 'DB9', 'citadine'),
  ('Aston Martin', 'DB11', 'citadine'),
  ('Aston Martin', 'DB12', 'citadine'),
  ('Aston Martin', 'DBS', 'citadine'),
  ('Aston Martin', 'DBX', 'suv'),
  ('Aston Martin', 'Rapide', 'citadine'),
  ('Aston Martin', 'Vanquish', 'citadine'),
  ('Aston Martin', 'Vantage', 'citadine'),
  ('Audi', 'A1', 'citadine'),
  ('Audi', 'A2', 'citadine'),
  ('Audi', 'A3', 'citadine'),
  ('Audi', 'A4', 'citadine'),
  ('Audi', 'A5', 'citadine'),
  ('Audi', 'A6', 'citadine'),
  ('Audi', 'A7', 'citadine'),
  ('Audi', 'A8', 'citadine'),
  ('Audi', 'e-tron', 'suv'),
  ('Audi', 'e-tron GT', 'citadine'),
  ('Audi', 'Q2', 'suv'),
  ('Audi', 'Q3', 'suv'),
  ('Audi', 'Q4 e-tron', 'suv'),
  ('Audi', 'Q5', 'suv'),
  ('Audi', 'Q6 e-tron', 'suv'),
  ('Audi', 'Q7', 'suv'),
  ('Audi', 'Q8', 'suv'),
  ('Audi', 'R8', 'citadine'),
  ('Audi', 'TT', 'citadine'),
  ('BAIC', 'BJ40', 'suv'),
  ('BAIC', 'D20', 'citadine'),
  ('BAIC', 'U5 Plus', 'citadine'),
  ('BAIC', 'X7', 'suv'),
  ('BAIC', 'X25', 'suv'),
  ('BAIC', 'X35', 'suv'),
  ('BAIC', 'X55', 'suv'),
  ('Bentley', 'Arnage', 'citadine'),
  ('Bentley', 'Azure', 'citadine'),
  ('Bentley', 'Bentayga', 'suv'),
  ('Bentley', 'Brooklands', 'citadine'),
  ('Bentley', 'Continental GT', 'citadine'),
  ('Bentley', 'Flying Spur', 'citadine'),
  ('Bentley', 'Mulsanne', 'citadine'),
  ('BMW', 'i3', 'citadine'),
  ('BMW', 'i4', 'citadine'),
  ('BMW', 'i5', 'citadine'),
  ('BMW', 'i7', 'citadine'),
  ('BMW', 'i8', 'citadine'),
  ('BMW', 'iX', 'suv'),
  ('BMW', 'iX1', 'suv'),
  ('BMW', 'iX2', 'suv'),
  ('BMW', 'iX3', 'suv'),
  ('BMW', 'Série 1', 'citadine'),
  ('BMW', 'Série 2', 'citadine'),
  ('BMW', 'Série 3', 'citadine'),
  ('BMW', 'Série 4', 'citadine'),
  ('BMW', 'Série 5', 'citadine'),
  ('BMW', 'Série 6', 'citadine'),
  ('BMW', 'Série 7', 'citadine'),
  ('BMW', 'Série 8', 'citadine'),
  ('BMW', 'X1', 'suv'),
  ('BMW', 'X2', 'suv'),
  ('BMW', 'X3', 'suv'),
  ('BMW', 'X4', 'suv'),
  ('BMW', 'X5', 'suv'),
  ('BMW', 'X6', 'suv'),
  ('BMW', 'X7', 'suv'),
  ('BMW', 'XM', 'suv'),
  ('BMW', 'Z4', 'citadine'),
  ('Bova', 'Futura', 'other'),
  ('Bova', 'Magiq', 'other'),
  ('BYD', 'Atto 2', 'suv'),
  ('BYD', 'Atto 3', 'suv'),
  ('BYD', 'Dolphin', 'citadine'),
  ('BYD', 'Dolphin Surf', 'citadine'),
  ('BYD', 'Han', 'citadine'),
  ('BYD', 'Seal', 'citadine'),
  ('BYD', 'Seal 6', 'citadine'),
  ('BYD', 'Seal U', 'suv'),
  ('BYD', 'Sealion 5', 'suv'),
  ('BYD', 'Sealion 7', 'suv'),
  ('BYD', 'Song Plus', 'suv'),
  ('BYD', 'Tang', 'suv'),
  ('Cadillac', 'BLS', 'citadine'),
  ('Cadillac', 'CTS', 'citadine'),
  ('Cadillac', 'Escalade', 'suv'),
  ('Cadillac', 'Lyriq', 'suv'),
  ('Cadillac', 'SRX', 'suv'),
  ('Cadillac', 'STS', 'citadine'),
  ('Cadillac', 'XT4', 'suv'),
  ('Changan', 'Hunter', 'utilitaire'),
  ('Changan', 'Star Truck', 'utilitaire'),
  ('Changan', 'Star Van', 'utilitaire'),
  ('Chery', 'Arrizo 5', 'citadine'),
  ('Chery', 'Arrizo 8', 'citadine'),
  ('Chery', 'Cowin', 'citadine'),
  ('Chery', 'Fulwin', 'citadine'),
  ('Chery', 'Himla', 'utilitaire'),
  ('Chery', 'QQ', 'citadine'),
  ('Chery', 'S18', 'citadine'),
  ('Chery', 'Tiggo 1X', 'suv'),
  ('Chery', 'Tiggo 2', 'suv'),
  ('Chery', 'Tiggo 3X', 'suv'),
  ('Chery', 'Tiggo 4', 'suv'),
  ('Chery', 'Tiggo 7', 'suv'),
  ('Chery', 'Tiggo 8', 'suv'),
  ('Chery', 'Tiggo 9', 'suv'),
  ('Chevrolet', 'Aveo', 'citadine'),
  ('Chevrolet', 'Camaro', 'citadine'),
  ('Chevrolet', 'Captiva', 'suv'),
  ('Chevrolet', 'Corvette', 'citadine'),
  ('Chevrolet', 'Cruze', 'citadine'),
  ('Chevrolet', 'Epica', 'citadine'),
  ('Chevrolet', 'Evanda', 'citadine'),
  ('Chevrolet', 'Kalos', 'citadine'),
  ('Chevrolet', 'Lacetti', 'citadine'),
  ('Chevrolet', 'Malibu', 'citadine'),
  ('Chevrolet', 'Matiz', 'citadine'),
  ('Chevrolet', 'Nubira', 'citadine'),
  ('Chevrolet', 'Optra', 'citadine'),
  ('Chevrolet', 'Orlando', 'citadine'),
  ('Chevrolet', 'Rezzo', 'citadine'),
  ('Chevrolet', 'Sail', 'citadine'),
  ('Chevrolet', 'Spark', 'citadine'),
  ('Chevrolet', 'Trax', 'suv'),
  ('Chevrolet', 'Volt', 'citadine'),
  ('Chrysler', '300C', 'citadine'),
  ('Chrysler', 'Crossfire', 'citadine'),
  ('Chrysler', 'PT Cruiser', 'citadine'),
  ('Chrysler', 'Sebring', 'citadine'),
  ('Chrysler', 'Voyager', 'citadine'),
  ('Citroën', 'Ami', 'citadine'),
  ('Citroën', 'Berlingo', 'utilitaire'),
  ('Citroën', 'C-Crosser', 'suv'),
  ('Citroën', 'C-Elysée', 'citadine'),
  ('Citroën', 'C-Zero', 'citadine'),
  ('Citroën', 'C1', 'citadine'),
  ('Citroën', 'C2', 'citadine'),
  ('Citroën', 'C3', 'citadine'),
  ('Citroën', 'C3 Aircross', 'suv'),
  ('Citroën', 'C3 Picasso', 'citadine'),
  ('Citroën', 'C3 Pluriel', 'citadine'),
  ('Citroën', 'C4', 'citadine'),
  ('Citroën', 'C4 Aircross', 'suv'),
  ('Citroën', 'C4 Cactus', 'citadine'),
  ('Citroën', 'C4 Picasso', 'citadine'),
  ('Citroën', 'C4 SpaceTourer', 'citadine'),
  ('Citroën', 'C4 X', 'citadine'),
  ('Citroën', 'C5', 'citadine'),
  ('Citroën', 'C5 Aircross', 'suv'),
  ('Citroën', 'C5 X', 'citadine'),
  ('Citroën', 'C6', 'citadine'),
  ('Citroën', 'C8', 'citadine'),
  ('Citroën', 'C15', 'utilitaire'),
  ('Citroën', 'Jumper', 'utilitaire'),
  ('Citroën', 'Jumpy', 'utilitaire'),
  ('Citroën', 'Nemo', 'utilitaire'),
  ('Citroën', 'SpaceTourer', 'utilitaire'),
  ('Citroën', 'Xsara', 'citadine'),
  ('Citroën', 'Xsara Picasso', 'citadine'),
  ('Cupra', 'Ateca', 'suv'),
  ('Cupra', 'Born', 'citadine'),
  ('Cupra', 'Formentor', 'suv'),
  ('Cupra', 'Leon', 'citadine'),
  ('Cupra', 'Tavascan', 'suv'),
  ('Cupra', 'Terramar', 'suv'),
  ('Dacia', 'Bigster', 'suv'),
  ('Dacia', 'Dokker', 'utilitaire'),
  ('Dacia', 'Duster', 'suv'),
  ('Dacia', 'Jogger', 'citadine'),
  ('Dacia', 'Lodgy', 'citadine'),
  ('Dacia', 'Logan', 'citadine'),
  ('Dacia', 'Sandero', 'citadine'),
  ('Dacia', 'Spring', 'citadine'),
  ('DAF', 'CF', 'camion'),
  ('DAF', 'LF', 'camion'),
  ('DAF', 'XB', 'camion'),
  ('DAF', 'XD', 'camion'),
  ('DAF', 'XF', 'camion'),
  ('DAF', 'XG', 'camion'),
  ('Daihatsu', 'Charade', 'citadine'),
  ('Daihatsu', 'Copen', 'citadine'),
  ('Daihatsu', 'Cuore', 'citadine'),
  ('Daihatsu', 'Materia', 'citadine'),
  ('Daihatsu', 'Sirion', 'citadine'),
  ('Daihatsu', 'Terios', 'suv'),
  ('Daihatsu', 'Trevis', 'citadine'),
  ('DFSK', 'C31', 'utilitaire'),
  ('DFSK', 'C32', 'utilitaire'),
  ('DFSK', 'C35', 'utilitaire'),
  ('DFSK', 'E5', 'suv'),
  ('DFSK', 'EC75', 'utilitaire'),
  ('DFSK', 'Glory 500', 'suv'),
  ('DFSK', 'Glory 580', 'suv'),
  ('DFSK', 'Glory iX5', 'suv'),
  ('DFSK', 'K01', 'utilitaire'),
  ('DFSK', 'K02', 'utilitaire'),
  ('DFSK', 'K05', 'utilitaire'),
  ('DFSK', 'Seres 3', 'suv'),
  ('Dodge', 'Avenger', 'citadine'),
  ('Dodge', 'Caliber', 'citadine'),
  ('Dodge', 'Journey', 'suv'),
  ('Dodge', 'Nitro', 'suv'),
  ('Dongfeng', 'AX7', 'suv'),
  ('Dongfeng', 'Box', 'citadine'),
  ('Dongfeng', 'Captain', 'camion'),
  ('Dongfeng', 'Duolika', 'camion'),
  ('Dongfeng', 'Huge', 'suv'),
  ('Dongfeng', 'Rich', 'utilitaire'),
  ('Dongfeng', 'Shine', 'citadine'),
  ('Dongfeng', 'Shine GS', 'suv'),
  ('Dongfeng', 'Shine Max', 'citadine'),
  ('Dongfeng', 'Tianlong', 'camion'),
  ('DS', 'DS 3', 'citadine'),
  ('DS', 'DS 4', 'citadine'),
  ('DS', 'DS 5', 'citadine'),
  ('DS', 'DS 7', 'suv'),
  ('DS', 'DS 9', 'citadine'),
  ('DS', 'N°8', 'suv'),
  ('FAW', 'J5', 'camion'),
  ('FAW', 'J6', 'camion'),
  ('Ferrari', '12Cilindri', 'citadine'),
  ('Ferrari', '296 GTB', 'citadine'),
  ('Ferrari', '458 Italia', 'citadine'),
  ('Ferrari', '488 GTB', 'citadine'),
  ('Ferrari', '599 GTB Fiorano', 'citadine'),
  ('Ferrari', '612 Scaglietti', 'citadine'),
  ('Ferrari', '812 Superfast', 'citadine'),
  ('Ferrari', 'California', 'citadine'),
  ('Ferrari', 'F8 Tributo', 'citadine'),
  ('Ferrari', 'F12berlinetta', 'citadine'),
  ('Ferrari', 'F430', 'citadine'),
  ('Ferrari', 'FF', 'citadine'),
  ('Ferrari', 'GTC4Lusso', 'citadine'),
  ('Ferrari', 'Portofino', 'citadine'),
  ('Ferrari', 'Purosangue', 'suv'),
  ('Ferrari', 'Roma', 'citadine'),
  ('Ferrari', 'SF90 Stradale', 'citadine'),
  ('Fiat', '124 Spider', 'citadine'),
  ('Fiat', '500', 'citadine'),
  ('Fiat', '500L', 'citadine'),
  ('Fiat', '500X', 'suv'),
  ('Fiat', '600', 'suv'),
  ('Fiat', 'Albea', 'citadine'),
  ('Fiat', 'Bravo', 'citadine'),
  ('Fiat', 'Croma', 'citadine'),
  ('Fiat', 'Doblò', 'utilitaire'),
  ('Fiat', 'Ducato', 'utilitaire'),
  ('Fiat', 'Fiorino', 'utilitaire'),
  ('Fiat', 'Freemont', 'suv'),
  ('Fiat', 'Fullback', 'utilitaire'),
  ('Fiat', 'Grande Panda', 'citadine'),
  ('Fiat', 'Idea', 'citadine'),
  ('Fiat', 'Linea', 'citadine'),
  ('Fiat', 'Multipla', 'citadine'),
  ('Fiat', 'Palio', 'citadine'),
  ('Fiat', 'Panda', 'citadine'),
  ('Fiat', 'Punto', 'citadine'),
  ('Fiat', 'Qubo', 'citadine'),
  ('Fiat', 'Scudo', 'utilitaire'),
  ('Fiat', 'Sedici', 'suv'),
  ('Fiat', 'Seicento', 'citadine'),
  ('Fiat', 'Siena', 'citadine'),
  ('Fiat', 'Stilo', 'citadine'),
  ('Fiat', 'Strada', 'utilitaire'),
  ('Fiat', 'Talento', 'utilitaire'),
  ('Fiat', 'Tipo', 'citadine'),
  ('Fiat', 'Topolino', 'citadine'),
  ('Fiat', 'Ulysse', 'citadine'),
  ('Ford', 'B-Max', 'citadine'),
  ('Ford', 'Bronco', 'suv'),
  ('Ford', 'C-Max', 'citadine'),
  ('Ford', 'Capri', 'suv'),
  ('Ford', 'EcoSport', 'suv'),
  ('Ford', 'Edge', 'suv'),
  ('Ford', 'Explorer', 'suv'),
  ('Ford', 'F-Max', 'camion'),
  ('Ford', 'Fiesta', 'citadine'),
  ('Ford', 'Focus', 'citadine'),
  ('Ford', 'Fusion', 'citadine'),
  ('Ford', 'Galaxy', 'citadine'),
  ('Ford', 'Ka', 'citadine'),
  ('Ford', 'Kuga', 'suv'),
  ('Ford', 'Mondeo', 'citadine'),
  ('Ford', 'Mustang', 'citadine'),
  ('Ford', 'Mustang Mach-E', 'suv'),
  ('Ford', 'Puma', 'suv'),
  ('Ford', 'Ranger', 'utilitaire'),
  ('Ford', 'S-Max', 'citadine'),
  ('Ford', 'Tourneo Connect', 'citadine'),
  ('Ford', 'Tourneo Courier', 'citadine'),
  ('Ford', 'Tourneo Custom', 'utilitaire'),
  ('Ford', 'Transit', 'utilitaire'),
  ('Ford', 'Transit Connect', 'utilitaire'),
  ('Ford', 'Transit Courier', 'utilitaire'),
  ('Ford', 'Transit Custom', 'utilitaire'),
  ('Foton', 'Auman', 'camion'),
  ('Foton', 'Aumark', 'camion'),
  ('Foton', 'Gratour', 'utilitaire'),
  ('Foton', 'Ollin', 'camion'),
  ('Foton', 'Toano', 'utilitaire'),
  ('Foton', 'Tunland', 'utilitaire'),
  ('Foton', 'View', 'utilitaire'),
  ('Foton', 'Wonder', 'utilitaire'),
  ('Geely', 'Azkarra', 'suv'),
  ('Geely', 'Cityray', 'suv'),
  ('Geely', 'CK', 'citadine'),
  ('Geely', 'Coolray', 'suv'),
  ('Geely', 'Emgrand', 'citadine'),
  ('Geely', 'EX2', 'citadine'),
  ('Geely', 'EX5', 'suv'),
  ('Geely', 'GX3', 'suv'),
  ('Geely', 'MK', 'citadine'),
  ('Geely', 'Monjaro', 'suv'),
  ('Geely', 'Ray', 'citadine'),
  ('Geely', 'Starray', 'suv'),
  ('Geely', 'Tugella', 'suv'),
  ('Golden Dragon', 'XML6122', 'other'),
  ('Golden Dragon', 'XML6127', 'other'),
  ('Goupil', 'G3', 'utilitaire'),
  ('Goupil', 'G4', 'utilitaire'),
  ('Goupil', 'G5', 'utilitaire'),
  ('Goupil', 'G6', 'utilitaire'),
  ('Great Wall', 'Florid', 'citadine'),
  ('Great Wall', 'Hover', 'suv'),
  ('Great Wall', 'Poer', 'utilitaire'),
  ('Great Wall', 'Voleex C30', 'citadine'),
  ('Great Wall', 'Voleex C50', 'citadine'),
  ('Great Wall', 'Wingle', 'utilitaire'),
  ('Haval', 'Dargo', 'suv'),
  ('Haval', 'H2', 'suv'),
  ('Haval', 'H6', 'suv'),
  ('Haval', 'Jolion', 'suv'),
  ('Haval', 'M4', 'suv'),
  ('Heuliez Bus', 'GX 127', 'other'),
  ('Heuliez Bus', 'GX 137', 'other'),
  ('Heuliez Bus', 'GX 317', 'other'),
  ('Heuliez Bus', 'GX 327', 'other'),
  ('Heuliez Bus', 'GX 337', 'other'),
  ('Heuliez Bus', 'GX 417', 'other'),
  ('Heuliez Bus', 'GX 427', 'other'),
  ('Heuliez Bus', 'GX 437', 'other'),
  ('Higer', 'KLQ6122', 'other'),
  ('Higer', 'KLQ6129', 'other'),
  ('Hino', 'Série 300', 'camion'),
  ('Hino', 'Série 500', 'camion'),
  ('Hino', 'Série 700', 'camion'),
  ('Honda', 'Accord', 'citadine'),
  ('Honda', 'City', 'citadine'),
  ('Honda', 'Civic', 'citadine'),
  ('Honda', 'CR-V', 'suv'),
  ('Honda', 'CR-Z', 'citadine'),
  ('Honda', 'e', 'citadine'),
  ('Honda', 'e:Ny1', 'suv'),
  ('Honda', 'FR-V', 'citadine'),
  ('Honda', 'HR-V', 'suv'),
  ('Honda', 'Insight', 'citadine'),
  ('Honda', 'Jazz', 'citadine'),
  ('Honda', 'Legend', 'citadine'),
  ('Honda', 'NSX', 'citadine'),
  ('Honda', 'S2000', 'citadine'),
  ('Honda', 'Stream', 'citadine'),
  ('Honda', 'ZR-V', 'suv'),
  ('Hummer', 'H2', 'suv'),
  ('Hummer', 'H3', 'suv'),
  ('Hyundai', 'Accent', 'citadine'),
  ('Hyundai', 'Atos', 'citadine'),
  ('Hyundai', 'Bayon', 'suv'),
  ('Hyundai', 'County', 'other'),
  ('Hyundai', 'Coupé', 'citadine'),
  ('Hyundai', 'Creta', 'suv'),
  ('Hyundai', 'Elantra', 'citadine'),
  ('Hyundai', 'Getz', 'citadine'),
  ('Hyundai', 'Grand i10', 'citadine'),
  ('Hyundai', 'Grandeur', 'citadine'),
  ('Hyundai', 'H-1', 'utilitaire'),
  ('Hyundai', 'H100', 'utilitaire'),
  ('Hyundai', 'H350', 'utilitaire'),
  ('Hyundai', 'HD35', 'utilitaire'),
  ('Hyundai', 'HD65', 'camion'),
  ('Hyundai', 'HD72', 'camion'),
  ('Hyundai', 'HD78', 'camion'),
  ('Hyundai', 'i10', 'citadine'),
  ('Hyundai', 'i20', 'citadine'),
  ('Hyundai', 'i30', 'citadine'),
  ('Hyundai', 'i40', 'citadine'),
  ('Hyundai', 'Inster', 'citadine'),
  ('Hyundai', 'Ioniq', 'citadine'),
  ('Hyundai', 'Ioniq 5', 'suv'),
  ('Hyundai', 'Ioniq 6', 'citadine'),
  ('Hyundai', 'Ioniq 9', 'suv'),
  ('Hyundai', 'ix20', 'citadine'),
  ('Hyundai', 'ix35', 'suv'),
  ('Hyundai', 'ix55', 'suv'),
  ('Hyundai', 'Kona', 'suv'),
  ('Hyundai', 'Matrix', 'citadine'),
  ('Hyundai', 'Mighty', 'camion'),
  ('Hyundai', 'Nexo', 'suv'),
  ('Hyundai', 'Palisade', 'suv'),
  ('Hyundai', 'Porter', 'utilitaire'),
  ('Hyundai', 'Santa Fe', 'suv'),
  ('Hyundai', 'Sonata', 'citadine'),
  ('Hyundai', 'Staria', 'utilitaire'),
  ('Hyundai', 'Terracan', 'suv'),
  ('Hyundai', 'Trajet', 'citadine'),
  ('Hyundai', 'Tucson', 'suv'),
  ('Hyundai', 'Universe', 'other'),
  ('Hyundai', 'Veloster', 'citadine'),
  ('Hyundai', 'Venue', 'suv'),
  ('Hyundai', 'Xcient', 'camion'),
  ('Infiniti', 'EX', 'suv'),
  ('Infiniti', 'FX', 'suv'),
  ('Infiniti', 'G', 'citadine'),
  ('Infiniti', 'M', 'citadine'),
  ('Infiniti', 'Q30', 'citadine'),
  ('Infiniti', 'Q50', 'citadine'),
  ('Infiniti', 'Q60', 'citadine'),
  ('Infiniti', 'Q70', 'citadine'),
  ('Infiniti', 'QX30', 'suv'),
  ('Infiniti', 'QX50', 'suv'),
  ('Infiniti', 'QX70', 'suv'),
  ('Irisbus', 'Agora', 'other'),
  ('Irisbus', 'Ares', 'other'),
  ('Irisbus', 'Arway', 'other'),
  ('Irisbus', 'Axer', 'other'),
  ('Irisbus', 'Citelis', 'other'),
  ('Irisbus', 'Crealis', 'other'),
  ('Irisbus', 'Cristalis', 'other'),
  ('Irisbus', 'Crossway', 'other'),
  ('Irisbus', 'Evadys', 'other'),
  ('Irisbus', 'Iliade', 'other'),
  ('Irisbus', 'Magelys', 'other'),
  ('Irisbus', 'Recreo', 'other'),
  ('Irizar', 'Century', 'other'),
  ('Irizar', 'i4', 'other'),
  ('Irizar', 'i6', 'other'),
  ('Irizar', 'i8', 'other'),
  ('Irizar', 'ie tram', 'other'),
  ('Irizar', 'PB', 'other'),
  ('Isuzu', 'Citibus', 'other'),
  ('Isuzu', 'D-Max', 'utilitaire'),
  ('Isuzu', 'FSR', 'camion'),
  ('Isuzu', 'FTR', 'camion'),
  ('Isuzu', 'FVR', 'camion'),
  ('Isuzu', 'MU-X', 'suv'),
  ('Isuzu', 'NKR', 'camion'),
  ('Isuzu', 'NLR', 'camion'),
  ('Isuzu', 'NMR', 'camion'),
  ('Isuzu', 'Novo', 'other'),
  ('Isuzu', 'NPR', 'camion'),
  ('Isuzu', 'NQR', 'camion'),
  ('Isuzu', 'Turquoise', 'other'),
  ('Isuzu', 'Visigo', 'other'),
  ('Iveco', 'Crealis', 'other'),
  ('Iveco', 'Crossway', 'other'),
  ('Iveco', 'Daily', 'utilitaire'),
  ('Iveco', 'E-Way', 'other'),
  ('Iveco', 'Eurocargo', 'camion'),
  ('Iveco', 'Evadys', 'other'),
  ('Iveco', 'Magelys', 'other'),
  ('Iveco', 'S-Way', 'camion'),
  ('Iveco', 'Stralis', 'camion'),
  ('Iveco', 'T-Way', 'camion'),
  ('Iveco', 'Trakker', 'camion'),
  ('Iveco', 'Urbanway', 'other'),
  ('Iveco', 'X-Way', 'camion'),
  ('JAC', 'Gallop', 'camion'),
  ('JAC', 'J2', 'citadine'),
  ('JAC', 'J3', 'citadine'),
  ('JAC', 'J5', 'citadine'),
  ('JAC', 'J6', 'citadine'),
  ('JAC', 'J7', 'citadine'),
  ('JAC', 'JS2', 'suv'),
  ('JAC', 'JS3', 'suv'),
  ('JAC', 'JS4', 'suv'),
  ('JAC', 'JS8', 'suv'),
  ('JAC', 'Série N', 'camion'),
  ('JAC', 'T8', 'utilitaire'),
  ('Jaecoo', 'J5', 'suv'),
  ('Jaecoo', 'J7', 'suv'),
  ('Jaecoo', 'J8', 'suv'),
  ('Jaguar', 'E-Pace', 'suv'),
  ('Jaguar', 'F-Pace', 'suv'),
  ('Jaguar', 'F-Type', 'citadine'),
  ('Jaguar', 'I-Pace', 'suv'),
  ('Jaguar', 'S-Type', 'citadine'),
  ('Jaguar', 'X-Type', 'citadine'),
  ('Jaguar', 'XE', 'citadine'),
  ('Jaguar', 'XF', 'citadine'),
  ('Jaguar', 'XJ', 'citadine'),
  ('Jaguar', 'XK', 'citadine'),
  ('Jeep', 'Avenger', 'suv'),
  ('Jeep', 'Cherokee', 'suv'),
  ('Jeep', 'Commander', 'suv'),
  ('Jeep', 'Compass', 'suv'),
  ('Jeep', 'Gladiator', 'utilitaire'),
  ('Jeep', 'Grand Cherokee', 'suv'),
  ('Jeep', 'Patriot', 'suv'),
  ('Jeep', 'Renegade', 'suv'),
  ('Jeep', 'Wrangler', 'suv'),
  ('Jetour', 'Dashing', 'suv'),
  ('Jetour', 'T2', 'suv'),
  ('Jetour', 'X70', 'suv'),
  ('Jetour', 'X70 Plus', 'suv'),
  ('Jetour', 'X90 Plus', 'suv'),
  ('Karsan', 'Atak', 'other'),
  ('Karsan', 'Jest', 'other'),
  ('Kia', 'Carens', 'citadine'),
  ('Kia', 'Carnival', 'citadine'),
  ('Kia', 'Ceed', 'citadine'),
  ('Kia', 'Cerato', 'citadine'),
  ('Kia', 'EV3', 'suv'),
  ('Kia', 'EV4', 'citadine'),
  ('Kia', 'EV6', 'suv'),
  ('Kia', 'EV9', 'suv'),
  ('Kia', 'K2500', 'utilitaire'),
  ('Kia', 'K2700', 'utilitaire'),
  ('Kia', 'Magentis', 'citadine'),
  ('Kia', 'Niro', 'suv'),
  ('Kia', 'Opirus', 'citadine'),
  ('Kia', 'Optima', 'citadine'),
  ('Kia', 'Pegas', 'citadine'),
  ('Kia', 'Picanto', 'citadine'),
  ('Kia', 'PV5', 'utilitaire'),
  ('Kia', 'Rio', 'citadine'),
  ('Kia', 'Seltos', 'suv'),
  ('Kia', 'Sonet', 'suv'),
  ('Kia', 'Sorento', 'suv'),
  ('Kia', 'Soul', 'suv'),
  ('Kia', 'Sportage', 'suv'),
  ('Kia', 'Stinger', 'citadine'),
  ('Kia', 'Stonic', 'suv'),
  ('Kia', 'Venga', 'citadine'),
  ('Kia', 'XCeed', 'suv'),
  ('King Long', 'XMQ6127', 'other'),
  ('King Long', 'XMQ6900', 'other'),
  ('Lada', 'Granta', 'citadine'),
  ('Lada', 'Kalina', 'citadine'),
  ('Lada', 'Niva', 'suv'),
  ('Lada', 'Priora', 'citadine'),
  ('Lamborghini', 'Aventador', 'citadine'),
  ('Lamborghini', 'Gallardo', 'citadine'),
  ('Lamborghini', 'Huracán', 'citadine'),
  ('Lamborghini', 'Murciélago', 'citadine'),
  ('Lamborghini', 'Revuelto', 'citadine'),
  ('Lamborghini', 'Temerario', 'citadine'),
  ('Lamborghini', 'Urus', 'suv'),
  ('Lancia', 'Delta', 'citadine'),
  ('Lancia', 'Musa', 'citadine'),
  ('Lancia', 'Phedra', 'citadine'),
  ('Lancia', 'Thema', 'citadine'),
  ('Lancia', 'Thesis', 'citadine'),
  ('Lancia', 'Voyager', 'citadine'),
  ('Lancia', 'Ypsilon', 'citadine'),
  ('Land Rover', 'Defender', 'suv'),
  ('Land Rover', 'Discovery', 'suv'),
  ('Land Rover', 'Discovery Sport', 'suv'),
  ('Land Rover', 'Freelander', 'suv'),
  ('Land Rover', 'Range Rover', 'suv'),
  ('Land Rover', 'Range Rover Evoque', 'suv'),
  ('Land Rover', 'Range Rover Sport', 'suv'),
  ('Land Rover', 'Range Rover Velar', 'suv'),
  ('Leapmotor', 'B05', 'citadine'),
  ('Leapmotor', 'B10', 'suv'),
  ('Leapmotor', 'C10', 'suv'),
  ('Leapmotor', 'T03', 'citadine'),
  ('Lexus', 'CT', 'citadine'),
  ('Lexus', 'ES', 'citadine'),
  ('Lexus', 'GS', 'citadine'),
  ('Lexus', 'IS', 'citadine'),
  ('Lexus', 'LBX', 'suv'),
  ('Lexus', 'LC', 'citadine'),
  ('Lexus', 'LM', 'citadine'),
  ('Lexus', 'LS', 'citadine'),
  ('Lexus', 'NX', 'suv'),
  ('Lexus', 'RC', 'citadine'),
  ('Lexus', 'RX', 'suv'),
  ('Lexus', 'RZ', 'suv'),
  ('Lexus', 'UX', 'suv'),
  ('Ligier', 'JS50', 'citadine'),
  ('Ligier', 'Myli', 'citadine'),
  ('Lotus', 'Eletre', 'suv'),
  ('Lotus', 'Elise', 'citadine'),
  ('Lotus', 'Emeya', 'citadine'),
  ('Lotus', 'Emira', 'citadine'),
  ('Lotus', 'Evora', 'citadine'),
  ('Lotus', 'Exige', 'citadine'),
  ('Lynk & Co', '01', 'suv'),
  ('Lynk & Co', '08', 'suv'),
  ('Mahindra', 'KUV100', 'suv'),
  ('Mahindra', 'Pik-Up', 'utilitaire'),
  ('Mahindra', 'Scorpio', 'suv'),
  ('Mahindra', 'XUV 3XO', 'suv'),
  ('Mahindra', 'XUV300', 'suv'),
  ('Mahindra', 'XUV500', 'suv'),
  ('MAN', 'Lion''s City', 'other'),
  ('MAN', 'Lion''s Coach', 'other'),
  ('MAN', 'Lion''s Intercity', 'other'),
  ('MAN', 'TGA', 'camion'),
  ('MAN', 'TGE', 'utilitaire'),
  ('MAN', 'TGL', 'camion'),
  ('MAN', 'TGM', 'camion'),
  ('MAN', 'TGS', 'camion'),
  ('MAN', 'TGX', 'camion'),
  ('Maserati', 'Ghibli', 'citadine'),
  ('Maserati', 'GranTurismo', 'citadine'),
  ('Maserati', 'Grecale', 'suv'),
  ('Maserati', 'Levante', 'suv'),
  ('Maserati', 'MC20', 'citadine'),
  ('Maserati', 'Quattroporte', 'citadine'),
  ('Mazda', 'BT-50', 'utilitaire'),
  ('Mazda', 'CX-3', 'suv'),
  ('Mazda', 'CX-5', 'suv'),
  ('Mazda', 'CX-7', 'suv'),
  ('Mazda', 'CX-30', 'suv'),
  ('Mazda', 'CX-60', 'suv'),
  ('Mazda', 'CX-80', 'suv'),
  ('Mazda', 'Mazda2', 'citadine'),
  ('Mazda', 'Mazda3', 'citadine'),
  ('Mazda', 'Mazda5', 'citadine'),
  ('Mazda', 'Mazda6', 'citadine'),
  ('Mazda', 'Mazda6e', 'citadine'),
  ('Mazda', 'MX-5', 'citadine'),
  ('Mazda', 'MX-30', 'suv'),
  ('Mazda', 'RX-8', 'citadine'),
  ('Mazda', 'Tribute', 'suv'),
  ('McLaren', '12C', 'citadine'),
  ('McLaren', '570S', 'citadine'),
  ('McLaren', '650S', 'citadine'),
  ('McLaren', '720S', 'citadine'),
  ('McLaren', '750S', 'citadine'),
  ('McLaren', 'Artura', 'citadine'),
  ('McLaren', 'GT', 'citadine'),
  ('Mercedes-Benz', 'Actros', 'camion'),
  ('Mercedes-Benz', 'AMG GT', 'citadine'),
  ('Mercedes-Benz', 'Antos', 'camion'),
  ('Mercedes-Benz', 'Arocs', 'camion'),
  ('Mercedes-Benz', 'Atego', 'camion'),
  ('Mercedes-Benz', 'Axor', 'camion'),
  ('Mercedes-Benz', 'Citan', 'utilitaire'),
  ('Mercedes-Benz', 'Citaro', 'other'),
  ('Mercedes-Benz', 'CL', 'citadine'),
  ('Mercedes-Benz', 'CLA', 'citadine'),
  ('Mercedes-Benz', 'Classe A', 'citadine'),
  ('Mercedes-Benz', 'Classe B', 'citadine'),
  ('Mercedes-Benz', 'Classe C', 'citadine'),
  ('Mercedes-Benz', 'Classe E', 'citadine'),
  ('Mercedes-Benz', 'Classe G', 'suv'),
  ('Mercedes-Benz', 'Classe M', 'suv'),
  ('Mercedes-Benz', 'Classe R', 'citadine'),
  ('Mercedes-Benz', 'Classe S', 'citadine'),
  ('Mercedes-Benz', 'Classe T', 'citadine'),
  ('Mercedes-Benz', 'Classe V', 'utilitaire'),
  ('Mercedes-Benz', 'Classe X', 'utilitaire'),
  ('Mercedes-Benz', 'CLC', 'citadine'),
  ('Mercedes-Benz', 'CLE', 'citadine'),
  ('Mercedes-Benz', 'CLK', 'citadine'),
  ('Mercedes-Benz', 'CLS', 'citadine'),
  ('Mercedes-Benz', 'Econic', 'camion'),
  ('Mercedes-Benz', 'EQA', 'suv'),
  ('Mercedes-Benz', 'EQB', 'suv'),
  ('Mercedes-Benz', 'EQC', 'suv'),
  ('Mercedes-Benz', 'EQE', 'citadine'),
  ('Mercedes-Benz', 'EQS', 'citadine'),
  ('Mercedes-Benz', 'EQT', 'citadine'),
  ('Mercedes-Benz', 'EQV', 'utilitaire'),
  ('Mercedes-Benz', 'GL', 'suv'),
  ('Mercedes-Benz', 'GLA', 'suv'),
  ('Mercedes-Benz', 'GLB', 'suv'),
  ('Mercedes-Benz', 'GLC', 'suv'),
  ('Mercedes-Benz', 'GLE', 'suv'),
  ('Mercedes-Benz', 'GLK', 'suv'),
  ('Mercedes-Benz', 'GLS', 'suv'),
  ('Mercedes-Benz', 'Intouro', 'other'),
  ('Mercedes-Benz', 'SL', 'citadine'),
  ('Mercedes-Benz', 'SLC', 'citadine'),
  ('Mercedes-Benz', 'SLK', 'citadine'),
  ('Mercedes-Benz', 'Sprinter', 'utilitaire'),
  ('Mercedes-Benz', 'Tourino', 'other'),
  ('Mercedes-Benz', 'Tourismo', 'other'),
  ('Mercedes-Benz', 'Travego', 'other'),
  ('Mercedes-Benz', 'Unimog', 'camion'),
  ('Mercedes-Benz', 'Vario', 'camion'),
  ('Mercedes-Benz', 'Viano', 'utilitaire'),
  ('Mercedes-Benz', 'Vito', 'utilitaire'),
  ('Mercedes-Benz', 'Zetros', 'camion'),
  ('MG', 'Cyberster', 'citadine'),
  ('MG', 'GS', 'suv'),
  ('MG', 'GT', 'citadine'),
  ('MG', 'HS', 'suv'),
  ('MG', 'Marvel R', 'suv'),
  ('MG', 'MG3', 'citadine'),
  ('MG', 'MG4', 'citadine'),
  ('MG', 'MG5', 'citadine'),
  ('MG', 'MG7', 'citadine'),
  ('MG', 'MG350', 'citadine'),
  ('MG', 'One', 'suv'),
  ('MG', 'RX5', 'suv'),
  ('MG', 'RX9', 'suv'),
  ('MG', 'S5', 'suv'),
  ('MG', 'S6', 'suv'),
  ('MG', 'ZS', 'suv'),
  ('Mini', 'Aceman', 'suv'),
  ('Mini', 'Clubman', 'citadine'),
  ('Mini', 'Cooper', 'citadine'),
  ('Mini', 'Countryman', 'suv'),
  ('Mini', 'Paceman', 'suv'),
  ('Mitsubishi', 'ASX', 'suv'),
  ('Mitsubishi', 'Attrage', 'citadine'),
  ('Mitsubishi', 'Colt', 'citadine'),
  ('Mitsubishi', 'Eclipse Cross', 'suv'),
  ('Mitsubishi', 'Grandis', 'citadine'),
  ('Mitsubishi', 'i-MiEV', 'citadine'),
  ('Mitsubishi', 'L200', 'utilitaire'),
  ('Mitsubishi', 'L300', 'utilitaire'),
  ('Mitsubishi', 'Lancer', 'citadine'),
  ('Mitsubishi', 'Outlander', 'suv'),
  ('Mitsubishi', 'Pajero', 'suv'),
  ('Mitsubishi', 'Pajero Sport', 'suv'),
  ('Mitsubishi', 'Space Star', 'citadine'),
  ('Mitsubishi Fuso', 'Canter', 'camion'),
  ('Mitsubishi Fuso', 'Fighter', 'camion'),
  ('Mitsubishi Fuso', 'Rosa', 'other'),
  ('Neoplan', 'Cityliner', 'other'),
  ('Neoplan', 'Euroliner', 'other'),
  ('Neoplan', 'Jetliner', 'other'),
  ('Neoplan', 'Skyliner', 'other'),
  ('Neoplan', 'Starliner', 'other'),
  ('Neoplan', 'Tourliner', 'other'),
  ('Neoplan', 'Trendliner', 'other'),
  ('Nissan', '350Z', 'citadine'),
  ('Nissan', '370Z', 'citadine'),
  ('Nissan', 'Almera', 'citadine'),
  ('Nissan', 'Ariya', 'suv'),
  ('Nissan', 'Atleon', 'camion'),
  ('Nissan', 'Cabstar', 'camion'),
  ('Nissan', 'Cube', 'citadine'),
  ('Nissan', 'GT-R', 'citadine'),
  ('Nissan', 'Interstar', 'utilitaire'),
  ('Nissan', 'Juke', 'suv'),
  ('Nissan', 'Kubistar', 'utilitaire'),
  ('Nissan', 'Leaf', 'citadine'),
  ('Nissan', 'Magnite', 'suv'),
  ('Nissan', 'Micra', 'citadine'),
  ('Nissan', 'Murano', 'suv'),
  ('Nissan', 'Navara', 'utilitaire'),
  ('Nissan', 'Note', 'citadine'),
  ('Nissan', 'NP300', 'utilitaire'),
  ('Nissan', 'NT400', 'camion'),
  ('Nissan', 'NT500', 'camion'),
  ('Nissan', 'NV200', 'utilitaire'),
  ('Nissan', 'NV250', 'utilitaire'),
  ('Nissan', 'NV300', 'utilitaire'),
  ('Nissan', 'NV400', 'utilitaire'),
  ('Nissan', 'Pathfinder', 'suv'),
  ('Nissan', 'Patrol', 'suv'),
  ('Nissan', 'Pixo', 'citadine'),
  ('Nissan', 'Primastar', 'utilitaire'),
  ('Nissan', 'Primera', 'citadine'),
  ('Nissan', 'Pulsar', 'citadine'),
  ('Nissan', 'Qashqai', 'suv'),
  ('Nissan', 'Sunny', 'citadine'),
  ('Nissan', 'Terrano', 'suv'),
  ('Nissan', 'Tiida', 'citadine'),
  ('Nissan', 'Townstar', 'utilitaire'),
  ('Nissan', 'Urvan', 'utilitaire'),
  ('Nissan', 'X-Trail', 'suv'),
  ('Omoda', 'C5', 'suv'),
  ('Omoda', 'C7', 'suv'),
  ('Omoda', 'C9', 'suv'),
  ('Omoda', 'E5', 'suv'),
  ('Opel', 'Adam', 'citadine'),
  ('Opel', 'Agila', 'citadine'),
  ('Opel', 'Ampera', 'citadine'),
  ('Opel', 'Antara', 'suv'),
  ('Opel', 'Astra', 'citadine'),
  ('Opel', 'Cascada', 'citadine'),
  ('Opel', 'Combo', 'utilitaire'),
  ('Opel', 'Corsa', 'citadine'),
  ('Opel', 'Crossland', 'suv'),
  ('Opel', 'Frontera', 'suv'),
  ('Opel', 'Grandland', 'suv'),
  ('Opel', 'GT', 'citadine'),
  ('Opel', 'Insignia', 'citadine'),
  ('Opel', 'Karl', 'citadine'),
  ('Opel', 'Meriva', 'citadine'),
  ('Opel', 'Mokka', 'suv'),
  ('Opel', 'Movano', 'utilitaire'),
  ('Opel', 'Rocks-e', 'citadine'),
  ('Opel', 'Signum', 'citadine'),
  ('Opel', 'Tigra', 'citadine'),
  ('Opel', 'Vectra', 'citadine'),
  ('Opel', 'Vivaro', 'utilitaire'),
  ('Opel', 'Zafira', 'citadine'),
  ('Opel', 'Zafira Life', 'utilitaire'),
  ('Otokar', 'Kent', 'other'),
  ('Otokar', 'Navigo', 'other'),
  ('Otokar', 'Territo', 'other'),
  ('Otokar', 'Vectio', 'other'),
  ('Peugeot', '107', 'citadine'),
  ('Peugeot', '108', 'citadine'),
  ('Peugeot', '206', 'citadine'),
  ('Peugeot', '207', 'citadine'),
  ('Peugeot', '208', 'citadine'),
  ('Peugeot', '301', 'citadine'),
  ('Peugeot', '307', 'citadine'),
  ('Peugeot', '308', 'citadine'),
  ('Peugeot', '406', 'citadine'),
  ('Peugeot', '407', 'citadine'),
  ('Peugeot', '408', 'citadine'),
  ('Peugeot', '508', 'citadine'),
  ('Peugeot', '607', 'citadine'),
  ('Peugeot', '807', 'citadine'),
  ('Peugeot', '1007', 'citadine'),
  ('Peugeot', '2008', 'suv'),
  ('Peugeot', '3008', 'suv'),
  ('Peugeot', '4007', 'suv'),
  ('Peugeot', '4008', 'suv'),
  ('Peugeot', '5008', 'suv'),
  ('Peugeot', 'Bipper', 'utilitaire'),
  ('Peugeot', 'Boxer', 'utilitaire'),
  ('Peugeot', 'Expert', 'utilitaire'),
  ('Peugeot', 'iOn', 'citadine'),
  ('Peugeot', 'Landtrek', 'utilitaire'),
  ('Peugeot', 'Partner', 'utilitaire'),
  ('Peugeot', 'Pick Up', 'utilitaire'),
  ('Peugeot', 'RCZ', 'citadine'),
  ('Peugeot', 'Rifter', 'citadine'),
  ('Peugeot', 'Traveller', 'utilitaire'),
  ('Piaggio', 'Porter', 'utilitaire'),
  ('Polestar', '2', 'citadine'),
  ('Polestar', '3', 'suv'),
  ('Polestar', '4', 'suv'),
  ('Porsche', '911', 'citadine'),
  ('Porsche', 'Boxster', 'citadine'),
  ('Porsche', 'Cayenne', 'suv'),
  ('Porsche', 'Cayman', 'citadine'),
  ('Porsche', 'Macan', 'suv'),
  ('Porsche', 'Panamera', 'citadine'),
  ('Porsche', 'Taycan', 'citadine'),
  ('Proton', 'Persona', 'citadine'),
  ('Renault', '4 E-Tech', 'suv'),
  ('Renault', '5 E-Tech', 'citadine'),
  ('Renault', 'Alaskan', 'utilitaire'),
  ('Renault', 'Arkana', 'suv'),
  ('Renault', 'Austral', 'suv'),
  ('Renault', 'Captur', 'suv'),
  ('Renault', 'Clio', 'citadine'),
  ('Renault', 'Espace', 'citadine'),
  ('Renault', 'Express', 'utilitaire'),
  ('Renault', 'Fluence', 'citadine'),
  ('Renault', 'Kadjar', 'suv'),
  ('Renault', 'Kangoo', 'utilitaire'),
  ('Renault', 'Koleos', 'suv'),
  ('Renault', 'Laguna', 'citadine'),
  ('Renault', 'Latitude', 'citadine'),
  ('Renault', 'Master', 'utilitaire'),
  ('Renault', 'Mégane', 'citadine'),
  ('Renault', 'Modus', 'citadine'),
  ('Renault', 'Rafale', 'suv'),
  ('Renault', 'Scénic', 'citadine'),
  ('Renault', 'Symbioz', 'suv'),
  ('Renault', 'Symbol', 'citadine'),
  ('Renault', 'Talisman', 'citadine'),
  ('Renault', 'Trafic', 'utilitaire'),
  ('Renault', 'Twingo', 'citadine'),
  ('Renault', 'Twizy', 'citadine'),
  ('Renault', 'Vel Satis', 'citadine'),
  ('Renault', 'Wind', 'citadine'),
  ('Renault', 'Zoe', 'citadine'),
  ('Renault Trucks', 'C', 'camion'),
  ('Renault Trucks', 'D', 'camion'),
  ('Renault Trucks', 'K', 'camion'),
  ('Renault Trucks', 'Kerax', 'camion'),
  ('Renault Trucks', 'Magnum', 'camion'),
  ('Renault Trucks', 'Mascott', 'utilitaire'),
  ('Renault Trucks', 'Master', 'utilitaire'),
  ('Renault Trucks', 'Maxity', 'utilitaire'),
  ('Renault Trucks', 'Midlum', 'camion'),
  ('Renault Trucks', 'Premium', 'camion'),
  ('Renault Trucks', 'T', 'camion'),
  ('Rolls-Royce', 'Cullinan', 'suv'),
  ('Rolls-Royce', 'Dawn', 'citadine'),
  ('Rolls-Royce', 'Ghost', 'citadine'),
  ('Rolls-Royce', 'Phantom', 'citadine'),
  ('Rolls-Royce', 'Spectre', 'citadine'),
  ('Rolls-Royce', 'Wraith', 'citadine'),
  ('Saab', '9-3', 'citadine'),
  ('Saab', '9-5', 'citadine'),
  ('Scania', 'Citywide', 'other'),
  ('Scania', 'Interlink', 'other'),
  ('Scania', 'Série G', 'camion'),
  ('Scania', 'Série L', 'camion'),
  ('Scania', 'Série P', 'camion'),
  ('Scania', 'Série R', 'camion'),
  ('Scania', 'Série S', 'camion'),
  ('Scania', 'Touring', 'other'),
  ('Seat', 'Alhambra', 'citadine'),
  ('Seat', 'Altea', 'citadine'),
  ('Seat', 'Arona', 'suv'),
  ('Seat', 'Ateca', 'suv'),
  ('Seat', 'Córdoba', 'citadine'),
  ('Seat', 'Exeo', 'citadine'),
  ('Seat', 'Ibiza', 'citadine'),
  ('Seat', 'León', 'citadine'),
  ('Seat', 'Mii', 'citadine'),
  ('Seat', 'Tarraco', 'suv'),
  ('Seat', 'Toledo', 'citadine'),
  ('Setra', 'ComfortClass', 'other'),
  ('Setra', 'MultiClass', 'other'),
  ('Setra', 'TopClass', 'other'),
  ('Shacman', 'F2000', 'camion'),
  ('Shacman', 'F3000', 'camion'),
  ('Shacman', 'H3000', 'camion'),
  ('Shacman', 'L3000', 'camion'),
  ('Shacman', 'X3000', 'camion'),
  ('Sinotruk', 'Howo', 'camion'),
  ('Skoda', 'Citigo', 'citadine'),
  ('Skoda', 'Elroq', 'suv'),
  ('Skoda', 'Enyaq', 'suv'),
  ('Skoda', 'Fabia', 'citadine'),
  ('Skoda', 'Kamiq', 'suv'),
  ('Skoda', 'Karoq', 'suv'),
  ('Skoda', 'Kodiaq', 'suv'),
  ('Skoda', 'Octavia', 'citadine'),
  ('Skoda', 'Rapid', 'citadine'),
  ('Skoda', 'Roomster', 'citadine'),
  ('Skoda', 'Scala', 'citadine'),
  ('Skoda', 'Superb', 'citadine'),
  ('Skoda', 'Yeti', 'suv'),
  ('Smart', '#1', 'suv'),
  ('Smart', '#3', 'suv'),
  ('Smart', '#5', 'suv'),
  ('Smart', 'Forfour', 'citadine'),
  ('Smart', 'Fortwo', 'citadine'),
  ('SNVI', '100 L6', 'other'),
  ('SNVI', '100 V8', 'other'),
  ('SNVI', 'B260', 'camion'),
  ('SNVI', 'C260', 'camion'),
  ('SNVI', 'K66', 'camion'),
  ('SNVI', 'K120', 'camion'),
  ('Solaris', 'Urbino', 'other'),
  ('Soueast', 'DX3', 'suv'),
  ('Soueast', 'DX7', 'suv'),
  ('SsangYong', 'Actyon', 'suv'),
  ('SsangYong', 'Actyon Sports', 'utilitaire'),
  ('SsangYong', 'Korando', 'suv'),
  ('SsangYong', 'Kyron', 'suv'),
  ('SsangYong', 'Musso', 'utilitaire'),
  ('SsangYong', 'Rexton', 'suv'),
  ('SsangYong', 'Rodius', 'citadine'),
  ('SsangYong', 'Tivoli', 'suv'),
  ('SsangYong', 'Torres', 'suv'),
  ('SsangYong', 'XLV', 'suv'),
  ('Subaru', 'BRZ', 'citadine'),
  ('Subaru', 'Crosstrek', 'suv'),
  ('Subaru', 'Forester', 'suv'),
  ('Subaru', 'Impreza', 'citadine'),
  ('Subaru', 'Justy', 'citadine'),
  ('Subaru', 'Legacy', 'citadine'),
  ('Subaru', 'Levorg', 'citadine'),
  ('Subaru', 'Outback', 'suv'),
  ('Subaru', 'Solterra', 'suv'),
  ('Subaru', 'Trezia', 'citadine'),
  ('Subaru', 'Tribeca', 'suv'),
  ('Subaru', 'XV', 'suv'),
  ('Suzuki', 'Across', 'suv'),
  ('Suzuki', 'Alto', 'citadine'),
  ('Suzuki', 'Baleno', 'citadine'),
  ('Suzuki', 'Carry', 'utilitaire'),
  ('Suzuki', 'Celerio', 'citadine'),
  ('Suzuki', 'Ciaz', 'citadine'),
  ('Suzuki', 'Dzire', 'citadine'),
  ('Suzuki', 'e Vitara', 'suv'),
  ('Suzuki', 'Ertiga', 'citadine'),
  ('Suzuki', 'Fronx', 'suv'),
  ('Suzuki', 'Grand Vitara', 'suv'),
  ('Suzuki', 'Ignis', 'suv'),
  ('Suzuki', 'Jimny', 'suv'),
  ('Suzuki', 'Kizashi', 'citadine'),
  ('Suzuki', 'Liana', 'citadine'),
  ('Suzuki', 'S-Cross', 'suv'),
  ('Suzuki', 'S-Presso', 'suv'),
  ('Suzuki', 'Splash', 'citadine'),
  ('Suzuki', 'Swace', 'citadine'),
  ('Suzuki', 'Swift', 'citadine'),
  ('Suzuki', 'SX4', 'suv'),
  ('Suzuki', 'Vitara', 'suv'),
  ('Suzuki', 'Wagon R+', 'citadine'),
  ('Tata', 'Aria', 'suv'),
  ('Tata', 'Indica', 'citadine'),
  ('Tata', 'Indigo', 'citadine'),
  ('Tata', 'LPT', 'camion'),
  ('Tata', 'Manza', 'citadine'),
  ('Tata', 'Prima', 'camion'),
  ('Tata', 'Super Ace', 'utilitaire'),
  ('Tata', 'Vista', 'citadine'),
  ('Tata', 'Xenon', 'utilitaire'),
  ('Temsa', 'HD', 'other'),
  ('Temsa', 'LD', 'other'),
  ('Temsa', 'MD9', 'other'),
  ('Temsa', 'Opalin', 'other'),
  ('Temsa', 'Safari', 'other'),
  ('Tesla', 'Model 3', 'citadine'),
  ('Tesla', 'Model S', 'citadine'),
  ('Tesla', 'Model X', 'suv'),
  ('Tesla', 'Model Y', 'suv'),
  ('Tesla', 'Roadster', 'citadine'),
  ('Toyota', 'Auris', 'citadine'),
  ('Toyota', 'Avanza', 'citadine'),
  ('Toyota', 'Avensis', 'citadine'),
  ('Toyota', 'Aygo', 'citadine'),
  ('Toyota', 'Aygo X', 'suv'),
  ('Toyota', 'bZ4X', 'suv'),
  ('Toyota', 'C-HR', 'suv'),
  ('Toyota', 'Camry', 'citadine'),
  ('Toyota', 'Coaster', 'other'),
  ('Toyota', 'Corolla', 'citadine'),
  ('Toyota', 'Corolla Cross', 'suv'),
  ('Toyota', 'Dyna', 'camion'),
  ('Toyota', 'Fortuner', 'suv'),
  ('Toyota', 'GR86', 'citadine'),
  ('Toyota', 'GT86', 'citadine'),
  ('Toyota', 'Hiace', 'utilitaire'),
  ('Toyota', 'Highlander', 'suv'),
  ('Toyota', 'Hilux', 'utilitaire'),
  ('Toyota', 'iQ', 'citadine'),
  ('Toyota', 'Land Cruiser', 'suv'),
  ('Toyota', 'Land Cruiser Prado', 'suv'),
  ('Toyota', 'Mirai', 'citadine'),
  ('Toyota', 'Previa', 'citadine'),
  ('Toyota', 'Prius', 'citadine'),
  ('Toyota', 'Proace', 'utilitaire'),
  ('Toyota', 'Proace City', 'utilitaire'),
  ('Toyota', 'Proace Max', 'utilitaire'),
  ('Toyota', 'RAV4', 'suv'),
  ('Toyota', 'Supra', 'citadine'),
  ('Toyota', 'Urban Cruiser', 'suv'),
  ('Toyota', 'Verso', 'citadine'),
  ('Toyota', 'Verso-S', 'citadine'),
  ('Toyota', 'Yaris', 'citadine'),
  ('Toyota', 'Yaris Cross', 'suv'),
  ('Van Hool', 'Acron', 'other'),
  ('Van Hool', 'Alicron', 'other'),
  ('Van Hool', 'Alizée', 'other'),
  ('Van Hool', 'Altano', 'other'),
  ('Van Hool', 'Astromega', 'other'),
  ('Van Hool', 'Astron', 'other'),
  ('Van Hool', 'Exqui.City', 'other'),
  ('Van Hool', 'Série EX', 'other'),
  ('VDL', 'Citea', 'other'),
  ('VDL', 'Futura', 'other'),
  ('Volkswagen', 'Amarok', 'utilitaire'),
  ('Volkswagen', 'Arteon', 'citadine'),
  ('Volkswagen', 'Bora', 'citadine'),
  ('Volkswagen', 'Caddy', 'utilitaire'),
  ('Volkswagen', 'Caravelle', 'utilitaire'),
  ('Volkswagen', 'CC', 'citadine'),
  ('Volkswagen', 'Coccinelle', 'citadine'),
  ('Volkswagen', 'Crafter', 'utilitaire'),
  ('Volkswagen', 'Eos', 'citadine'),
  ('Volkswagen', 'Fox', 'citadine'),
  ('Volkswagen', 'Golf', 'citadine'),
  ('Volkswagen', 'ID. Buzz', 'utilitaire'),
  ('Volkswagen', 'ID.3', 'citadine'),
  ('Volkswagen', 'ID.4', 'suv'),
  ('Volkswagen', 'ID.5', 'suv'),
  ('Volkswagen', 'ID.7', 'citadine'),
  ('Volkswagen', 'Jetta', 'citadine'),
  ('Volkswagen', 'LT', 'utilitaire'),
  ('Volkswagen', 'Multivan', 'utilitaire'),
  ('Volkswagen', 'New Beetle', 'citadine'),
  ('Volkswagen', 'Passat', 'citadine'),
  ('Volkswagen', 'Phaeton', 'citadine'),
  ('Volkswagen', 'Polo', 'citadine'),
  ('Volkswagen', 'Scirocco', 'citadine'),
  ('Volkswagen', 'Sharan', 'citadine'),
  ('Volkswagen', 'T-Cross', 'suv'),
  ('Volkswagen', 'T-Roc', 'suv'),
  ('Volkswagen', 'Taigo', 'suv'),
  ('Volkswagen', 'Tayron', 'suv'),
  ('Volkswagen', 'Tiguan', 'suv'),
  ('Volkswagen', 'Touareg', 'suv'),
  ('Volkswagen', 'Touran', 'citadine'),
  ('Volkswagen', 'Transporter', 'utilitaire'),
  ('Volkswagen', 'up!', 'citadine'),
  ('Volvo', '7900', 'other'),
  ('Volvo', '8700', 'other'),
  ('Volvo', '8900', 'other'),
  ('Volvo', '9700', 'other'),
  ('Volvo', '9900', 'other'),
  ('Volvo', 'C30', 'citadine'),
  ('Volvo', 'C40', 'suv'),
  ('Volvo', 'C70', 'citadine'),
  ('Volvo', 'ES90', 'citadine'),
  ('Volvo', 'EX30', 'suv'),
  ('Volvo', 'EX90', 'suv'),
  ('Volvo', 'FE', 'camion'),
  ('Volvo', 'FH', 'camion'),
  ('Volvo', 'FH16', 'camion'),
  ('Volvo', 'FL', 'camion'),
  ('Volvo', 'FM', 'camion'),
  ('Volvo', 'FMX', 'camion'),
  ('Volvo', 'S40', 'citadine'),
  ('Volvo', 'S60', 'citadine'),
  ('Volvo', 'S80', 'citadine'),
  ('Volvo', 'S90', 'citadine'),
  ('Volvo', 'V40', 'citadine'),
  ('Volvo', 'V50', 'citadine'),
  ('Volvo', 'V60', 'citadine'),
  ('Volvo', 'V70', 'citadine'),
  ('Volvo', 'V90', 'citadine'),
  ('Volvo', 'XC40', 'suv'),
  ('Volvo', 'XC60', 'suv'),
  ('Volvo', 'XC70', 'suv'),
  ('Volvo', 'XC90', 'suv'),
  ('Wallyscar', 'Iris', 'citadine'),
  ('Wallyscar', 'Izis', 'suv'),
  ('Xpeng', 'G6', 'suv'),
  ('Xpeng', 'G9', 'suv'),
  ('Yutong', 'E10', 'other'),
  ('Yutong', 'E12', 'other');

-- Marques absentes (la première orthographe du catalogue fait foi).
INSERT INTO brands ("Name", "IsActive", "CreatedAt")
SELECT DISTINCT ON (pg_temp.norm(c.marque)) c.marque, true, now()
FROM catalogue c
WHERE NOT EXISTS (SELECT 1 FROM brands b WHERE pg_temp.norm(b."Name") = pg_temp.norm(c.marque))
ORDER BY pg_temp.norm(c.marque), c.marque;

-- Modèles absents de leur marque. Une marque déjà en double en base : la plus ancienne.
INSERT INTO vehicle_models ("BrandId", "Name", "VehicleType", "IsActive", "CreatedAt")
SELECT DISTINCT ON (b."Id", pg_temp.norm(c.modele)) b."Id", c.modele, c.type, true, now()
FROM catalogue c
CROSS JOIN LATERAL (
  SELECT b."Id" FROM brands b
  WHERE pg_temp.norm(b."Name") = pg_temp.norm(c.marque)
  ORDER BY b."Id" LIMIT 1
) b
WHERE NOT EXISTS (
  SELECT 1 FROM vehicle_models m
  WHERE m."BrandId" = b."Id" AND pg_temp.norm(m."Name") = pg_temp.norm(c.modele)
)
ORDER BY b."Id", pg_temp.norm(c.modele), c.modele;

COMMIT;
