CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE TABLE subscriptions (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        type character varying(50) NOT NULL,
        price numeric(10,2) NOT NULL,
        features text[] NOT NULL,
        gps_tracking boolean NOT NULL,
        gps_installation boolean NOT NULL,
        max_vehicles integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_subscriptions" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE TABLE user_settings (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        language character varying(10) NOT NULL,
        timezone character varying(50) NOT NULL,
        currency character varying(10) NOT NULL,
        date_format character varying(20) NOT NULL,
        distance_unit character varying(10) NOT NULL,
        speed_unit character varying(10) NOT NULL,
        volume_unit character varying(10) NOT NULL,
        temperature_unit character varying(5) NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        display jsonb,
        notifications jsonb,
        CONSTRAINT "PK_user_settings" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE TABLE companies (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(200) NOT NULL,
        type character varying(50) NOT NULL,
        address character varying(200),
        city character varying(100),
        country character varying(10) NOT NULL,
        phone character varying(20),
        email character varying(100),
        subscription_id integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        settings jsonb,
        CONSTRAINT "PK_companies" PRIMARY KEY (id),
        CONSTRAINT "FK_companies_subscriptions_subscription_id" FOREIGN KEY (subscription_id) REFERENCES subscriptions (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE TABLE employees (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        email character varying(150),
        phone character varying(20),
        role character varying(50) NOT NULL,
        status character varying(20) NOT NULL,
        hire_date timestamp with time zone,
        license_number character varying(100),
        license_expiry timestamp with time zone,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        company_id integer NOT NULL,
        CONSTRAINT "PK_employees" PRIMARY KEY (id),
        CONSTRAINT "FK_employees_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE TABLE geofences (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        description character varying(500),
        type character varying(20) NOT NULL,
        color character varying(20) NOT NULL,
        coordinates jsonb,
        center_lat double precision,
        center_lng double precision,
        radius double precision,
        alert_on_entry boolean NOT NULL,
        alert_on_exit boolean NOT NULL,
        alert_speed_limit integer,
        is_active boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        company_id integer NOT NULL,
        CONSTRAINT "PK_geofences" PRIMARY KEY (id),
        CONSTRAINT "FK_geofences_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE TABLE gps_devices (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        device_uid character varying(50) NOT NULL,
        label character varying(100),
        sim_number character varying(20),
        sim_operator character varying(50),
        model character varying(50),
        brand character varying(50),
        protocol_type character varying(50),
        firmware_version character varying(50),
        installation_date timestamp with time zone,
        status character varying(20) NOT NULL,
        last_communication timestamp with time zone,
        battery_level integer,
        signal_strength integer,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        company_id integer NOT NULL,
        CONSTRAINT "PK_gps_devices" PRIMARY KEY (id),
        CONSTRAINT "FK_gps_devices_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE TABLE users (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        email character varying(150) NOT NULL,
        phone character varying(20),
        password_hash text NOT NULL,
        roles text[] NOT NULL,
        permissions text[] NOT NULL,
        assigned_vehicle_ids integer[] NOT NULL,
        status character varying(20) NOT NULL,
        last_login_at timestamp with time zone,
        user_settings_id integer,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        company_id integer NOT NULL,
        CONSTRAINT "PK_users" PRIMARY KEY (id),
        CONSTRAINT "FK_users_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
        CONSTRAINT "FK_users_user_settings_user_settings_id" FOREIGN KEY (user_settings_id) REFERENCES user_settings (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE TABLE gps_positions (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        device_id integer NOT NULL,
        recorded_at timestamp with time zone NOT NULL,
        latitude double precision NOT NULL,
        longitude double precision NOT NULL,
        speed_kph double precision,
        course_deg double precision,
        altitude_m double precision,
        ignition_on boolean,
        fuel_raw integer,
        power_voltage integer,
        satellites integer,
        is_valid boolean NOT NULL,
        is_real_time boolean NOT NULL,
        address character varying(500),
        metadata jsonb,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_gps_positions" PRIMARY KEY (id),
        CONSTRAINT "FK_gps_positions_gps_devices_device_id" FOREIGN KEY (device_id) REFERENCES gps_devices (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE TABLE vehicles (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        type character varying(50) NOT NULL,
        brand character varying(50),
        model character varying(50),
        plate_number character varying(20),
        year integer,
        color character varying(30),
        status character varying(20) NOT NULL,
        has_gps boolean NOT NULL,
        mileage integer NOT NULL,
        rental_mileage integer,
        assigned_driver_id integer,
        assigned_supervisor_id integer,
        gps_device_id integer,
        driver_name text,
        driver_phone text,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        company_id integer NOT NULL,
        CONSTRAINT "PK_vehicles" PRIMARY KEY (id),
        CONSTRAINT "FK_vehicles_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
        CONSTRAINT "FK_vehicles_employees_assigned_driver_id" FOREIGN KEY (assigned_driver_id) REFERENCES employees (id) ON DELETE SET NULL,
        CONSTRAINT "FK_vehicles_employees_assigned_supervisor_id" FOREIGN KEY (assigned_supervisor_id) REFERENCES employees (id) ON DELETE SET NULL,
        CONSTRAINT "FK_vehicles_gps_devices_gps_device_id" FOREIGN KEY (gps_device_id) REFERENCES gps_devices (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE TABLE geofence_events (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        geofence_id integer NOT NULL,
        vehicle_id integer NOT NULL,
        type character varying(30) NOT NULL,
        latitude double precision NOT NULL,
        longitude double precision NOT NULL,
        speed double precision,
        timestamp timestamp with time zone NOT NULL,
        CONSTRAINT "PK_geofence_events" PRIMARY KEY (id),
        CONSTRAINT "FK_geofence_events_geofences_geofence_id" FOREIGN KEY (geofence_id) REFERENCES geofences (id) ON DELETE CASCADE,
        CONSTRAINT "FK_geofence_events_vehicles_vehicle_id" FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE TABLE geofence_vehicles (
        geofence_id integer NOT NULL,
        vehicle_id integer NOT NULL,
        assigned_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_geofence_vehicles" PRIMARY KEY (geofence_id, vehicle_id),
        CONSTRAINT "FK_geofence_vehicles_geofences_geofence_id" FOREIGN KEY (geofence_id) REFERENCES geofences (id) ON DELETE CASCADE,
        CONSTRAINT "FK_geofence_vehicles_vehicles_vehicle_id" FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE TABLE gps_alerts (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        device_id integer,
        vehicle_id integer,
        type character varying(50) NOT NULL,
        severity character varying(50) NOT NULL,
        message character varying(500) NOT NULL,
        resolved boolean NOT NULL,
        resolved_at timestamp with time zone,
        resolved_by_user_id integer,
        latitude double precision,
        longitude double precision,
        timestamp timestamp with time zone NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_gps_alerts" PRIMARY KEY (id),
        CONSTRAINT "FK_gps_alerts_gps_devices_device_id" FOREIGN KEY (device_id) REFERENCES gps_devices (id),
        CONSTRAINT "FK_gps_alerts_users_resolved_by_user_id" FOREIGN KEY (resolved_by_user_id) REFERENCES users (id),
        CONSTRAINT "FK_gps_alerts_vehicles_vehicle_id" FOREIGN KEY (vehicle_id) REFERENCES vehicles (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE TABLE maintenance_records (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        vehicle_id integer NOT NULL,
        type character varying(50) NOT NULL,
        description character varying(500) NOT NULL,
        mileage_at_service integer NOT NULL,
        date timestamp with time zone NOT NULL,
        next_service_date timestamp with time zone,
        next_service_mileage integer,
        status character varying(30) NOT NULL,
        labor_cost numeric(10,2) NOT NULL,
        parts_cost numeric(10,2) NOT NULL,
        total_cost numeric(10,2) NOT NULL,
        service_provider character varying(200),
        provider_contact character varying(100),
        invoice_number character varying(100),
        invoice_url character varying(500),
        notes character varying(1000),
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        company_id integer NOT NULL,
        CONSTRAINT "PK_maintenance_records" PRIMARY KEY (id),
        CONSTRAINT "FK_maintenance_records_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
        CONSTRAINT "FK_maintenance_records_vehicles_vehicle_id" FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE TABLE vehicle_costs (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        vehicle_id integer NOT NULL,
        type character varying(50) NOT NULL,
        description character varying(500),
        amount numeric(10,2) NOT NULL,
        date timestamp with time zone NOT NULL,
        mileage integer,
        receipt_number character varying(100),
        receipt_url character varying(500),
        fuel_type character varying(20),
        liters numeric(10,2),
        price_per_liter numeric(10,2),
        created_by_user_id integer,
        created_at timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        company_id integer NOT NULL,
        CONSTRAINT "PK_vehicle_costs" PRIMARY KEY (id),
        CONSTRAINT "FK_vehicle_costs_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
        CONSTRAINT "FK_vehicle_costs_users_created_by_user_id" FOREIGN KEY (created_by_user_id) REFERENCES users (id),
        CONSTRAINT "FK_vehicle_costs_vehicles_vehicle_id" FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE TABLE vehicle_documents (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        vehicle_id integer NOT NULL,
        type character varying(50) NOT NULL,
        name character varying(200) NOT NULL,
        expiry_date timestamp with time zone,
        file_url character varying(500),
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_vehicle_documents" PRIMARY KEY (id),
        CONSTRAINT "FK_vehicle_documents_vehicles_vehicle_id" FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE TABLE maintenance_parts (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        maintenance_record_id integer NOT NULL,
        name character varying(200) NOT NULL,
        part_number character varying(100),
        quantity integer NOT NULL,
        unit_cost numeric(10,2) NOT NULL,
        total_cost numeric(10,2) NOT NULL,
        CONSTRAINT "PK_maintenance_parts" PRIMARY KEY (id),
        CONSTRAINT "FK_maintenance_parts_maintenance_records_maintenance_record_id" FOREIGN KEY (maintenance_record_id) REFERENCES maintenance_records (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_companies_subscription_id" ON companies (subscription_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_employees_company_id" ON employees (company_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_geofence_events_geofence_id" ON geofence_events (geofence_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_geofence_events_vehicle_id" ON geofence_events (vehicle_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_geofence_vehicles_vehicle_id" ON geofence_vehicles (vehicle_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_geofences_company_id" ON geofences (company_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_gps_alerts_device_id" ON gps_alerts (device_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_gps_alerts_resolved_by_user_id" ON gps_alerts (resolved_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_gps_alerts_timestamp" ON gps_alerts (timestamp DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_gps_alerts_vehicle_id" ON gps_alerts (vehicle_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_gps_devices_company_id" ON gps_devices (company_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE UNIQUE INDEX "IX_gps_devices_device_uid" ON gps_devices (device_uid);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_gps_positions_device_id" ON gps_positions (device_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_gps_positions_recorded_at" ON gps_positions (recorded_at DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_maintenance_parts_maintenance_record_id" ON maintenance_parts (maintenance_record_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_maintenance_records_company_id" ON maintenance_records (company_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_maintenance_records_vehicle_id" ON maintenance_records (vehicle_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_users_company_id" ON users (company_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE UNIQUE INDEX "IX_users_email" ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE UNIQUE INDEX "IX_users_user_settings_id" ON users (user_settings_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_vehicle_costs_company_id" ON vehicle_costs (company_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_vehicle_costs_created_by_user_id" ON vehicle_costs (created_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_vehicle_costs_vehicle_id" ON vehicle_costs (vehicle_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_vehicle_documents_vehicle_id" ON vehicle_documents (vehicle_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX idx_vehicles_plate_number ON vehicles (plate_number);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_vehicles_assigned_driver_id" ON vehicles (assigned_driver_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_vehicles_assigned_supervisor_id" ON vehicles (assigned_supervisor_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE INDEX "IX_vehicles_company_id" ON vehicles (company_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    CREATE UNIQUE INDEX "IX_vehicles_gps_device_id" ON vehicles (gps_device_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251224145939_InitialCqrsArchitecture') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251224145939_InitialCqrsArchitecture', '9.0.1');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    ALTER TABLE subscriptions ADD "BillingCycle" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    ALTER TABLE subscriptions ADD "IsActive" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    ALTER TABLE subscriptions ADD "MaxGeofences" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    ALTER TABLE subscriptions ADD "MaxGpsDevices" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    ALTER TABLE subscriptions ADD "MaxUsers" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    ALTER TABLE companies ADD "IF" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    ALTER TABLE companies ADD "IsActive" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    ALTER TABLE companies ADD "LogoUrl" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    ALTER TABLE companies ADD "RC" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    ALTER TABLE companies ADD "SubscriptionExpiresAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    ALTER TABLE companies ADD "TaxId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE audit_logs (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer,
        "CompanyId" integer,
        "Action" text NOT NULL,
        "EntityType" text NOT NULL,
        "EntityId" integer,
        "EntityName" text,
        "OldValues" jsonb,
        "NewValues" jsonb,
        "IpAddress" text,
        "UserAgent" text,
        "Description" text,
        "Timestamp" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_audit_logs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_audit_logs_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (id),
        CONSTRAINT "FK_audit_logs_users_UserId" FOREIGN KEY ("UserId") REFERENCES users (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE contracts (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "VehicleId" integer NOT NULL,
        "ContractNumber" text NOT NULL,
        "Type" text NOT NULL,
        "Provider" text,
        "ProviderContact" text,
        "ProviderPhone" text,
        "ProviderEmail" text,
        "StartDate" timestamp with time zone NOT NULL,
        "EndDate" timestamp with time zone NOT NULL,
        "TotalValue" numeric(12,2) NOT NULL,
        "MonthlyPayment" numeric(10,2),
        "PaymentFrequency" text NOT NULL,
        "AllowedKmPerYear" integer,
        "ExcessKmRate" numeric(6,2),
        "ResidualValue" numeric(12,2),
        "PolicyNumber" text,
        "CoverageType" text,
        "Deductible" numeric(10,2),
        "Status" text NOT NULL,
        "DocumentUrl" text,
        "Notes" text,
        "ReminderDaysBefore" integer,
        "ReminderSent" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CompanyId" integer NOT NULL,
        CONSTRAINT "PK_contracts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_contracts_vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES vehicles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE daily_statistics (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "VehicleId" integer NOT NULL,
        "Date" date NOT NULL,
        "DistanceKm" numeric(10,2) NOT NULL,
        "DrivingTimeMinutes" integer NOT NULL,
        "IdleTimeMinutes" integer NOT NULL,
        "StoppedTimeMinutes" integer NOT NULL,
        "TripCount" integer NOT NULL,
        "AverageSpeedKph" numeric(6,2),
        "MaxSpeedKph" numeric(6,2),
        "OverspeedingEvents" integer NOT NULL,
        "OverspeedingMinutes" integer NOT NULL,
        "FuelConsumedLiters" numeric(10,2),
        "FuelEfficiencyKmPerLiter" numeric(6,2),
        "FuelCost" numeric(10,2),
        "HarshBrakingCount" integer NOT NULL,
        "HarshAccelerationCount" integer NOT NULL,
        "SharpTurnCount" integer NOT NULL,
        "StartMileage" integer NOT NULL,
        "EndMileage" integer NOT NULL,
        "EngineOnTimeMinutes" integer,
        "EngineOffTimeMinutes" integer,
        "AlertCount" integer NOT NULL,
        "GeofenceEventsCount" integer NOT NULL,
        "DriverScore" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CompanyId" integer NOT NULL,
        CONSTRAINT "PK_daily_statistics" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_daily_statistics_vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES vehicles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE driver_assignments (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "VehicleId" integer NOT NULL,
        "DriverId" integer NOT NULL,
        "AssignedByUserId" integer,
        "StartDate" timestamp with time zone NOT NULL,
        "EndDate" timestamp with time zone,
        "Status" text NOT NULL,
        "AssignmentType" text NOT NULL,
        "Notes" text,
        "StartMileage" integer,
        "EndMileage" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CompanyId" integer NOT NULL,
        CONSTRAINT "PK_driver_assignments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_driver_assignments_employees_DriverId" FOREIGN KEY ("DriverId") REFERENCES employees (id) ON DELETE CASCADE,
        CONSTRAINT "FK_driver_assignments_users_AssignedByUserId" FOREIGN KEY ("AssignedByUserId") REFERENCES users (id),
        CONSTRAINT "FK_driver_assignments_vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES vehicles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE driver_scores (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DriverId" integer NOT NULL,
        "Date" date NOT NULL,
        "OverallScore" integer NOT NULL,
        "SpeedingScore" integer NOT NULL,
        "BrakingScore" integer NOT NULL,
        "AccelerationScore" integer NOT NULL,
        "IdlingScore" integer NOT NULL,
        "FuelEfficiencyScore" integer NOT NULL,
        "SpeedingEvents" integer NOT NULL,
        "HarshBrakingEvents" integer NOT NULL,
        "HarshAccelerationEvents" integer NOT NULL,
        "IdlingEvents" integer NOT NULL,
        "DistanceKm" numeric(10,2) NOT NULL,
        "DrivingTimeMinutes" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CompanyId" integer NOT NULL,
        CONSTRAINT "PK_driver_scores" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_driver_scores_employees_DriverId" FOREIGN KEY ("DriverId") REFERENCES employees (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE notifications (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Type" text NOT NULL,
        "Title" text NOT NULL,
        "Message" text NOT NULL,
        "Priority" text NOT NULL,
        "Channel" text NOT NULL,
        "IsRead" boolean NOT NULL,
        "ReadAt" timestamp with time zone,
        "IsSent" boolean NOT NULL,
        "SentAt" timestamp with time zone,
        "ReferenceType" text,
        "ReferenceId" integer,
        "ActionUrl" text,
        "Metadata" jsonb,
        "ExpiresAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CompanyId" integer NOT NULL,
        CONSTRAINT "PK_notifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_notifications_users_UserId" FOREIGN KEY ("UserId") REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE points_of_interest (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text,
        "Category" text NOT NULL,
        "SubCategory" text,
        "Latitude" double precision NOT NULL,
        "Longitude" double precision NOT NULL,
        "Address" text,
        "City" text,
        "Phone" text,
        "Email" text,
        "Website" text,
        "Hours" jsonb,
        "Color" text NOT NULL,
        "Icon" text,
        "IsActive" boolean NOT NULL,
        "FuelBrand" text,
        "HasDiesel" boolean,
        "HasGasoline" boolean,
        "HasElectricCharging" boolean,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CompanyId" integer NOT NULL,
        CONSTRAINT "PK_points_of_interest" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_points_of_interest_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE refresh_tokens (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Token" text NOT NULL,
        "UserId" integer NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "RevokedAt" timestamp with time zone,
        "RevokedByIp" text,
        "CreatedByIp" text,
        "ReplacedByToken" text,
        "DeviceInfo" text,
        CONSTRAINT "PK_refresh_tokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_refresh_tokens_users_UserId" FOREIGN KEY ("UserId") REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE report_schedules (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CreatedByUserId" integer NOT NULL,
        "Name" text NOT NULL,
        "ReportType" text NOT NULL,
        "Frequency" text NOT NULL,
        "DayOfWeek" integer,
        "DayOfMonth" integer,
        "TimeOfDay" text NOT NULL,
        "EmailRecipients" text[] NOT NULL,
        "VehicleIds" integer[],
        "DriverIds" integer[],
        "Format" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "LastRunAt" timestamp with time zone,
        "NextRunAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CompanyId" integer NOT NULL,
        CONSTRAINT "PK_report_schedules" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_report_schedules_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (id) ON DELETE CASCADE,
        CONSTRAINT "FK_report_schedules_users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE reports (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CreatedByUserId" integer,
        "Name" text NOT NULL,
        "Type" text NOT NULL,
        "Description" text,
        "StartDate" timestamp with time zone,
        "EndDate" timestamp with time zone,
        "VehicleIds" integer[],
        "DriverIds" integer[],
        "Format" text NOT NULL,
        "Status" text NOT NULL,
        "FileUrl" text,
        "FileSizeBytes" bigint,
        "ErrorMessage" text,
        "GeneratedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CompanyId" integer NOT NULL,
        CONSTRAINT "PK_reports" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_reports_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (id) ON DELETE CASCADE,
        CONSTRAINT "FK_reports_users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES users (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE reservations (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "VehicleId" integer NOT NULL,
        "RequestedByUserId" integer,
        "AssignedDriverId" integer,
        "Purpose" text,
        "Destination" text,
        "StartDateTime" timestamp with time zone NOT NULL,
        "EndDateTime" timestamp with time zone NOT NULL,
        "EstimatedKm" integer,
        "ActualKm" integer,
        "StartMileage" integer,
        "EndMileage" integer,
        "Status" text NOT NULL,
        "ApprovedByUserId" integer,
        "ApprovedAt" timestamp with time zone,
        "RejectionReason" text,
        "Notes" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CompanyId" integer NOT NULL,
        CONSTRAINT "PK_reservations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_reservations_employees_AssignedDriverId" FOREIGN KEY ("AssignedDriverId") REFERENCES employees (id),
        CONSTRAINT "FK_reservations_users_ApprovedByUserId" FOREIGN KEY ("ApprovedByUserId") REFERENCES users (id),
        CONSTRAINT "FK_reservations_users_RequestedByUserId" FOREIGN KEY ("RequestedByUserId") REFERENCES users (id),
        CONSTRAINT "FK_reservations_vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES vehicles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE suppliers (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Type" text NOT NULL,
        "Address" text,
        "City" text,
        "ContactName" text,
        "Phone" text,
        "Email" text,
        "Website" text,
        "TaxId" text,
        "BankAccount" text,
        "PaymentTerms" text NOT NULL,
        "DiscountPercent" numeric(5,2),
        "Rating" integer,
        "Notes" text,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CompanyId" integer NOT NULL,
        CONSTRAINT "PK_suppliers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_suppliers_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE trips (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "VehicleId" integer NOT NULL,
        "DriverId" integer,
        "StartTime" timestamp with time zone NOT NULL,
        "StartLatitude" double precision NOT NULL,
        "StartLongitude" double precision NOT NULL,
        "StartAddress" text,
        "StartMileage" integer NOT NULL,
        "EndTime" timestamp with time zone,
        "EndLatitude" double precision,
        "EndLongitude" double precision,
        "EndAddress" text,
        "EndMileage" integer,
        "DistanceKm" numeric(10,2) NOT NULL,
        "DurationMinutes" integer NOT NULL,
        "FuelConsumedLiters" numeric(10,2),
        "AverageSpeedKph" numeric(6,2),
        "MaxSpeedKph" numeric(6,2),
        "IdleTimeMinutes" integer,
        "HarshBrakingCount" integer,
        "HarshAccelerationCount" integer,
        "OverspeedingCount" integer,
        "Status" text NOT NULL,
        "Notes" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CompanyId" integer NOT NULL,
        CONSTRAINT "PK_trips" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_trips_employees_DriverId" FOREIGN KEY ("DriverId") REFERENCES employees (id),
        CONSTRAINT "FK_trips_vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES vehicles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE user_vehicles (
        "UserId" integer NOT NULL,
        "VehicleId" integer NOT NULL,
        "AccessLevel" text NOT NULL,
        "AssignedAt" timestamp with time zone NOT NULL,
        "AssignedByUserId" integer,
        CONSTRAINT "PK_user_vehicles" PRIMARY KEY ("UserId", "VehicleId"),
        CONSTRAINT "FK_user_vehicles_users_AssignedByUserId" FOREIGN KEY ("AssignedByUserId") REFERENCES users (id),
        CONSTRAINT "FK_user_vehicles_users_UserId" FOREIGN KEY ("UserId") REFERENCES users (id) ON DELETE CASCADE,
        CONSTRAINT "FK_user_vehicles_vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES vehicles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE part_inventory (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SupplierId" integer,
        "PartNumber" text NOT NULL,
        "Name" text NOT NULL,
        "Description" text,
        "Category" text NOT NULL,
        "Brand" text,
        "Unit" text,
        "QuantityInStock" integer NOT NULL,
        "MinimumStock" integer NOT NULL,
        "ReorderQuantity" integer,
        "UnitCost" numeric(10,2) NOT NULL,
        "SellingPrice" numeric(10,2),
        "Location" text,
        "CompatibleVehicles" text[],
        "LastRestockDate" timestamp with time zone,
        "ExpiryDate" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CompanyId" integer NOT NULL,
        CONSTRAINT "PK_part_inventory" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_part_inventory_suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES suppliers ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE driving_events (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "VehicleId" integer NOT NULL,
        "DriverId" integer,
        "TripId" bigint,
        "Type" text NOT NULL,
        "Severity" text NOT NULL,
        "Latitude" double precision NOT NULL,
        "Longitude" double precision NOT NULL,
        "Address" text,
        "Timestamp" timestamp with time zone NOT NULL,
        "SpeedKph" double precision,
        "SpeedLimitKph" double precision,
        "GForce" double precision,
        "DurationSeconds" integer,
        "Metadata" jsonb,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CompanyId" integer NOT NULL,
        CONSTRAINT "PK_driving_events" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_driving_events_employees_DriverId" FOREIGN KEY ("DriverId") REFERENCES employees (id),
        CONSTRAINT "FK_driving_events_trips_TripId" FOREIGN KEY ("TripId") REFERENCES trips ("Id"),
        CONSTRAINT "FK_driving_events_vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES vehicles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE trip_waypoints (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TripId" bigint NOT NULL,
        "SequenceNumber" integer NOT NULL,
        "Latitude" double precision NOT NULL,
        "Longitude" double precision NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL,
        "SpeedKph" double precision,
        "Heading" double precision,
        "Address" text,
        "EventType" text,
        CONSTRAINT "PK_trip_waypoints" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_trip_waypoints_trips_TripId" FOREIGN KEY ("TripId") REFERENCES trips ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE TABLE part_transactions (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PartId" integer NOT NULL,
        "Type" text NOT NULL,
        "Quantity" integer NOT NULL,
        "QuantityBefore" integer NOT NULL,
        "QuantityAfter" integer NOT NULL,
        "UnitCost" numeric(10,2),
        "TotalCost" numeric(10,2),
        "MaintenanceRecordId" integer,
        "VehicleId" integer,
        "SupplierId" integer,
        "ReferenceNumber" text,
        "Notes" text,
        "CreatedByUserId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CompanyId" integer NOT NULL,
        CONSTRAINT "PK_part_transactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_part_transactions_maintenance_records_MaintenanceRecordId" FOREIGN KEY ("MaintenanceRecordId") REFERENCES maintenance_records (id),
        CONSTRAINT "FK_part_transactions_part_inventory_PartId" FOREIGN KEY ("PartId") REFERENCES part_inventory ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_part_transactions_suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES suppliers ("Id"),
        CONSTRAINT "FK_part_transactions_users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES users (id),
        CONSTRAINT "FK_part_transactions_vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES vehicles (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_audit_logs_CompanyId" ON audit_logs ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_audit_logs_UserId" ON audit_logs ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_contracts_VehicleId" ON contracts ("VehicleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE UNIQUE INDEX "IX_daily_statistics_VehicleId_Date" ON daily_statistics ("VehicleId", "Date");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_driver_assignments_AssignedByUserId" ON driver_assignments ("AssignedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_driver_assignments_DriverId" ON driver_assignments ("DriverId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_driver_assignments_VehicleId" ON driver_assignments ("VehicleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE UNIQUE INDEX "IX_driver_scores_DriverId_Date" ON driver_scores ("DriverId", "Date");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_driving_events_DriverId" ON driving_events ("DriverId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_driving_events_TripId" ON driving_events ("TripId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_driving_events_VehicleId" ON driving_events ("VehicleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_notifications_UserId" ON notifications ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_part_inventory_SupplierId" ON part_inventory ("SupplierId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_part_transactions_CreatedByUserId" ON part_transactions ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_part_transactions_MaintenanceRecordId" ON part_transactions ("MaintenanceRecordId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_part_transactions_PartId" ON part_transactions ("PartId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_part_transactions_SupplierId" ON part_transactions ("SupplierId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_part_transactions_VehicleId" ON part_transactions ("VehicleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_points_of_interest_CompanyId" ON points_of_interest ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_refresh_tokens_UserId" ON refresh_tokens ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_report_schedules_CompanyId" ON report_schedules ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_report_schedules_CreatedByUserId" ON report_schedules ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_reports_CompanyId" ON reports ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_reports_CreatedByUserId" ON reports ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_reservations_ApprovedByUserId" ON reservations ("ApprovedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_reservations_AssignedDriverId" ON reservations ("AssignedDriverId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_reservations_RequestedByUserId" ON reservations ("RequestedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_reservations_VehicleId" ON reservations ("VehicleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_suppliers_CompanyId" ON suppliers ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_trip_waypoints_TripId" ON trip_waypoints ("TripId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_trips_DriverId" ON trips ("DriverId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_trips_VehicleId" ON trips ("VehicleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_user_vehicles_AssignedByUserId" ON user_vehicles ("AssignedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    CREATE INDEX "IX_user_vehicles_VehicleId" ON user_vehicles ("VehicleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226123142_CompleteSchemaExpansion') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251226123142_CompleteSchemaExpansion', '9.0.1');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226131641_AddMatToGpsDevice') THEN
    ALTER TABLE gps_devices ADD "Mat" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226131641_AddMatToGpsDevice') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251226131641_AddMatToGpsDevice', '9.0.1');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    ALTER INDEX "IX_gps_positions_recorded_at" RENAME TO ix_gps_positions_time;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    ALTER TABLE gps_positions ADD "FuelRateLPer100Km" numeric(6,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    ALTER TABLE gps_positions ADD "MemsX" smallint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    ALTER TABLE gps_positions ADD "MemsY" smallint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    ALTER TABLE gps_positions ADD "MemsZ" smallint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    ALTER TABLE gps_positions ADD "OdometerKm" bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    ALTER TABLE gps_positions ADD "ProtocolVersion" smallint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    ALTER TABLE gps_positions ADD "Rpm" smallint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    ALTER TABLE gps_positions ADD "SendFlag" smallint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    ALTER TABLE gps_positions ADD "TemperatureC" smallint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    CREATE TABLE fuel_records (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "VehicleId" integer NOT NULL,
        "DriverId" integer,
        "DeviceId" integer,
        "RecordedAt" timestamp with time zone NOT NULL,
        "FuelPercent" smallint NOT NULL,
        "FuelLiters" numeric(10,2),
        "TankCapacityLiters" numeric(10,2),
        "ConsumptionRateLPer100Km" numeric(6,2),
        "AverageConsumptionLPer100Km" numeric(6,2),
        "OdometerKm" bigint,
        "SpeedKph" double precision,
        "Rpm" smallint,
        "IgnitionOn" boolean,
        "Latitude" double precision NOT NULL,
        "Longitude" double precision NOT NULL,
        "EventType" text NOT NULL,
        "FuelChange" smallint,
        "RefuelAmount" numeric(10,2),
        "RefuelCost" numeric(10,2),
        "RefuelStation" text,
        "IsAnomaly" boolean NOT NULL,
        "AnomalyReason" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CompanyId" integer NOT NULL,
        CONSTRAINT "PK_fuel_records" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_fuel_records_employees_DriverId" FOREIGN KEY ("DriverId") REFERENCES employees (id),
        CONSTRAINT "FK_fuel_records_gps_devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES gps_devices (id),
        CONSTRAINT "FK_fuel_records_vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES vehicles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    CREATE TABLE vehicle_stops (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "VehicleId" integer NOT NULL,
        "DriverId" integer,
        "DeviceId" integer,
        "StartTime" timestamp with time zone NOT NULL,
        "EndTime" timestamp with time zone,
        "DurationSeconds" integer NOT NULL,
        "Latitude" double precision NOT NULL,
        "Longitude" double precision NOT NULL,
        "Address" text,
        "StopType" text NOT NULL,
        "IgnitionOff" boolean NOT NULL,
        "IsAuthorized" boolean NOT NULL,
        "StartMileage" integer,
        "EndMileage" integer,
        "FuelLevelStart" integer,
        "FuelLevelEnd" integer,
        "GeofenceId" integer,
        "InsideGeofence" boolean NOT NULL,
        "Notes" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CompanyId" integer NOT NULL,
        CONSTRAINT "PK_vehicle_stops" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_vehicle_stops_employees_DriverId" FOREIGN KEY ("DriverId") REFERENCES employees (id),
        CONSTRAINT "FK_vehicle_stops_geofences_GeofenceId" FOREIGN KEY ("GeofenceId") REFERENCES geofences (id),
        CONSTRAINT "FK_vehicle_stops_gps_devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES gps_devices (id),
        CONSTRAINT "FK_vehicle_stops_vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES vehicles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    CREATE INDEX ix_gps_positions_device_time ON gps_positions (device_id, recorded_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    CREATE INDEX "IX_fuel_records_DeviceId" ON fuel_records ("DeviceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    CREATE INDEX "IX_fuel_records_DriverId" ON fuel_records ("DriverId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    CREATE INDEX ix_fuel_records_vehicle_time ON fuel_records ("VehicleId", "RecordedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    CREATE INDEX "IX_vehicle_stops_DeviceId" ON vehicle_stops ("DeviceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    CREATE INDEX "IX_vehicle_stops_DriverId" ON vehicle_stops ("DriverId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    CREATE INDEX "IX_vehicle_stops_GeofenceId" ON vehicle_stops ("GeofenceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    CREATE INDEX ix_vehicle_stops_vehicle_time ON vehicle_stops ("VehicleId", "StartTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229144324_AddAAPSupport_VehicleStops_FuelRecords') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251229144324_AddAAPSupport_VehicleStops_FuelRecords', '9.0.1');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229155041_AddGpsPositionsPartitioning') THEN

                    CREATE OR REPLACE FUNCTION create_gps_positions_partition(partition_date DATE)
                    RETURNS void AS $$
                    DECLARE
                        partition_name TEXT;
                        start_date DATE;
                        end_date DATE;
                    BEGIN
                        start_date := date_trunc('month', partition_date);
                        end_date := start_date + INTERVAL '1 month';
                        partition_name := 'gps_positions_' || to_char(start_date, 'YYYY_MM');
                        
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_class c
                            JOIN pg_namespace n ON n.oid = c.relnamespace
                            WHERE c.relname = partition_name AND n.nspname = 'public'
                        ) THEN
                            EXECUTE format(
                                'CREATE TABLE IF NOT EXISTS %I PARTITION OF gps_positions
                                 FOR VALUES FROM (%L) TO (%L)',
                                partition_name, start_date, end_date
                            );
                            RAISE NOTICE 'Created partition: %', partition_name;
                        END IF;
                    EXCEPTION WHEN undefined_table THEN
                        RAISE NOTICE 'Table gps_positions is not partitioned yet. Run PartitionGpsPositions.sql first.';
                    END;
                    $$ LANGUAGE plpgsql;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229155041_AddGpsPositionsPartitioning') THEN

                    CREATE TABLE IF NOT EXISTS partition_maintenance_log (
                        id SERIAL PRIMARY KEY,
                        table_name TEXT NOT NULL,
                        partition_name TEXT NOT NULL,
                        action TEXT NOT NULL,
                        executed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                        details TEXT
                    );
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229155041_AddGpsPositionsPartitioning') THEN

                    CREATE OR REPLACE VIEW v_gps_positions_partitions AS
                    SELECT 
                        child.relname AS partition_name,
                        pg_get_expr(child.relpartbound, child.oid) AS partition_range,
                        pg_size_pretty(pg_relation_size(child.oid)) AS size,
                        pg_relation_size(child.oid) AS size_bytes
                    FROM pg_inherits
                    JOIN pg_class parent ON pg_inherits.inhparent = parent.oid
                    JOIN pg_class child ON pg_inherits.inhrelid = child.oid
                    WHERE parent.relname = 'gps_positions'
                    ORDER BY child.relname;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229155041_AddGpsPositionsPartitioning') THEN

                    CREATE OR REPLACE FUNCTION maintain_gps_positions_partitions()
                    RETURNS void AS $$
                    DECLARE
                        future_months INT := 3;
                        current_month DATE;
                        i INT;
                    BEGIN
                        FOR i IN 0..future_months LOOP
                            current_month := date_trunc('month', CURRENT_DATE) + (i || ' months')::INTERVAL;
                            PERFORM create_gps_positions_partition(current_month::DATE);
                        END LOOP;
                    END;
                    $$ LANGUAGE plpgsql;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251229155041_AddGpsPositionsPartitioning') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251229155041_AddGpsPositionsPartitioning', '9.0.1');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records DROP CONSTRAINT "FK_fuel_records_employees_DriverId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records DROP CONSTRAINT "FK_fuel_records_gps_devices_DeviceId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records DROP CONSTRAINT "FK_fuel_records_vehicles_VehicleId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops DROP CONSTRAINT "FK_vehicle_stops_employees_DriverId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops DROP CONSTRAINT "FK_vehicle_stops_geofences_GeofenceId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops DROP CONSTRAINT "FK_vehicle_stops_gps_devices_DeviceId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops DROP CONSTRAINT "FK_vehicle_stops_vehicles_VehicleId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "Notes" TO notes;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "Longitude" TO longitude;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "Latitude" TO latitude;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "Address" TO address;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "Id" TO id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "VehicleId" TO vehicle_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "UpdatedAt" TO updated_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "StopType" TO stop_type;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "StartTime" TO start_time;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "StartMileage" TO start_mileage;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "IsAuthorized" TO is_authorized;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "InsideGeofence" TO inside_geofence;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "IgnitionOff" TO ignition_off;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "GeofenceId" TO geofence_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "FuelLevelStart" TO fuel_level_start;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "FuelLevelEnd" TO fuel_level_end;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "EndTime" TO end_time;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "EndMileage" TO end_mileage;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "DurationSeconds" TO duration_seconds;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "DriverId" TO driver_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "DeviceId" TO device_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "CreatedAt" TO created_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops RENAME COLUMN "CompanyId" TO company_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER INDEX "IX_vehicle_stops_GeofenceId" RENAME TO "IX_vehicle_stops_geofence_id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER INDEX "IX_vehicle_stops_DriverId" RENAME TO "IX_vehicle_stops_driver_id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER INDEX "IX_vehicle_stops_DeviceId" RENAME TO "IX_vehicle_stops_device_id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE gps_positions RENAME COLUMN "Rpm" TO rpm;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE gps_positions RENAME COLUMN "TemperatureC" TO temperature_c;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE gps_positions RENAME COLUMN "SendFlag" TO send_flag;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE gps_positions RENAME COLUMN "ProtocolVersion" TO protocol_version;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE gps_positions RENAME COLUMN "OdometerKm" TO odometer_km;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE gps_positions RENAME COLUMN "MemsZ" TO mems_z;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE gps_positions RENAME COLUMN "MemsY" TO mems_y;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE gps_positions RENAME COLUMN "MemsX" TO mems_x;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE gps_positions RENAME COLUMN "FuelRateLPer100Km" TO fuel_rate_l_per_100km;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "Rpm" TO rpm;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "Longitude" TO longitude;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "Latitude" TO latitude;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "Id" TO id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "VehicleId" TO vehicle_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "UpdatedAt" TO updated_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "TankCapacityLiters" TO tank_capacity_liters;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "SpeedKph" TO speed_kph;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "RefuelStation" TO refuel_station;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "RefuelCost" TO refuel_cost;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "RefuelAmount" TO refuel_amount;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "RecordedAt" TO recorded_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "OdometerKm" TO odometer_km;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "IsAnomaly" TO is_anomaly;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "IgnitionOn" TO ignition_on;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "FuelPercent" TO fuel_percent;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "FuelLiters" TO fuel_liters;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "FuelChange" TO fuel_change;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "EventType" TO event_type;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "DriverId" TO driver_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "DeviceId" TO device_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "CreatedAt" TO created_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "ConsumptionRateLPer100Km" TO consumption_rate_l_per_100km;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "CompanyId" TO company_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "AverageConsumptionLPer100Km" TO average_consumption_l_per_100km;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records RENAME COLUMN "AnomalyReason" TO anomaly_reason;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER INDEX "IX_fuel_records_DriverId" RENAME TO "IX_fuel_records_driver_id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER INDEX "IX_fuel_records_DeviceId" RENAME TO "IX_fuel_records_device_id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops ALTER COLUMN notes TYPE character varying(1000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops ALTER COLUMN address TYPE character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops ALTER COLUMN stop_type TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE gps_positions ADD bird_flight_reason character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE gps_positions ADD implicit_speed_kph double precision;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE gps_positions ADD is_bird_flight boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records ALTER COLUMN refuel_station TYPE character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records ALTER COLUMN event_type TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records ALTER COLUMN anomaly_reason TYPE character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    CREATE INDEX "IX_vehicle_stops_company_id" ON vehicle_stops (company_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    CREATE INDEX "IX_fuel_records_company_id" ON fuel_records (company_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records ADD CONSTRAINT "FK_fuel_records_employees_driver_id" FOREIGN KEY (driver_id) REFERENCES employees (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records ADD CONSTRAINT "FK_fuel_records_gps_devices_device_id" FOREIGN KEY (device_id) REFERENCES gps_devices (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE fuel_records ADD CONSTRAINT "FK_fuel_records_vehicles_vehicle_id" FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops ADD CONSTRAINT "FK_vehicle_stops_employees_driver_id" FOREIGN KEY (driver_id) REFERENCES employees (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops ADD CONSTRAINT "FK_vehicle_stops_geofences_geofence_id" FOREIGN KEY (geofence_id) REFERENCES geofences (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops ADD CONSTRAINT "FK_vehicle_stops_gps_devices_device_id" FOREIGN KEY (device_id) REFERENCES gps_devices (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    ALTER TABLE vehicle_stops ADD CONSTRAINT "FK_vehicle_stops_vehicles_vehicle_id" FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230144334_AddBirdFlightFilter') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251230144334_AddBirdFlightFilter', '9.0.1');
    END IF;
END $EF$;
COMMIT;

