import { Routes } from '@angular/router';
import { LandingComponent } from './components/landing.component';
import { LoginComponent } from './components/login.component';
import { RegisterComponent } from './components/register.component';
import { DashboardComponent } from './components/dashboard.component';
import { VehiclesComponent } from './components/vehicles.component';
import { EmployeesComponent } from './components/employees.component';
import { GpsComponent } from './components/gps.component';
import { SubscriptionComponent } from './components/subscription.component';
import { MonitoringComponent } from './components/monitoring.component';
import { ReportsComponent } from './components/reports.component';
import { GeofencesComponent } from './components/geofences.component';
import { NotificationsComponent } from './components/notifications.component';

export const routes: Routes = [
  { path: '', component: LandingComponent },
  { path: 'login', component: LoginComponent },
  { path: 'register', component: RegisterComponent },
  { path: 'dashboard', component: DashboardComponent },
  { path: 'units', component: VehiclesComponent },
  { path: 'vehicles', component: VehiclesComponent },
  { path: 'drivers', component: EmployeesComponent },
  { path: 'employees', component: EmployeesComponent },
  { path: 'gps', component: GpsComponent },
  { path: 'subscription', component: SubscriptionComponent },
  { path: 'monitoring', component: MonitoringComponent },
  { path: 'reports', component: ReportsComponent },
  { path: 'geofences', component: GeofencesComponent },
  { path: 'notifications', component: NotificationsComponent },
  { path: '**', redirectTo: '' },
];
