import { Routes } from '@angular/router';
import { LandingComponent } from './components/landing.component';
import { LoginComponent } from './components/login.component';
import { RegisterComponent } from './components/register.component';
import { DashboardComponent } from './components/dashboard.component';
import { VehiclesComponent } from './components/vehicles.component';
import { EmployeesComponent } from './components/employees.component';
import { GpsComponent } from './components/gps.component';
import { SubscriptionComponent } from './components/subscription.component';
import { MonitoringComponent } from './components/monitoring.component';
import { ReportsComponent } from './components/reports.component';
import { MonthlyReportComponent } from './components/monthly-report.component';
import { GeofencesComponent } from './components/geofences.component';
import { NotificationsComponent } from './components/notifications.component';
import { GPSDevicesComponent } from './components/gps-devices.component';
import { MaintenanceComponent } from './components/maintenance.component';
import { VehicleCostsComponent } from './components/vehicle-costs.component';
import { ProfileComponent } from './components/profile.component';
import { SettingsComponent } from './components/settings.component';
import { UserManagementComponent } from './components/user-management.component';
import { SuppliersComponent } from './components/suppliers.component';
import { DocumentsComponent } from './components/documents.component';
import { AccidentClaimsComponent } from './components/accident-claims.component';
import { MaintenanceTemplatesComponent } from './components/maintenance-templates.component';
import { adminRoutes } from './admin/admin.routes';

export const routes: Routes = [
  { path: '', component: LandingComponent },
  { path: 'login', component: LoginComponent },
  { path: 'register', component: RegisterComponent },
  { path: 'dashboard', component: DashboardComponent },
  { path: 'units', component: VehiclesComponent },
  { path: 'vehicles', component: VehiclesComponent },
  { path: 'drivers', component: EmployeesComponent },
  { path: 'employees', component: EmployeesComponent },
  { path: 'gps', component: GpsComponent },
  { path: 'gps-devices', component: GPSDevicesComponent },
  { path: 'maintenance', component: MaintenanceComponent },
  { path: 'costs', component: VehicleCostsComponent },
  { path: 'subscription', component: SubscriptionComponent },
  { path: 'monitoring', component: MonitoringComponent },
  { path: 'reports', component: ReportsComponent },
  { path: 'reports/monthly', component: MonthlyReportComponent },
  { path: 'geofences', component: GeofencesComponent },
  { path: 'notifications', component: NotificationsComponent },
  { path: 'profile', component: ProfileComponent },
  { path: 'settings', component: SettingsComponent },
  { path: 'users', component: UserManagementComponent },
  { path: 'suppliers', component: SuppliersComponent },
  { path: 'fournisseurs', component: SuppliersComponent },
  { path: 'documents', component: DocumentsComponent },
  { path: 'echeances', component: DocumentsComponent },
  { path: 'accidents', component: AccidentClaimsComponent },
  { path: 'sinistres', component: AccidentClaimsComponent },
  { path: 'entretiens-maitres', component: MaintenanceTemplatesComponent },
  { path: 'maintenance-templates', component: MaintenanceTemplatesComponent },
  { path: 'admin', children: adminRoutes },
  { path: '**', redirectTo: '' },
];
