// <auto-generated />
using System;
using System.Collections.Generic;
using GisAPI.Domain.Entities;
using GisAPI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GisAPI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GisDbContext))]
    [Migration("20251224145939_InitialCqrsArchitecture")]
    partial class InitialCqrsArchitecture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GisAPI.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hire_date");

                    b.Property<DateTime?>("LicenseExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("license_expiry");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("license_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.Geofence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlertOnEntry")
                        .HasColumnType("boolean")
                        .HasColumnName("alert_on_entry");

                    b.Property<bool>("AlertOnExit")
                        .HasColumnType("boolean")
                        .HasColumnName("alert_on_exit");

                    b.Property<int?>("AlertSpeedLimit")
                        .HasColumnType("integer")
                        .HasColumnName("alert_speed_limit");

                    b.Property<double?>("CenterLat")
                        .HasColumnType("double precision")
                        .HasColumnName("center_lat");

                    b.Property<double?>("CenterLng")
                        .HasColumnType("double precision")
                        .HasColumnName("center_lng");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<GeofencePoint[]>("Coordinates")
                        .HasColumnType("jsonb")
                        .HasColumnName("coordinates");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<double?>("Radius")
                        .HasColumnType("double precision")
                        .HasColumnName("radius");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("geofences", (string)null);
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.GeofenceEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GeofenceId")
                        .HasColumnType("integer")
                        .HasColumnName("geofence_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision")
                        .HasColumnName("speed");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("GeofenceId");

                    b.HasIndex("VehicleId");

                    b.ToTable("geofence_events", (string)null);
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.GeofenceVehicle", b =>
                {
                    b.Property<int>("GeofenceId")
                        .HasColumnType("integer")
                        .HasColumnName("geofence_id");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("GeofenceId", "VehicleId");

                    b.HasIndex("VehicleId");

                    b.ToTable("geofence_vehicles", (string)null);
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.GpsAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.HasIndex("VehicleId");

                    b.ToTable("gps_alerts", (string)null);
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.GpsDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatteryLevel")
                        .HasColumnType("integer")
                        .HasColumnName("battery_level");

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("brand");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_uid");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("firmware_version");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installation_date");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<DateTime?>("LastCommunication")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_communication");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.Property<string>("ProtocolType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("protocol_type");

                    b.Property<int?>("SignalStrength")
                        .HasColumnType("integer")
                        .HasColumnName("signal_strength");

                    b.Property<string>("SimNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sim_number");

                    b.Property<string>("SimOperator")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sim_operator");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DeviceUid")
                        .IsUnique();

                    b.ToTable("gps_devices", (string)null);
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.GpsPosition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<double?>("AltitudeM")
                        .HasColumnType("double precision")
                        .HasColumnName("altitude_m");

                    b.Property<double?>("CourseDeg")
                        .HasColumnType("double precision")
                        .HasColumnName("course_deg");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<int?>("FuelRaw")
                        .HasColumnType("integer")
                        .HasColumnName("fuel_raw");

                    b.Property<bool?>("IgnitionOn")
                        .HasColumnType("boolean")
                        .HasColumnName("ignition_on");

                    b.Property<bool>("IsRealTime")
                        .HasColumnType("boolean")
                        .HasColumnName("is_real_time");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<Dictionary<string, object>>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int?>("PowerVoltage")
                        .HasColumnType("integer")
                        .HasColumnName("power_voltage");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int?>("Satellites")
                        .HasColumnType("integer")
                        .HasColumnName("satellites");

                    b.Property<double?>("SpeedKph")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_kph");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("RecordedAt")
                        .IsDescending();

                    b.ToTable("gps_positions", (string)null);
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.MaintenancePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaintenanceRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("maintenance_record_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PartNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_number");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_cost");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceRecordId");

                    b.ToTable("maintenance_parts", (string)null);
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("invoice_number");

                    b.Property<string>("InvoiceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("invoice_url");

                    b.Property<decimal>("LaborCost")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("labor_cost");

                    b.Property<int>("MileageAtService")
                        .HasColumnType("integer")
                        .HasColumnName("mileage_at_service");

                    b.Property<DateTime?>("NextServiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_service_date");

                    b.Property<int?>("NextServiceMileage")
                        .HasColumnType("integer")
                        .HasColumnName("next_service_mileage");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<decimal>("PartsCost")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("parts_cost");

                    b.Property<string>("ProviderContact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_contact");

                    b.Property<string>("ServiceProvider")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service_provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_cost");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("VehicleId");

                    b.ToTable("maintenance_records", (string)null);
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string[]>("Features")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("features");

                    b.Property<bool>("GpsInstallation")
                        .HasColumnType("boolean")
                        .HasColumnName("gps_installation");

                    b.Property<bool>("GpsTracking")
                        .HasColumnType("boolean")
                        .HasColumnName("gps_tracking");

                    b.Property<int>("MaxVehicles")
                        .HasColumnType("integer")
                        .HasColumnName("max_vehicles");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<int[]>("AssignedVehicleIds")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("assigned_vehicle_ids");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.PrimitiveCollection<string[]>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("permissions");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.PrimitiveCollection<string[]>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("roles");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserSettingsId")
                        .HasColumnType("integer")
                        .HasColumnName("user_settings_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserSettingsId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("date_format");

                    b.Property<string>("DistanceUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("distance_unit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("SpeedUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("speed_unit");

                    b.Property<string>("TemperatureUnit")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("temperature_unit");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("timezone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VolumeUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("volume_unit");

                    b.HasKey("Id");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedDriverId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_driver_id");

                    b.Property<int?>("AssignedSupervisorId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_supervisor_id");

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("brand");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("color");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DriverName")
                        .HasColumnType("text")
                        .HasColumnName("driver_name");

                    b.Property<string>("DriverPhone")
                        .HasColumnType("text")
                        .HasColumnName("driver_phone");

                    b.Property<int?>("GpsDeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("gps_device_id");

                    b.Property<bool>("HasGps")
                        .HasColumnType("boolean")
                        .HasColumnName("has_gps");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Plate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plate_number");

                    b.Property<int?>("RentalMileage")
                        .HasColumnType("integer")
                        .HasColumnName("rental_mileage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDriverId");

                    b.HasIndex("AssignedSupervisorId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("GpsDeviceId")
                        .IsUnique();

                    b.HasIndex("Plate")
                        .HasDatabaseName("idx_vehicles_plate_number");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.VehicleCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("FuelType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fuel_type");

                    b.Property<decimal?>("Liters")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("liters");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<decimal?>("PricePerLiter")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_per_liter");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("receipt_number");

                    b.Property<string>("ReceiptUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("receipt_url");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("vehicle_costs", (string)null);
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.VehicleDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("vehicle_documents", (string)null);
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.Company", b =>
                {
                    b.HasOne("GisAPI.Domain.Entities.Subscription", "Subscription")
                        .WithMany("Companies")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GisAPI.Domain.Entities.CompanySettings", "Settings", b1 =>
                        {
                            b1.Property<int>("CompanyId")
                                .HasColumnType("integer");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("DateFormat")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("DistanceUnit")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SpeedUnit")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Timezone")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("VolumeUnit")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CompanyId");

                            b1.ToTable("companies");

                            b1.ToJson("settings");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Settings");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.Employee", b =>
                {
                    b.HasOne("GisAPI.Domain.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.Geofence", b =>
                {
                    b.HasOne("GisAPI.Domain.Entities.Company", "Company")
                        .WithMany("Geofences")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.GeofenceEvent", b =>
                {
                    b.HasOne("GisAPI.Domain.Entities.Geofence", "Geofence")
                        .WithMany("Events")
                        .HasForeignKey("GeofenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GisAPI.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Geofence");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.GeofenceVehicle", b =>
                {
                    b.HasOne("GisAPI.Domain.Entities.Geofence", "Geofence")
                        .WithMany("AssignedVehicles")
                        .HasForeignKey("GeofenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GisAPI.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Geofence");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.GpsAlert", b =>
                {
                    b.HasOne("GisAPI.Domain.Entities.GpsDevice", "Device")
                        .WithMany("Alerts")
                        .HasForeignKey("DeviceId");

                    b.HasOne("GisAPI.Domain.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId");

                    b.HasOne("GisAPI.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId");

                    b.Navigation("Device");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.GpsDevice", b =>
                {
                    b.HasOne("GisAPI.Domain.Entities.Company", "Company")
                        .WithMany("GpsDevices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.GpsPosition", b =>
                {
                    b.HasOne("GisAPI.Domain.Entities.GpsDevice", "Device")
                        .WithMany("Positions")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.MaintenancePart", b =>
                {
                    b.HasOne("GisAPI.Domain.Entities.MaintenanceRecord", "MaintenanceRecord")
                        .WithMany("Parts")
                        .HasForeignKey("MaintenanceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaintenanceRecord");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.HasOne("GisAPI.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GisAPI.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.User", b =>
                {
                    b.HasOne("GisAPI.Domain.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GisAPI.Domain.Entities.UserSettings", "Settings")
                        .WithOne()
                        .HasForeignKey("GisAPI.Domain.Entities.User", "UserSettingsId");

                    b.Navigation("Company");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.UserSettings", b =>
                {
                    b.OwnsOne("GisAPI.Domain.Entities.DisplaySettings", "Display", b1 =>
                        {
                            b1.Property<int>("UserSettingsId")
                                .HasColumnType("integer");

                            b1.Property<bool>("Animations")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Clustering")
                                .HasColumnType("boolean");

                            b1.Property<string>("MapStyle")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("RefreshInterval")
                                .HasColumnType("integer");

                            b1.Property<bool>("ShowVehicleLabels")
                                .HasColumnType("boolean");

                            b1.Property<string>("Theme")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserSettingsId");

                            b1.ToTable("user_settings");

                            b1.ToJson("display");

                            b1.WithOwner()
                                .HasForeignKey("UserSettingsId");
                        });

                    b.OwnsOne("GisAPI.Domain.Entities.NotificationSettings", "Notifications", b1 =>
                        {
                            b1.Property<int>("UserSettingsId")
                                .HasColumnType("integer");

                            b1.Property<bool>("Email")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Geofence")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Idling")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Maintenance")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Push")
                                .HasColumnType("boolean");

                            b1.Property<string>("QuietEnd")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("QuietHours")
                                .HasColumnType("boolean");

                            b1.Property<string>("QuietStart")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("Sms")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Speeding")
                                .HasColumnType("boolean");

                            b1.HasKey("UserSettingsId");

                            b1.ToTable("user_settings");

                            b1.ToJson("notifications");

                            b1.WithOwner()
                                .HasForeignKey("UserSettingsId");
                        });

                    b.Navigation("Display");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("GisAPI.Domain.Entities.Employee", "AssignedDriver")
                        .WithMany("AssignedVehiclesAsDriver")
                        .HasForeignKey("AssignedDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GisAPI.Domain.Entities.Employee", "AssignedSupervisor")
                        .WithMany("AssignedVehiclesAsSupervisor")
                        .HasForeignKey("AssignedSupervisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GisAPI.Domain.Entities.Company", "Company")
                        .WithMany("Vehicles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GisAPI.Domain.Entities.GpsDevice", "GpsDevice")
                        .WithOne("Vehicle")
                        .HasForeignKey("GisAPI.Domain.Entities.Vehicle", "GpsDeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedDriver");

                    b.Navigation("AssignedSupervisor");

                    b.Navigation("Company");

                    b.Navigation("GpsDevice");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.VehicleCost", b =>
                {
                    b.HasOne("GisAPI.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GisAPI.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("GisAPI.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Costs")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.VehicleDocument", b =>
                {
                    b.HasOne("GisAPI.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Documents")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.Company", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Geofences");

                    b.Navigation("GpsDevices");

                    b.Navigation("Users");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.Employee", b =>
                {
                    b.Navigation("AssignedVehiclesAsDriver");

                    b.Navigation("AssignedVehiclesAsSupervisor");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.Geofence", b =>
                {
                    b.Navigation("AssignedVehicles");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.GpsDevice", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Positions");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("GisAPI.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Costs");

                    b.Navigation("Documents");

                    b.Navigation("MaintenanceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
