using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GisAPI.Infrastructure.Persistence.Migrations;

/// <summary>
/// Quota mensuel de scans de factures IA :
/// - societes.invoice_scan_monthly_limit (NULL = défaut plateforme 20, 0 = désactivé),
///   modifiable par le sys admin depuis l'interface société de l'admin ;
/// - invoice_scan_logs : une ligne par scan réussi (société, utilisateur, tokens
///   Groq consommés) — sert au comptage mensuel et à l'audit de consommation.
/// Migration idempotente (IF NOT EXISTS) pour rester sans risque en prod.
/// </summary>
[DbContext(typeof(GisDbContext))]
[Migration("20260707170000_AddInvoiceScanQuota")]
public partial class AddInvoiceScanQuota : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            "ALTER TABLE societes ADD COLUMN IF NOT EXISTS invoice_scan_monthly_limit integer NULL;");

        migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS invoice_scan_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL,
    user_id integer NOT NULL,
    tokens_used integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT NOW()
);");

        migrationBuilder.Sql(
            "CREATE INDEX IF NOT EXISTS ix_invoice_scan_logs_company_id_created_at ON invoice_scan_logs (company_id, created_at);");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE IF EXISTS invoice_scan_logs;");
        migrationBuilder.Sql("ALTER TABLE societes DROP COLUMN IF EXISTS invoice_scan_monthly_limit;");
    }
}
