using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GisAPI.Infrastructure.Persistence.Migrations;

/// <summary>
/// Commandes d'abonnement du libre-service (offre GPA).
///
/// Aucun prestataire de paiement n'est branché : le client COMMANDE depuis son
/// écran Abonnement, la plateforme VALIDE une fois le règlement reçu hors
/// application, et la validation active l'abonnement. Cette table est la trace de
/// ce circuit — c'est aussi la première trace de facturation du système, qui n'en
/// avait aucune (uniquement last_payment_at / next_payment_amount, écrasés à
/// chaque renouvellement).
///
/// Idempotente (IF NOT EXISTS) — sans risque en production.
/// </summary>
[DbContext(typeof(GisDbContext))]
[Migration("20260804130000_AddSubscriptionOrders")]
public partial class AddSubscriptionOrders : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS subscription_orders (
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           integer NOT NULL REFERENCES societes(id),
    subscription_type_id integer NOT NULL REFERENCES subscription_types(id),
    billing_cycle        varchar(20) NOT NULL,
    amount               numeric(12,2) NOT NULL,
    status               varchar(20) NOT NULL DEFAULT 'pending',
    created_by_user_id   integer NOT NULL,
    processed_at         timestamptz,
    processed_by_user_id integer,
    note                 varchar(500),
    created_at           timestamptz NOT NULL DEFAULT NOW(),
    updated_at           timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_subscription_orders_status_created
    ON subscription_orders (status, created_at);
CREATE INDEX IF NOT EXISTS idx_subscription_orders_company
    ON subscription_orders (company_id);
");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE IF EXISTS subscription_orders;");
    }
}
