using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GisAPI.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddIsInterpolatedToGpsPositions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Add is_interpolated column to mark GPS positions that were
            // generated by the gap-filling algorithm (OSRM route interpolation)
            migrationBuilder.AddColumn<bool>(
                name: "is_interpolated",
                table: "gps_positions",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            // Add index for filtering interpolated positions if needed
            migrationBuilder.CreateIndex(
                name: "IX_gps_positions_is_interpolated",
                table: "gps_positions",
                column: "is_interpolated");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_gps_positions_is_interpolated",
                table: "gps_positions");

            migrationBuilder.DropColumn(
                name: "is_interpolated",
                table: "gps_positions");
        }
    }
}


