using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GisAPI.Infrastructure.Persistence.Migrations;

/// <summary>
/// Calypso 9 — standalone tow detection. Creates the <c>tow_events</c> table
/// backing the dedicated /remorquages page and the
/// <c>TowDetectionService</c> (engine-off + speed &gt; 15 km/h + real
/// displacement over a cluster of frames).
///
/// <para>Hand-written on purpose. <c>dotnet ef migrations add</c> diffs the
/// (stale) model snapshot and scaffolds drops/recreates of dozens of existing
/// tables — applying that would corrupt prod. This migration touches ONLY the
/// new table and is fully idempotent (<c>IF NOT EXISTS</c>), so it is safe even
/// if the table already exists. It carries the <c>[Migration]</c> +
/// <c>[DbContext]</c> attributes so <c>MigrateAsync()</c> discovers and runs it
/// (a manual migration without them is dead code).</para>
/// </summary>
[Migration("20260525141939_AddTowEvents")]
[DbContext(typeof(GisDbContext))]
public partial class AddTowEvents : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"
            CREATE TABLE IF NOT EXISTS tow_events (
                id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_id       integer NOT NULL,
                vehicle_id       integer NOT NULL REFERENCES vehicles(id),
                device_id        integer NOT NULL REFERENCES gps_devices(id),
                device_uid       varchar(64),
                started_at       timestamp with time zone NOT NULL,
                last_seen_at     timestamp with time zone NOT NULL,
                ended_at         timestamp with time zone,
                start_lat        double precision NOT NULL,
                start_lon        double precision NOT NULL,
                last_lat         double precision,
                last_lon         double precision,
                start_address    varchar(512),
                max_speed_kph    double precision NOT NULL,
                distance_meters  double precision NOT NULL,
                frame_count      integer NOT NULL,
                status           varchar(20) NOT NULL,
                acknowledged     boolean NOT NULL DEFAULT false,
                acknowledged_by  integer,
                acknowledged_at  timestamp with time zone,
                created_at       timestamp with time zone NOT NULL,
                updated_at       timestamp with time zone NOT NULL
            );
        ");

        migrationBuilder.Sql(@"
            CREATE INDEX IF NOT EXISTS ix_tow_events_device_id
                ON tow_events (device_id);
        ");
        migrationBuilder.Sql(@"
            CREATE INDEX IF NOT EXISTS ix_tow_events_company_status
                ON tow_events (company_id, status);
        ");
        migrationBuilder.Sql(@"
            CREATE INDEX IF NOT EXISTS ix_tow_events_started_at
                ON tow_events (started_at DESC);
        ");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"DROP TABLE IF EXISTS tow_events;");
    }
}
