using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GisAPI.Infrastructure.Persistence.Migrations;

/// <summary>
/// "Argus tunisien" — creates the <c>car_market_models</c> table: GLOBAL
/// (non-tenant) curated car-market knowledge (prix neufs/occasion, défauts
/// connus, prix pièces, décote) feeding the public AI assistant's
/// buying-advisor tools (<c>CarAdvisorService</c>). Rows are upserted at
/// startup from <c>Data/car-market-tn-seed.json</c>.
///
/// <para>Hand-written on purpose. <c>dotnet ef migrations add</c> diffs the
/// (stale) model snapshot and scaffolds drops/recreates of dozens of existing
/// tables — applying that would corrupt prod. This migration touches ONLY the
/// new table and is fully idempotent (<c>IF NOT EXISTS</c>). It carries the
/// <c>[Migration]</c> + <c>[DbContext]</c> attributes so <c>MigrateAsync()</c>
/// discovers and runs it.</para>
/// </summary>
[Migration("20260702120000_AddCarMarketModels")]
[DbContext(typeof(GisDbContext))]
public partial class AddCarMarketModels : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"
            CREATE TABLE IF NOT EXISTS car_market_models (
                id                     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                brand                  varchar(64) NOT NULL,
                model                  varchar(64) NOT NULL,
                generation             varchar(64),
                year_from              integer NOT NULL,
                year_to                integer,
                segment                varchar(32) NOT NULL,
                energy                 varchar(16) NOT NULL,
                engine_label           varchar(64),
                fiscal_power           integer,
                seats                  integer,
                new_price_tnd          numeric(12,2),
                real_consumption_l100  double precision,
                reliability_score      integer,
                buying_advice          text,
                known_issues           jsonb NOT NULL DEFAULT '[]',
                parts_prices           jsonb NOT NULL DEFAULT '[]',
                price_curve            jsonb NOT NULL DEFAULT '[]',
                is_active              boolean NOT NULL DEFAULT true,
                created_at             timestamp with time zone NOT NULL,
                updated_at             timestamp with time zone NOT NULL
            );
        ");

        migrationBuilder.Sql(@"
            CREATE INDEX IF NOT EXISTS ix_car_market_models_brand_model
                ON car_market_models (brand, model);
        ");
        migrationBuilder.Sql(@"
            CREATE INDEX IF NOT EXISTS ix_car_market_models_segment
                ON car_market_models (segment);
        ");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"DROP TABLE IF EXISTS car_market_models;");
    }
}
