using GisAPI.Application.Common.Interfaces;
using MediatR;

namespace GisAPI.Application.Features.Users.Commands.UpdateUser;

public record UpdateUserCommand(
    int Id,
    string FirstName,
    string LastName,
    string Email,
    string? Phone,
    int? RoleId,
    string? Status,
    int[]? AssignedVehicleIds = null,
    string? EmployeeRole = null,
    string? PermitNumber = null,
    string? PermitType = null,
    DateTime? PermitExpiry = null,
    string? CIN = null,
    DateTime? DateOfBirth = null,
    DateTime? HireDate = null,
    string? AccessLevel = null,
    bool? CanMonitoring = null,
    bool? CanVehicles = null,
    bool? CanDrivers = null,
    bool? CanReports = null,
    bool? CanGeofences = null,
    bool? CanMaintenance = null,
    bool? CanCosts = null,
    bool? CanFuel = null,
    bool? CanDocuments = null,
    bool? CanAccidents = null,
    bool? CanUsers = null,
    bool? CanSettings = null,
    bool? CanSuppliers = null,
    bool? CanFleetManagement = null,
    bool? CanTours = null,
    bool? CanPlayback = null,
    // Per-report permissions
    bool? CanReportTrips = null,
    bool? CanReportFuel = null,
    bool? CanReportSpeed = null,
    bool? CanReportStops = null,
    bool? CanReportMileage = null,
    bool? CanReportCosts = null,
    bool? CanReportMaintenance = null,
    bool? CanReportDaily = null,
    bool? CanReportMonthly = null,
    bool? CanReportMileagePeriod = null,
    bool? CanReportSpeedInfraction = null,
    bool? CanReportDrivingBehavior = null,
    bool? CanReportMonthlyCosts = null,
    // Alert email preferences
    bool? AlertAssurance = null,
    bool? AlertTaxeCirculation = null,
    bool? AlertVisiteTechnique = null,
    bool? AlertEntretien = null
) : ICommand;
